feat(spanner): add samples for custom timeout and retry settings
GoogleCloudPlatform/php-docs-samples pull request #1177
Opened 2020-09-21 07:00 UTC by larkee

This sample shows how to set custom timeout and retry settings on client calls.

2020-09-22 21:38 UTC, bshaffer approved these changes

2020-09-22 21:40 UTC, bshaffer requested changes

2020-09-22 21:40 UTC, bshaffer commented on spanner/spanner.php
> +$application->add((new Command('set_custom_timeout_and_retry'))
The name should be `set-custom-timeout-and-retry`. Tests are failing as a result.

2020-09-24 00:44 UTC, larkee commented
@jdpedrie Could you please confirm this is the correct way to set custom timeout and retry settings for a method call?

2020-09-24 21:44 UTC, bshaffer reviewed
@larkee This code will not work. The available options are `requestTimeout`, `retries`, and `grpcOptions`. The `retrySettings` you specified can be passed as an element of `grpcOptions`. So it should look like this:

```php
    $database->runTransaction(function (Transaction $t) use ($spanner) {
        $rowCount = $t->executeUpdate(
            "INSERT Singers (SingerId, FirstName, LastName) "
            . " VALUES (10, 'Virginia', 'Watson')",
            [
                'grpcOptions' => [
                    'retrySettings' => [
                        'initialRetryDelayMillis' => 500,
                        'retryDelayMultiplier' => 1.5,
                        'maxRetryDelayMillis' => 64000,
                        'retryableCodes' => [ApiStatus::DEADLINE_EXCEEDED, ApiStatus::UNAVAILABLE],
                    ],
                ],
                'requestTimeout' => 60000,
            ]);
        $t->commit();
        printf('Inserted %d row(s).' . PHP_EOL, $rowCount);
    });
```

Also the tests need to find a way to test this!

2020-10-20 21:38 UTC, bshaffer commented
@larkee any update?

2021-11-09 17:03 UTC, closed without merging