feat(functions): add functions_http_form_data sample
GoogleCloudPlatform/php-docs-samples pull request #1196
Opened 2020-10-20 18:53 UTC by grayside

This adds the functions_http_form_data sample, which is focused on managing file uploads.

* It uses the PSR-7 file upload implementation provided by Guzzle.
* I skipped unit tests. System tests are still very fast and run in CI.
* To facilitate experimentation, I added a composer script to start the function. Should this be added to the composer.json by default for all sample functions?

2020-10-20 21:18 UTC, bshaffer requested changes

2020-10-20 21:18 UTC, bshaffer commented on functions/http_form_data/index.php
> +            ->withStatus(405);
This would look better if we use the `Response` constructor:

```php
return new Response(405, 'Method Not Allowed: expected POST, found ' . $request->getMethod());
```

And same with all the responses below

2020-10-20 21:18 UTC, bshaffer commented on functions/http_form_data/test/DeployTest.php
> +    public function testErrorCases() : void
nit: should be `public function testErrorCases(): void`

2020-10-20 21:18 UTC, bshaffer commented on functions/http_form_data/composer.json
> +    }
nit, but I'd prefer to just manually include the `TestCasesTrait` file in the test cases than use the autoloader. This is because this file is visible to our users as part of the sample, and having the test logic here may be confusing. It's not a hill I'd die on, but since we're only talking about a single class, I'd prefer to use `require_once`

2020-10-21 17:47 UTC, grayside commented on functions/http_form_data/index.php
> +            ->withStatus(405);
Ah, thanks for this feedback! This approach is what I saw in the guzzle docs, but I think what you suggest is much cleaner.

2020-10-21 17:56 UTC, grayside commented on functions/http_form_data/index.php
> +            ->withStatus(405);
Note in practice it will look like this:

```php
return new Response(405, [], 'Method Not Allowed: expected POST, found ' . $request->getMethod());
```

The second argument is an associative array of headers. Slightly unfortunate, that really should have been after the body.

2020-10-21 17:57 UTC, grayside commented on functions/http_form_data/composer.json
> +    }
Fixed.

2020-10-21 17:57 UTC, grayside commented on functions/http_form_data/test/DeployTest.php
> +    public function testErrorCases() : void
Fixed

2020-10-21 17:57 UTC, grayside commented on functions/http_form_data/index.php
> +            ->withStatus(405);
Fixed.

2020-10-22 05:02 UTC, ace-n approved these changes

2020-10-22 05:02 UTC, ace-n commented on functions/http_form_data/index.php
> +        // Use caution when trusting the client-provided filename:
Nit: this should probably be a callout in the doc itself, not (just?) the sample.

2020-10-22 05:11 UTC, bshaffer approved these changes

2020-10-22 18:11 UTC, bshaffer approved these changes

2020-10-22 18:11 UTC, bshaffer commented on functions/http_form_data/test/SystemTest.php
> +    public function testErrorCases() : void
just a few more of these to fix (3) and we can merge!

2020-10-22 18:29 UTC, grayside commented on functions/http_form_data/index.php
> +        // Use caution when trusting the client-provided filename:
Acknowledged, will send a CL to add this to the docs also.

2020-10-22 19:58 UTC, merged