feat(functions): Add HTTP samples, round 1
GoogleCloudPlatform/php-docs-samples pull request #1197
Opened 2020-10-20 23:55 UTC by ace-n

2020-10-21 18:25 UTC, grayside requested changes
Did a first low-res pass.

2020-10-21 18:25 UTC, grayside commented on functions/concepts_filesystem/index.php
> +    return '';
Per discussion in #1198, we're not directly outputting, don't use echo. Assemble and return a string or a Response object.

2020-10-21 18:25 UTC, grayside commented on functions/concepts_filesystem/index.php
> +    $contents = scandir($directory);
nit: circuitous code.

`__DIR__` is equivalent to `dirname(__FILE__)`. Further, `scandir('.')` is equivalent to `scandir(__DIR__)`. Since this is sometimes ambiguous, I suggest we directly use __DIR__.


```suggestion
    $contents = scandir(__DIR__);
```

2020-10-21 18:25 UTC, grayside commented on functions/concepts_filesystem/test/DeployTest.php
> +        $this->assertContains($expected, $actual);
Rather than duplicate the test cases, can we use the TestCasesTrait pattern as a default practice between the test types? Where we add test cases outside the common denominator we can add additional tests.

2020-10-21 18:25 UTC, grayside commented on functions/concepts_filesystem/test/UnitTest.php
> +        $this->expectOutputRegex("/index\.php/");
Why expectedOutputRegex instead of the easier to read $this->assertContains?

2020-10-21 18:25 UTC, grayside commented on functions/concepts_requests/composer.json
> +        "curl/curl": "^2.3"
Please use guzzlehttp/guzzle as the HTTP request client.

2020-10-21 18:25 UTC, grayside commented on functions/concepts_requests/index.php
> +    $curl = new Curl\Curl();
Per note on composer.json, please switch to use the Guzzle request client.
https://packagist.org/packages/guzzlehttp/guzzle

2020-10-21 18:25 UTC, grayside commented on functions/http_cors/test/DeployTest.php
> +class DeployTest extends TestCase
Expect System and Deploy test to specifically verify OPTIONS behavior. CORS is never sufficiently tested and we should minimally be sure our OPTIONS logic works as expected.

2020-10-21 18:25 UTC, grayside commented on functions/http_method/index.php
> +                [],
Is something smart enough to inject `Content-Type: application/json`? If not this is needed.

2020-10-21 18:25 UTC, grayside commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
There is already a helloHttp function. To avoid conflicts and confusion one should be renamed.

2020-10-21 18:25 UTC, grayside commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
@bshaffer do you have thoughts on whether we should typehint as Response or the ResponseInterface?

2020-10-21 18:25 UTC, grayside commented on functions/http_method/test/DeployTest.php
> +    public function testFunction() : void
My code showed the wrong way, remove the space between parens and colon.

```suggestion
    public function testFunction(): void
```

2020-10-22 06:15 UTC, ace-n commented on functions/concepts_filesystem/index.php
> +    return '';
Done.

2020-10-22 06:15 UTC, ace-n commented on functions/concepts_filesystem/index.php
> +    $contents = scandir($directory);
Done - I was wondering if such a constant existed, thanks!

2020-10-22 06:19 UTC, ace-n commented on functions/http_method/index.php
> +                [],
I'm not sure; I'll add it in case.

2020-10-22 06:21 UTC, ace-n commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
Done.

2020-10-22 06:21 UTC, ace-n commented on functions/http_method/test/DeployTest.php
> +    public function testFunction() : void
Done.

2020-10-22 06:23 UTC, ace-n commented on functions/concepts_filesystem/test/UnitTest.php
> +        $this->expectOutputRegex("/index\.php/");
Done - stored `$response` as a variable and used `assertContains()` with that.

2020-10-22 06:30 UTC, ace-n commented on functions/concepts_requests/composer.json
> +        "curl/curl": "^2.3"
Done.

2020-10-22 06:30 UTC, ace-n commented on functions/concepts_requests/index.php
> +    $curl = new Curl\Curl();
Done.

2020-10-22 06:33 UTC, ace-n commented on functions/http_cors/test/DeployTest.php
> +class DeployTest extends TestCase
Will implement this using `TestCasesTrait`.

2020-10-22 17:08 UTC, bshaffer commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
We should recommend `ResponseInterface` as using the guzzle library is optional, but returning a `ResponseInterface` is not.

2020-10-23 05:24 UTC, ace-n commented on functions/concepts_filesystem/test/DeployTest.php
> +        $this->assertContains($expected, $actual);
Done.

2020-10-23 19:18 UTC, grayside commented
Hey Ace, a number of comments are resolved but I don't see pushed commits. Holding off on further review for now.

2020-10-25 03:53 UTC, ace-n commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
Can y'all point me to an example of how to do this? Doesn't look like [directly returning an Interface is possible](https://stackoverflow.com/questions/8084169/return-an-interface-in-php).

(IIUC we might be able to wrap our functions themselves in a `Class`, but I'm not sure if that's the cleanest approach.)

2020-10-25 03:57 UTC, ace-n commented
> Hey Ace, a number of comments are resolved but I don't see pushed commits. Holding off on further review for now.

Sorry about the confusion - commits should be live now. Thanks!

2020-10-26 16:59 UTC, bshaffer commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
@ace-n the "naive way" is possible for the Type Hint. I am not suggesting you change what the function returns, only the return type hint, e.g.:

```php
function helloHttp(ServerRequestInterface $request): ResponseInterface
```

2020-10-26 17:17 UTC, bshaffer reviewed
These look great!! I just have a few requests:

 - A few spots could use comments for clarification
 - Instead of looping over `cases` in these tests, let's use the `@dataProvider` functionality in PHPUnit
 - Let's make all these functions use `Psr\Http\Message\RequestInterface` return types

2020-10-26 17:17 UTC, bshaffer commented on functions/concepts_requests/index.php
> +    );
How about comments for the parameters that are not obvious?

```php
    $function_response = new Response(
        $url_response->getStatusCode(),
        [], // headers
        ''  // body
    );
```

2020-10-26 17:17 UTC, bshaffer commented on functions/concepts_requests/test/UnitTest.php
> +        foreach (self::cases() as $test) {
We could refactor these to use PHPUnit data providers and they'd be a bit cleaner:

```php
    /** 
      * @dataProvider cases
      */
    public function testFunction($url, $statusCode): void
    {
        $request = new ServerRequest('GET', $url]);
        $output = $this->runFunction(self::$name, [$request]);
        $this->assertEquals(
            $statusCode,
            $output->getStatusCode()
        );
    }
```

2020-10-26 17:17 UTC, bshaffer commented on functions/http_method/index.php
> +                405,
"Something Blew Up" isn't the actual status code, it's "Method Not Allowed... I think we should at least add a comment after `405` so it's clear why we're using this status code.

2020-10-26 17:17 UTC, bshaffer commented on functions/http_method/index.php
> +                'Forbidden!' . PHP_EOL
it's not clear why PUT is 403 "Forbidden", but the other methods are "Method Not Allowed". Could we add a comment explaining the reason for the difference?

2020-10-26 17:42 UTC, bshaffer commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
See https://github.com/GoogleCloudPlatform/functions-framework-php/blob/master/src/CloudEventFunctionWrapper.php#L43

2020-10-26 19:16 UTC, grayside commented on functions/concepts_requests/test/UnitTest.php
> +        foreach (self::cases() as $test) {
@bshaffer want to file a follow-up to do this to the existing tests? Ace is copying a pattern I laid out.

2020-10-26 19:19 UTC, grayside commented on functions/env_vars/test/DeployTest.php
> +        $flags['--update-env-vars'] = 'FOO=bar;';
Why the semicolon inside the quote mark? This has the potential to break the deploy command.

2020-10-26 19:21 UTC, grayside commented on functions/helloworld_get/test/SystemTest.php
> -        $resp = $this->client->get('/');
Thanks for updating helloworld_get to this pattern.

2020-10-26 21:30 UTC, ace-n commented on functions/http_method/index.php
> +function helloHttp(ServerRequestInterface $request): Response
Done - figured this out by looking at @grayside's examples.

2020-10-26 21:33 UTC, ace-n commented on functions/concepts_requests/index.php
> +    );
Done.

2020-10-26 21:34 UTC, ace-n commented on functions/http_method/index.php
> +                405,
Added explanations for each HTTP error code.

2020-10-26 21:38 UTC, ace-n commented on functions/http_method/index.php
> +                'Forbidden!' . PHP_EOL
Added use-case examples.

2020-10-26 21:39 UTC, ace-n commented on functions/env_vars/test/DeployTest.php
> +        $flags['--update-env-vars'] = 'FOO=bar;';
Removed it.

2020-10-26 23:51 UTC, ace-n commented
Tests are failing because the `FOO` environment variable is missing. (By default, it's set to `bar`.)

2020-10-28 16:21 UTC, grayside requested changes
Getting really close. I've made a point around url being in TestCasesTrait, everything else is minor.

2020-10-28 16:21 UTC, grayside commented on functions/concepts_requests/index.php
> +    $url_response = $client->get('/');
nit: inline comment linking to documentation on the guzzle http client? Maybe https://docs.guzzlephp.org/en/stable/.

2020-10-28 16:21 UTC, grayside commented on functions/concepts_requests/test/DeployTest.php
> +    public function testFunction($url, $statusCode): void
I'm against URL being abstracted to the separate TestCases, because:

1. It's not something which should ever vary
2. If you set the value to anything except empty string or the function name, the request gets 302 redirected to a Google login page, obscuring errors. This is a divergence in behavior between DeployTest and SystemTest.

2020-10-28 16:21 UTC, grayside commented on functions/http_method/index.php
> +                'error' => 'something blew up!'
nit: If the developer sent an invalid method, it's not that the server blew up. It's that the client did something wrong.

2020-10-28 18:29 UTC, ace-n commented on functions/concepts_requests/test/DeployTest.php
> +    public function testFunction($url, $statusCode): void
Done - I moved `url` back into specific test cases.

2020-10-28 18:30 UTC, ace-n commented on functions/http_method/index.php
> +                'error' => 'something blew up!'
This is the error message we use [in other languages](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/http/index.js#L75), so I'd rather keep it the same for consistency.

2020-10-28 18:33 UTC, ace-n commented on functions/concepts_requests/index.php
> +    $url_response = $client->get('/');
Added comments to this sample.

2020-10-29 20:55 UTC, bshaffer approved these changes

2020-10-29 20:58 UTC, grayside commented on functions/http_method/index.php
> +                'error' => 'something blew up!'
We probably should, but it's not worth 5 PRs just for this change.

2020-10-29 20:58 UTC, grayside approved these changes

2020-10-29 20:59 UTC, merged