feat(functions): add functions_log_helloworld
GoogleCloudPlatform/php-docs-samples pull request #1198
Opened 2020-10-21 01:53 UTC by ace-n

2020-10-21 16:28 UTC, bshaffer requested changes

2020-10-21 16:28 UTC, bshaffer commented on functions/log_helloworld/index.php
> +    fwrite($output, "HTTP message from fwrite().\n");
This should result in a "headers already sent" warning because output should be either returned as a string or in the Response object. Outputing the response in this way, if it's possible, is not something we want to highlight.

2020-10-21 16:28 UTC, bshaffer commented on functions/log_helloworld/test/DeployTest.php
> +        $this->assertContains('fwrite()', $response);
I suggest making this check for the full message, since two different lines output `fwrite()`. I'd also suggest including an `assertNotContains` for the `stderr` log message.

2020-10-21 16:28 UTC, bshaffer commented on functions/log_helloworld/test/SystemTest.php
> +    public function testFunction() : void
nit, should be `testFunction(): void`

2020-10-21 17:34 UTC, grayside requested changes

2020-10-21 17:34 UTC, grayside commented on functions/log_helloworld/index.php
> +    echo("HTTP message from echo().");
It's not typical to use echo with parentheses. Per Brent's comment though, we should consider removing anyway.

2020-10-21 17:34 UTC, grayside commented on functions/log_helloworld/index.php
> +    fwrite($error, "Log entry from fwrite().\n");
This is not specifically errors in any way, STDOUT and STDERR are treated identically by GCF.

I suggest we use a more general variable name, preferably concise:

```suggestion
    $log = fopen('php://stderr', 'wb');
    fwrite($log, "Log entry from fwrite().\n");
```

2020-10-21 17:34 UTC, grayside commented on functions/log_helloworld/index.php
> +    return '';
Ideally this sample might also make a statement about `error_log()`, does it work? Does it need special config?

2020-10-21 17:34 UTC, grayside commented on functions/log_helloworld/index.php
> +}
While it does push at the scope limits, I think it would be worth considering showcasing how to log with severity:

```
fwrite($log, json_encode([
  'message' => 'Structured log with error severity',
  'severity' => 'error'
]);
```

2020-10-21 17:34 UTC, grayside commented on functions/log_helloworld/index.php
> +function helloWorld(ServerRequestInterface $request): string
Should this not be `helloLogging` or similar? This seems like it has potential to lead to conflicts if there's another helloWorld function under test.

2020-10-21 17:34 UTC, grayside commented on functions/log_helloworld/test/UnitTest.php
> +        $this->expectOutputRegex("/fwrite()/");
Why not assertContains on these?

2020-10-21 17:34 UTC, grayside commented on functions/log_helloworld/index.php
> +    fwrite($output, "HTTP message from fwrite().\n");
In which case, you are suggesting all the code in this function above this line be removed?

Also, (FF behavior question) if we don't want developers to write to php://output in their function, should we buffer and discard that output? Or even redirect to stderr to simplify logging?

2020-10-22 05:03 UTC, ace-n commented on functions/log_helloworld/index.php
> +    fwrite($output, "HTTP message from fwrite().\n");
The main thing I'm trying to showcase here is "How can I write `error`-level (or at least `warning`-level) log messages to Stackdriver?"

2020-10-22 05:09 UTC, bshaffer commented on functions/log_helloworld/test/UnitTest.php
> +        $this->expectOutputRegex("/fwrite()/");
To use assertContains, we'd have to wrap the above include file in output buffers. This is preferable, as the above code (it's not obvious) only checks the final `expectOutputRegex`. Something like this would work:

```php

ob_start();
$funcReturn = self::runFunction(self::$name, [$request]);
$output = ob_get_clean();

$this->assertRegexp("/echo()/", output);
```

2020-10-22 05:12 UTC, grayside commented on functions/log_helloworld/index.php
> +    fwrite($output, "HTTP message from fwrite().\n");
The code you currently have only applies default severity level. I include code on how to add severity in one of my comments below, as well as in the form data PR.

2020-10-22 05:13 UTC, grayside commented on functions/log_helloworld/test/UnitTest.php
> +        $this->expectOutputRegex("/fwrite()/");
This assumes not switching to return a string value, which I thought was preferred?

2020-10-22 05:20 UTC, ace-n commented on functions/log_helloworld/test/DeployTest.php
> +        $this->assertContains('fwrite()', $response);
Done.

2020-10-22 05:23 UTC, ace-n commented on functions/log_helloworld/test/UnitTest.php
> +        $this->expectOutputRegex("/fwrite()/");
I was aiming for brevity last time. Changed to `assertContains`.

2020-10-22 05:23 UTC, ace-n commented on functions/log_helloworld/index.php
> +function helloWorld(ServerRequestInterface $request): string
That's the function name Node uses. 🤷 

I'll change it to `helloLogging` for PHP though.

2020-10-22 05:31 UTC, ace-n commented on functions/log_helloworld/index.php
> +}
Will test this on Cloud Functions itself.

2020-10-22 06:01 UTC, ace-n commented on functions/log_helloworld/index.php
> +    return '';
It's a no-op. (I'll mention that though.)

2020-10-22 06:02 UTC, ace-n commented on functions/log_helloworld/index.php
> +}
Didn't work - it logged the JSON payload as an `INFO` message.

2020-10-22 06:02 UTC, ace-n commented on functions/log_helloworld/index.php
> +    fwrite($error, "Log entry from fwrite().\n");
Done.

2020-10-22 06:04 UTC, ace-n commented on functions/log_helloworld/index.php
> +    echo("HTTP message from echo().");
Removed the parenthesis for now.

@bshaffer LMK if we should remove the `echo` outright.

2020-10-22 06:04 UTC, ace-n commented on functions/log_helloworld/test/SystemTest.php
> +    public function testFunction() : void
Done.

2020-10-22 06:39 UTC, grayside commented on functions/log_helloworld/index.php
> +}
Sorry, I forget to point the need for a newline termination, such as PHP_EOL.

Here's my experiment:

```
use Psr\Http\Message\ServerRequestInterface;

function severity(ServerRequestInterface $request): string
{
    $stream = fopen('php://stderr', 'wb');
    $severities = [
        'DEBUG',
        'NOTICE',
        'INFO',
        'WARNING',
        'ERROR',
        'CRITICAL',
        'ALERT',
        'EMERGENCY',
    ];

    foreach ($severities as $severity) {
        $msg = [
            'message' => 'Log with severity ' . $severity,
            'severity' => $severity,
        ];
        fwrite($stream, json_encode($msg) . PHP_EOL);
    }
}
```

Then, checking stackdriver:
<img width="681" alt="Screen Shot 2020-10-21 at 11 35 34 PM" src="https://user-images.githubusercontent.com/283489/96834207-7625bf80-13f6-11eb-9648-f247dec1a592.png">

2020-10-22 17:09 UTC, bshaffer commented on functions/log_helloworld/index.php
> +    echo("HTTP message from echo().");
Yes, I think it's best to remove it!

2020-10-22 17:10 UTC, bshaffer commented on functions/log_helloworld/index.php
> +}
beautiful

2020-10-22 17:11 UTC, bshaffer commented on functions/log_helloworld/test/UnitTest.php
> +        $output = $this->getActualOutput();
oh, that's better eh? 👍

2020-10-22 19:05 UTC, grayside commented on functions/log_helloworld/index.php
> +    error_log('error_log does not log in Cloud Functions!');
If error_log doesn't log in cloud functions, this sounds like the environment configuration should be improved to do so. Could you file a bug or shall I?

2020-10-23 00:53 UTC, ace-n commented on functions/log_helloworld/index.php
> +    echo("HTTP message from echo().");
Done.

2020-10-23 02:50 UTC, ace-n commented on functions/log_helloworld/index.php
> +}
@grayside Thanks for investigating - done.

2020-10-23 02:51 UTC, ace-n commented on functions/log_helloworld/test/UnitTest.php
> +        $output = $this->getActualOutput();
(Yeah, we had to get the output _somehow_.)

2020-10-23 03:36 UTC, ace-n commented on functions/log_helloworld/index.php
> +    error_log('error_log does not log in Cloud Functions!');
Done - bug filed. 🙂

2020-10-23 03:37 UTC, ace-n commented on functions/log_helloworld/index.php
> +    fwrite($output, "HTTP message from fwrite().\n");
Looks like the newlines were the problem. Added.

2020-10-23 03:46 UTC, ace-n commented
@grayside N.B: I chose not to use `TestCaseTrait` here, since this sample is fairly simple. LMK if I should change that!

2020-10-23 18:07 UTC, grayside requested changes

2020-10-23 18:07 UTC, grayside commented on functions/log_helloworld/composer.json
> +    }
Per chat discussion, let's add a start script. The plan doc has an example.

2020-10-23 18:07 UTC, grayside commented on functions/log_helloworld/index.php
> +    fwrite($output, "HTTP message from fwrite().\n");
Per Brent's initial comment, we **do not* want to highlight that developers can create a function response by writing to stdout. In that case, the print and php://output statements should be removed.

2020-10-23 18:07 UTC, grayside commented on functions/log_helloworld/index.php
> +    // Code running in Google Cloud Functions itself
nit: Not sure what the line length policy is in this repo, usually in PHP at least 80 characters.

2020-10-23 18:07 UTC, grayside commented on functions/log_helloworld/index.php
> +    return '';
We should be able to remove or change the typehint to `void` and skip this return statement.

2020-10-23 18:07 UTC, grayside commented on functions/log_helloworld/test/UnitTest.php
> +    private static function runFunction($functionName, array $params = []): string
Note if we change the function to return void, this will also need to be changed, if only to `return ''` here instead.

2020-10-24 00:42 UTC, ace-n commented on functions/log_helloworld/index.php
> +    // Code running in Google Cloud Functions itself
This is a URL, not sure if I can make it that much shorter (other than a `goo.gl` or similar link).

2020-10-24 00:43 UTC, ace-n commented on functions/log_helloworld/index.php
> +    return '';
Done.

2020-10-24 00:44 UTC, ace-n commented on functions/log_helloworld/test/UnitTest.php
> +    private static function runFunction($functionName, array $params = []): string
Done. (I had this function return `void` as well.)

2020-10-26 17:24 UTC, grayside commented on functions/log_helloworld/index.php
> +    // Code running in Google Cloud Functions itself
Not talking about a URL being too long, I'm talking about the comment lines in general being too short.

2020-10-26 17:24 UTC, grayside commented on functions/log_helloworld/index.php
> +    // writes log entries to Stackdriver Logging
"Stackdriver" is no longer used. Switch to "Cloud Logging".

2020-10-26 23:24 UTC, ace-n commented on functions/log_helloworld/index.php
> +    // writes log entries to Stackdriver Logging
Done.

2020-10-26 23:50 UTC, ace-n commented on functions/log_helloworld/index.php
> +    // Code running in Google Cloud Functions itself
Ah - I usually use a smaller text editor window, and erroneously figured this couldn't hurt. (Fixed.)

2020-10-29 20:56 UTC, grayside approved these changes

2020-10-29 21:01 UTC, bshaffer approved these changes

2020-10-29 21:01 UTC, merged