[DO NOT MERGE] feat(functions): add scopes sample
GoogleCloudPlatform/php-docs-samples pull request #1199
Opened 2020-10-21 01:54 UTC by ace-n

**Do not merge** until we determine how to handle global variables.

2020-10-21 01:58 UTC, ace-n commented on functions/tips_scopes/index.php
> +$instanceVar = _heavyComputation();
This line is **not** executed when running the tests locally, but it **is** executed by `DeployTest` (i.e. on Cloud Functions itself).

@grayside @bshaffer I presume this is a bug with the local test setup?

2020-10-23 19:39 UTC, grayside requested changes

2020-10-23 19:39 UTC, grayside commented on functions/tips_scopes/index.php
> +$instanceVar = _heavyComputation();
I can't see how local setup affects this offhand. However, this may be related to a flaw in the approach of the sample. Each request causes the PHP code to be reloaded, so there's no optimization in using global scope in this way.

In order to preserve a heavy computation for reuse, I suggest writing the data to the filesystem with `file_put_contents()` and then `file_get_contents()` when needed. No need for global variables, just a defined constant on where to look for this cache. Would also be useful to add a comment that the filesystem is in-memory, so expected to be fast.

2020-10-23 20:06 UTC, ace-n commented on functions/tips_scopes/index.php
> +$instanceVar = _heavyComputation();
@bshaffer is that an appropriately idiomatic solution?

(We can also say "PHP does not support caching variables globally".)

2020-10-29 17:23 UTC, grayside requested changes

2020-10-29 17:23 UTC, grayside commented on functions/tips_scopes/index.php
> +    $cachePath = '/tmp/cached_value.txt';
In support of local development, we should not assume `/tmp` is the temp filesystem.

I suggest one of two paths:

* Use PHP's built-in functions to identify the temp directory and create a file.

https://github.com/GoogleCloudPlatform/php-docs-samples/blob/02da6bac19126b68136bdfa52e28549ded891084/functions/http_form_data/index.php#L43

* Create a temp directory inside the sample directory to facilitate developers examining the cache when they run the function locally.

2020-10-30 02:51 UTC, ace-n commented on functions/tips_scopes/index.php
> +    $cachePath = '/tmp/cached_value.txt';
Used a built-in function here.

2020-10-30 18:44 UTC, bshaffer reviewed
I do think it'd be better to use a caching library (PSR-6) for these samples

2020-10-30 18:44 UTC, bshaffer commented on functions/tips_scopes/index.php
> +    $cachePath = sys_get_temp_dir() . 'cached_value.txt';
You need a directory separator, so `/cached_value.txt`

2020-11-04 23:35 UTC, bshaffer approved these changes

2020-11-04 23:35 UTC, bshaffer commented on functions/tips_scopes/test/SystemTest.php
> +class SystemTest extends TestCase
nit: can we call this `LocalTest.php`? That's the naming I use elsewhere in this repo

2020-11-04 23:42 UTC, ace-n commented on functions/tips_scopes/test/SystemTest.php
> +class SystemTest extends TestCase
Done.

2020-11-09 21:44 UTC, grayside requested changes

2020-11-09 21:44 UTC, grayside commented on functions/tips_scopes/test/DeployTest.php
> +    public function testFunction() : void
nit
```suggestion
    public function testFunction(): void
```

2020-11-09 21:44 UTC, grayside commented on functions/tips_scopes/test/LocalTest.php
> +class SystemTest extends TestCase
Align class name to file name.

Per discussion in #1213, we're talking about renaming this file & class to IntegrationTest, but the current name is SystemTest.

2020-11-09 21:44 UTC, grayside commented on functions/tips_scopes/test/LocalTest.php
> +    private static $name = 'scopeDemo';
Requires rename.

```suggestion
    private static $entryPoint = 'scopeDemo';
```

2020-11-09 21:44 UTC, grayside commented on functions/tips_scopes/test/DeployTest.php
> +    private static $name = 'scopeDemo';
Requires rename.

```suggestion
    private static $entryPoint = 'scopeDemo';
```

2020-11-09 21:44 UTC, grayside commented on functions/tips_scopes/test/DeployTest.php
> +        $this->assertContains('Per instance: 120', $output);
This is a fairly shallow test here. Would running the request twice to confirm persistence of in-memory data be worthwhile? The risk of spinning up a second instance could be mitigated by running with --max-instances=1

2020-11-09 21:44 UTC, grayside commented on functions/tips_scopes/test/DeployTest.php
> +        $resp = $this->client->get('', [
This should be a POST to ensure no edge cases replay the GET request and throw off the per-instance result.

2020-11-10 00:04 UTC, ace-n commented on functions/tips_scopes/test/LocalTest.php
> +    private static $name = 'scopeDemo';
Done.

2020-11-10 00:05 UTC, ace-n commented on functions/tips_scopes/test/DeployTest.php
> +        $this->assertContains('Per instance: 120', $output);
How should we do that? Maybe a timestamp-based and/or random value?

2020-11-10 00:06 UTC, ace-n commented on functions/tips_scopes/test/DeployTest.php
> +        $resp = $this->client->get('', [
Changed all `GET`s to `POST`s for this sample.

2020-11-10 00:06 UTC, ace-n commented on functions/tips_scopes/test/DeployTest.php
> +    private static $name = 'scopeDemo';
Done.

2020-11-10 03:55 UTC, ace-n commented on functions/tips_scopes/test/DeployTest.php
> +    public function testFunction() : void
Done.

2020-11-10 03:57 UTC, ace-n commented on functions/tips_scopes/test/LocalTest.php
> +class SystemTest extends TestCase
Done.

2020-11-10 19:31 UTC, grayside commented on functions/tips_scopes/test/DeployTest.php
> +        $this->assertContains('Per instance: 120', $output);
Ah, I had it in my head that heavyComputation was adding to the previous value. Given that, the way we might test this is if there's a log entry when priming the cache and otherwise not. Note I'm more interested in this for the Integration Test than the DeployTest.

2020-11-10 22:26 UTC, bshaffer reviewed
a bunch of nits but otherwise this still looks great!

2020-11-10 22:26 UTC, bshaffer commented on functions/tips_scopes/composer.json
> +        "google/cloud-functions-framework": "^0.6"
This should be updated to `^0.7.1` now!

2020-11-10 22:26 UTC, bshaffer commented on functions/tips_scopes/test/UnitTest.php
> +    public static function setUpBeforeClass() : void
nit: should be `public static function setUpBeforeClass(): void`

2020-11-10 22:26 UTC, bshaffer commented on functions/tips_scopes/test/UnitTest.php
> +    public function testFunction() : void
nit: should be `public function testFunction(): void`

2020-11-10 22:26 UTC, bshaffer commented on functions/tips_scopes/test/UnitTest.php
> +    private static function runFunction($functionName, array $params = []) : string
`private static function runFunction($functionName, array $params = []): string`

2020-11-11 02:10 UTC, ace-n commented on functions/tips_scopes/composer.json
> +        "google/cloud-functions-framework": "^0.6"
Done.

2020-11-11 02:11 UTC, ace-n commented on functions/tips_scopes/test/UnitTest.php
> +    public function testFunction() : void
Done.

2020-11-11 02:11 UTC, ace-n commented on functions/tips_scopes/test/UnitTest.php
> +    public static function setUpBeforeClass() : void
Done.

2020-11-11 02:12 UTC, ace-n commented on functions/tips_scopes/test/UnitTest.php
> +    private static function runFunction($functionName, array $params = []) : string
Done.

2020-11-11 02:12 UTC, ace-n commented on functions/tips_scopes/index.php
> +    $cachePath = sys_get_temp_dir() . 'cached_value.txt';
Done.

2020-11-11 02:25 UTC, ace-n commented on functions/tips_scopes/test/DeployTest.php
> +        $this->assertContains('Per instance: 120', $output);
Got it - I went ahead and added a `Response` test to both `IntegrationTest` and `DeployTest`.

2020-11-11 18:46 UTC, grayside approved these changes

2020-11-11 22:51 UTC, merged