chore(functions): clean up existing helloworld samples
GoogleCloudPlatform/php-docs-samples pull request #1210
Opened 2020-10-27 02:03 UTC by ace-n

- [x] Use `dataProvider`.
- [x] Make test variables `camelCase`.

2020-10-27 16:46 UTC, grayside requested changes

2020-10-27 16:46 UTC, grayside commented on functions/helloworld_get/test/TestCasesTrait.php
> +                'url' => '',
I'd prefer not to have `url` here for a couple reasons.

1. This should never vary.
2. SystemTest always starts with `/`. DeployTest if it is changed must always start with the functionName.

2020-10-28 21:14 UTC, ace-n commented
I'm going to hold off on this until #1197 is merged.

2020-10-31 00:07 UTC, ace-n commented
#1197 was merged - I scrapped the old PR in favor of a new branch, though.

(@grayside this one use `url`.)

2020-11-02 20:44 UTC, bshaffer approved these changes

2020-11-02 21:05 UTC, grayside approved these changes

2020-11-02 21:06 UTC, merged