[WIP] chore(functions): add Slack samples
GoogleCloudPlatform/php-docs-samples pull request #1212
Opened 2020-10-30 07:20 UTC by ace-n

**Do not merge** until the `DeploymentTests` are debugged. (They're running into some weird permissions issue.)

I've manually confirmed that the sample itself **does** work with Slack.

2020-10-30 20:34 UTC, bshaffer commented on functions/slack_slash_command/index.php
> +
nit: unnecessary newline

2020-10-30 20:34 UTC, bshaffer commented on functions/slack_slash_command/composer.json
> +    }
We should add the helpful tool which removes all client services except the ones we [explicitly ask for](https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services):

```json
{
    "require": {
        "google/cloud-functions-framework": "^0.6",
        "google/apiclient": "^2.8"
    },
    "scripts": {
        "post-update-cmd": "Google\\Task\\Composer::cleanup"
    },
    "extra": {
        "google/apiclient-services": [
            "Kgsearch"
        ]
    }
}
```

2020-10-30 20:34 UTC, bshaffer commented on functions/slack_slash_command/index.php
> +
nit: extra newline

2020-10-30 20:34 UTC, bshaffer commented on functions/slack_slash_command/index.php
> +    //var_dump($plaintext);
remove `var_dump` comment

2020-10-30 20:34 UTC, bshaffer commented on functions/slack_slash_command/index.php
> +    //$nowInMs = round(microtime(true) * 1000);
I don't think this is supposed to be here...

2020-10-30 21:05 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    //$nowInMs = round(microtime(true) * 1000);
Forgot to push the commit that removed this. 😄 Done.

2020-10-30 21:06 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    //var_dump($plaintext);
Done.

2020-10-30 21:06 UTC, ace-n commented on functions/slack_slash_command/index.php
> +
Removed.

2020-10-30 21:07 UTC, ace-n commented on functions/slack_slash_command/index.php
> +
Removed.

2020-10-30 21:07 UTC, ace-n commented on functions/slack_slash_command/composer.json
> +    }
Added.

2020-10-30 22:23 UTC, grayside requested changes

2020-10-30 22:23 UTC, grayside commented on functions/slack_slash_command/index.php
> +    * constants, so we fetch these values within PHP functions themselves.
This comment isn't quite right. PHP supports global constants and global state, it just doesn't preserve that state between requests. If you had a use case of multiple API requests to Knowledge Graph as part of a single function execution, you'd still want to stick the service variable in a global, or as a static variable in the function. (static variables inside a function stick around between function calls, though not between requests).

Actions:
1. Adjust comment content.
2. Consider if we want to teach reuse by default, even if it's not helpful in this use case.

2020-10-30 22:23 UTC, grayside commented on functions/slack_slash_command/index.php
> +        return new Response(405, [], '');
I think being explicit with the first parameters was useful for the initial HTTP introductions, but at this point more conciseness makes sense. PHP doesn't require you to specify all the parameters on the caller's side where there's a default in the function signature. Therefore, this could be:

```suggestion
        return new Response(405);
```

However, without any text in the response, this might confuse developers trying out the function to see no response. It would be more helpful to return a response that will show up in non-verbose `curl`, even if only "Method not allowed".

This feedback also applies to the 400 and 403 responses below.

2020-10-30 22:23 UTC, grayside commented on functions/slack_slash_command/index.php
> +    // Slack sends requests as URL-encoded strings
Specifically `application/x-www-form-urlencoded` or something else?

2020-10-30 22:23 UTC, grayside commented on functions/slack_slash_command/index.php
> +    $kgResponse = searchKnowledgeGraph($query);
What if searchKnowledgeGraph fails or throws an exception? Does that change the message to be sent for formatting?

@bshaffer here's an example of an HTTP function needing support from https://github.com/GoogleCloudPlatform/functions-framework-php/issues/60.

2020-10-30 22:23 UTC, grayside commented on functions/slack_slash_command/index.php
> +function formatSlackMessage($kgResponse, $query): string
I started us off by typehinting the return values, but we should probably declare strict types and include typehints for the function parameters as well.

2020-10-30 22:23 UTC, grayside commented on functions/slack_slash_command/index.php
> +    $entityList = $kgResponse["itemListElement"];
Does $kgResponse have a failure mode which is not a thrown exception but for which itemListElement is not populated?

```
PHP Notice:  Undefined index: itemListElement in php shell code on line 1
```

This warning can be suppressed with a check or a default value, such as a null coalescing operator.

```suggestion
    $entityList = $kgResponse["itemListElement"] ?? null;
```

2020-10-31 00:26 UTC, ace-n commented on functions/slack_slash_command/test/TestCasesTrait.php
> +        $SLACK_SIGNATURE = getenv('SLACK_TEST_SIGNATURE');
Good catch - removed.

2020-10-31 00:27 UTC, ace-n commented on functions/slack_slash_command/index.php
> +*/
Done.

2020-10-31 00:28 UTC, ace-n commented on functions/slack_slash_command/index.php
> +*/
Done.

2020-10-31 00:30 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    $entityList = $kgResponse["itemListElement"];
Done.

2020-10-31 00:36 UTC, ace-n commented on functions/slack_slash_command/index.php
> +        return new Response(405, [], '');
Done.

2020-10-31 01:00 UTC, ace-n commented on functions/slack_slash_command/index.php
> +function searchKnowledgeGraph($query): Google_Service_Kgsearch_SearchResponse
I presume you're referring to `Google_Service_Kgsearch_SearchResponse` here?

(I added a `use` statement for that in the `functions_slack_setup` section near the top of the file, but I'm fairly sure it's a no-op.)

2020-10-31 01:39 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    * constants, so we fetch these values within PHP functions themselves.
I think my main concern here is actually that the local testing framework (in particular the `UnitTest`s) doesn't execute these "global" statements.

If we can find a way to address that, I can move these into global scope + delete the comment outright. (Given that **a)** making these global seems idiomatic in PHP, and **b)** we call out PHP's caching behavior - or lack thereof - in `functions_tips_scopes`, I'm happy to drop the mention of it here altogether.)

2020-10-31 01:42 UTC, ace-n commented on functions/slack_slash_command/index.php
> +function formatSlackMessage($kgResponse, $query): string
Happy to do this for primitives and objects, but is there a good way to do this for collections (arrays/maps)? (It [doesn't seem like](https://stackoverflow.com/a/34273821) PHP collections allow their constituent values to be type-checked.)

2020-10-31 01:53 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    $entityList = $kgResponse["itemListElement"];
I believe `itemListElement` is supposed to be defined (but empty!) _even if_ there are no matching results. (There _is_ a test case for this behavior.)

Happy to add a null-coalescing operator for defensive programming though (e.g. to mitigate errors and/or unexpected changes at the API level), if you think that's worth doing.

2020-10-31 01:55 UTC, ace-n commented on functions/slack_slash_command/index.php
> +require_once './vendor/autoload.php';
Done.

2020-10-31 02:09 UTC, ace-n commented on functions/slack_slash_command/test/TestCasesTrait.php
> +        return [
Done.

2020-10-31 02:53 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    // Slack sends requests as URL-encoded strings
Yes - I've added a comment to this effect.

2020-10-31 02:57 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    $kgResponse = searchKnowledgeGraph($query);
For better or for worse - currently, the other samples don't explicitly handle this (and instead pass it off to the runtime itself to handle).

That said, I'm open to changing this pattern if you think it's worthwhile. (Aside: I don't know what the consensus is on "whether (or not) to handle exceptional behavior in samples". Maybe @jmdobry or @JustinBeckwith have some opinions on this?)

2020-11-03 23:36 UTC, grayside commented on functions/slack_slash_command/index.php
> +function formatSlackMessage($kgResponse, $query): string
We can typehint as array, and sometimes worth defaulting to an empty array as well.

2020-11-03 23:38 UTC, grayside commented on functions/slack_slash_command/index.php
> +function searchKnowledgeGraph($query): Google_Service_Kgsearch_SearchResponse
Yes. Everything should have a use statement. If nothing else it's how the IDE will identify what you're referencing.

2020-11-04 16:56 UTC, bshaffer commented on functions/slack_slash_command/index.php
> +     * constants, so we fetch these values within PHP functtions themselves.
Yes, I agree. Only if in the context of the documentation, we need to add the callout to differentiate from the other languages.

2020-11-04 21:02 UTC, ace-n commented on functions/slack_slash_command/index.php
> +    $kgResponse = searchKnowledgeGraph($query);
@grayside agreed - I'll stick to cross-sample consistency for now.

Perhaps it's worth filing a bug internally to revise this later (across languages), though?

2020-11-04 21:26 UTC, ace-n commented on functions/slack_slash_command/index.php
> +     * constants, so we fetch these values within PHP functtions themselves.
> Only if in the context of the documentation, we need to add the callout to differentiate from the other languages.

Yep - that's my concern. I'll reword this.

2020-11-04 21:30 UTC, ace-n commented on functions/slack_slash_command/index.php
> +     */
Reworded, per the other thread.

2020-11-04 23:40 UTC, ace-n commented on functions/slack_slash_command/index.php
> +function formatSlackMessage($kgResponse, $query): string
Used `object` here.

2020-11-04 23:42 UTC, bshaffer approved these changes
One nit, otherwise nice work!

2020-11-04 23:42 UTC, bshaffer commented on functions/slack_slash_command/test/SystemTest.php
> +class SystemTest extends TestCase
Request to rename this to `LocalTest.php`

2020-11-04 23:44 UTC, ace-n commented on functions/slack_slash_command/test/SystemTest.php
> +class SystemTest extends TestCase
Done.

2020-11-06 01:25 UTC, ace-n commented
The tests are failing with:

> InvalidArgumentException: **Missing required property: entryPoint** in /tmpfs/src/github/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/GcloudWrapper/CloudFunction.php:83

@grayside is this something a Kokoro re-run will solve? If so, would you mind kicking that off once you've finished merging changes to `php-tools`?

(If not...happy to update this PR accordingly. 🙂)

2020-11-06 18:11 UTC, grayside requested changes

2020-11-06 18:11 UTC, grayside commented on functions/slack_slash_command/test/LocalTest.php
> +class SystemTest extends TestCase
File Name doesn't match class name. I believe in #1213 we are discussing standardizing on `IntegrationTest`.

2020-11-06 18:11 UTC, grayside commented on functions/slack_slash_command/test/TestCasesTrait.php
> +
nit: extra line

2020-11-06 18:11 UTC, grayside commented on functions/slack_slash_command/test/TestCasesTrait.php
> +    $key = getenv('SLACK_SECRET');
nit: this is an undocumented requirement. There should be a $this->requireEnv() statement somewhere.

2020-11-06 18:11 UTC, grayside commented on functions/slack_slash_command/test/UnitTest.php
> +class UnitTest extends TestCase
Unit test shouldn't be dependent on integrations with Slack/Google APIs. If we're not going to implement mocks and the integration/system/etc test isn't too slow, I think we can delete the UnitTest.

2020-11-06 18:11 UTC, grayside commented on functions/slack_slash_command/index.php
> +     */
Ditto from `isValidSlackWebhook()`.

2020-11-09 05:34 UTC, ace-n commented on functions/slack_slash_command/test/TestCasesTrait.php
> +
Done.

2020-11-09 05:34 UTC, ace-n commented on functions/slack_slash_command/test/LocalTest.php
> +class SystemTest extends TestCase
Renamed to `IntegrationTest`

2020-11-09 05:35 UTC, ace-n commented on functions/slack_slash_command/test/UnitTest.php
> +class UnitTest extends TestCase
I'm not opposed. @bshaffer sound OK to you?

2020-11-09 05:36 UTC, ace-n commented on functions/slack_slash_command/test/DeployTest.php
> +        $envVars .= 'KG_API_KEY=' . getenv('KG_API_KEY');
Done.

2020-11-09 05:36 UTC, ace-n commented on functions/slack_slash_command/index.php
> +     */
Got it - deleted this comment.

2020-11-09 05:37 UTC, ace-n commented on functions/slack_slash_command/index.php
> +     */
Comment removed.

2020-11-09 08:11 UTC, ace-n commented on functions/slack_slash_command/test/TestCasesTrait.php
> +    $key = getenv('SLACK_SECRET');
Added it in the tests themselves.

(I think this is attached to some of the `Trait`s we use, so I'm doubtful if we can use it within `TestCaseTrait.php` - though that might be the ideal solution.)

2020-11-09 08:12 UTC, ace-n commented on functions/slack_slash_command/test/DeployTest.php
> +    protected static function deployFlags(array $flags = []): array
Good catch, updated.

2020-11-09 08:12 UTC, ace-n commented on functions/slack_slash_command/test/DeployTest.php
> +        $flags['--update-env-vars'] = '"' . $envVars . '"';
Apparently not! (I switched to `doDeploy()`, which doesn't appear to require this.)

2020-11-09 18:02 UTC, bshaffer commented on functions/slack_slash_command/test/UnitTest.php
> +class UnitTest extends TestCase
I am ambivalent, but it sounds ok to me! The integration tests should be sufficient.

2020-11-10 00:01 UTC, ace-n commented on functions/slack_slash_command/test/UnitTest.php
> +class UnitTest extends TestCase
OK - I'll remove this.

2020-11-10 19:01 UTC, grayside commented on functions/slack_slash_command/test/DeployTest.php
> +        $envVars .= 'KG_API_KEY=' . getenv('KG_API_KEY');
Require should be before use: this will create a somewhat fuzzy error on gcloud deploy and never call testFunction().

2020-11-10 19:18 UTC, grayside requested changes

2020-11-10 19:18 UTC, grayside commented on functions/slack_slash_command/test/IntegrationTest.php
> +        $this->requireEnv('KG_API_KEY');
I don't see a customization of the `doRun()` method, so presumably the function framework is being started without these variables. Is test coverage deep enough if it passes without those variables present in the function?

2020-11-10 19:18 UTC, grayside commented on functions/slack_slash_command/test/IntegrationTest.php
> +        $this->requireEnv('KG_API_KEY');
nit: Should check these variables before the function is started/deployed to ensure fast failure and clear error message.

2020-11-11 10:52 UTC, ace-n commented on functions/slack_slash_command/test/IntegrationTest.php
> +        $this->requireEnv('KG_API_KEY');
Thanks for clarifying - I wasn't quite sure where to put these. Moved to `doRun()`.

2020-11-11 10:52 UTC, ace-n commented on functions/slack_slash_command/test/IntegrationTest.php
> +        $this->requireEnv('KG_API_KEY');
Done - moved checks to `doRun()` as suggested above.

2020-11-11 10:53 UTC, ace-n commented on functions/slack_slash_command/test/DeployTest.php
> +        $envVars .= 'KG_API_KEY=' . getenv('KG_API_KEY');
Moved to `doRun()` - I assume that will suffice?

2020-11-11 18:37 UTC, grayside approved these changes
Thanks for addressing the many rounds of feedback on this PR!

2020-11-11 22:23 UTC, merged