chore(functions/log_helloworld): mention var_dump
GoogleCloudPlatform/php-docs-samples pull request #1218
Opened 2020-11-09 07:28 UTC by ace-n

Ran into this while debugging; figured it was worth documenting.

2020-11-09 18:03 UTC, bshaffer commented on functions/log_helloworld/index.php
> +    // These doesn't log anything
should be "these don't log anything"

2020-11-09 20:22 UTC, ace-n commented on functions/log_helloworld/index.php
> +    // These doesn't log anything
Done.

2020-11-09 20:33 UTC, bshaffer commented
This has to do with @grayside and my changes to google/cloud-tools , but kokoro has the following error:

```
InvalidArgumentException: Missing required property: entryPoint in /tmpfs/src/github/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/GcloudWrapper/CloudFunction.php:83
Stack trace:
#0 /tmpfs/src/github/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/GcloudWrapper/CloudFunction.php(111): Google\Cloud\TestUtils\GcloudWrapper\CloudFunction->__construct('php-docs-sample...', '', '', '', '')
#1 /tmpfs/src/github/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/CloudFunctionLocalTestTrait.php(58): Google\Cloud\TestUtils\GcloudWrapper\CloudFunction::fromArray(Array)
#2 /tmpfs/src/github/php-docs-samples/testing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(703): Google\Cloud\Samples\Functions\HelloLogging\Test\SystemTest::startFunction()
#3 /tmpfs/src/github/php-docs-samples/testing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(746): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#4 /tmpfs/src/github/php-docs-samples/testing/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(652): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#5 /tmpfs/src/github/php-docs-samples/testing/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#6 /tmpfs/src/github/php-docs-samples/testing/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run(Array, true)
#7 /tmpfs/src/github/php-docs-samples/testing/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
```

2020-11-09 20:45 UTC, ace-n commented
@bshaffer I suspect that's an issue with the tests (that should likely be remedied in a separate PR).

2020-11-09 21:13 UTC, grayside requested changes
could not reproduce this problem: I deploy a function, called it, and as expected the var_dump() output was returned in the HTTP response.

2020-11-10 04:02 UTC, ace-n commented
Ah - I didn't think to check there, my bad!

(I clarified the note a bit more, so @grayside PTAL.)

2020-11-10 18:53 UTC, grayside approved these changes
Filing a follow-up issue, as I think this is expanding the scope of the sample in a way that is both helpful but invites further details.

2020-11-10 18:56 UTC, grayside commented
#1219

2020-11-11 05:12 UTC, bshaffer approved these changes

2020-11-11 05:12 UTC, merged