chore(functions/log): add more logging methods
GoogleCloudPlatform/php-docs-samples pull request #1220
Opened 2020-11-11 05:35 UTC by ace-n

Fixes #1219

(I was going to do this in #1218, but @bshaffer ninja'd me. 🙂

2020-11-11 18:41 UTC, grayside approved these changes

2020-11-11 21:01 UTC, bshaffer requested changes

2020-11-11 21:01 UTC, bshaffer commented on functions/log_helloworld/index.php
> +    fwrite($log, $entry);  // Forward var_dump entry to fwrite.
This really doesn't seem necessary... why not just recommend `var_export`? I don't think we need to cover output buffering as a part of this example...

2020-11-11 22:24 UTC, grayside commented on functions/log_helloworld/index.php
> +    fwrite($log, $entry);  // Forward var_dump entry to fwrite.
I assumed Ace had a reason to emphasize this, I think showcasing `var_export()` (forgot about that one!) and my json_encode() snippet from the #1219 would be more valuable.

2020-11-11 23:12 UTC, bshaffer commented on functions/log_helloworld/index.php
> +    fwrite($log, $entry);  // Forward var_dump entry to fwrite.
I agree!

2020-11-11 23:17 UTC, ace-n commented on functions/log_helloworld/index.php
> +    fwrite($log, $entry);  // Forward var_dump entry to fwrite.
`var_export()`...hmm, TIL. 🤔

I'll use that instead.

2020-11-12 04:50 UTC, tmatsuo commented
@ace-n 
FYI, it seems like the snippet-bot is updating the comment which is deleted.

2020-11-12 19:01 UTC, bshaffer commented on functions/log_helloworld/index.php
> +    var_export('var_export output can be captured.', $entry);
This won't work as written here... it should be this

```php
$entry = var_export('var_export output can be captured.', true);
fwrite($log, $entry);
```

2020-11-12 19:05 UTC, ace-n commented on functions/log_helloworld/index.php
> +    var_export('var_export output can be captured.', $entry);
Done.

2020-11-12 22:15 UTC, bshaffer approved these changes

2020-11-12 22:15 UTC, merged