feat(functions): add Firestore sample
GoogleCloudPlatform/php-docs-samples pull request #1225
Opened 2020-11-15 13:12 UTC by ace-n

**N.B:** IMO this should have more than one test-case, but I couldn't figure out how to (easily) do that with the current log-based test architecture.

2020-11-17 18:42 UTC, grayside commented
What's the other test case you had in mind?

2020-11-17 20:50 UTC, ace-n commented
> What's the other test case you had in mind?

I was thinking of checking to make sure that:
* `oldValue` is correctly populated
* values are properly JSON-encoded

2020-11-20 22:09 UTC, grayside requested changes
Looks like the initial testing challenge is addressed. I have two further concerns but this seems close!

2020-11-20 22:09 UTC, grayside commented on functions/firebase_firestore/test/IntegrationTest.php
> +        }
I wonder if it would be worth creating a method in CloudFunctionsLocalTestTrait like:

```
private function request(CloudEvent $cloudevent, array $params = [])
{  
        // Prepare the HTTP headers for a CloudEvent.
        $cloudEventHeaders = [];
        foreach ($cloudevent as $key => $value) {
            $cloudEventHeaders['ce-' . $key] = $value;
        }

        return $this->client->request('POST', '/', array_merge_recursive($params, [
            'body' => json_encode($cloudevent->getBody()),
            'headers' => $cloudEventHeaders + [
                // Instruct the function framework to parse the body as JSON.
                'content-type' => 'application/json'
            ],
        ]));
}
```

2020-11-20 22:42 UTC, ace-n commented on functions/firebase_firestore/composer.json
> +            "FUNCTION_SIGNATURE_TYPE=cloudevent FUNCTION_TARGET=firebaseRTDB php -S localhost:${PORT:-8080} vendor/bin/router.php"
Good catch - I'm using `firebaseFirestore` for consistency with the RTDB sample (which is currently called `firebaseRTDB`).

2020-11-20 22:42 UTC, ace-n commented on functions/firebase_firestore/test/DeployTest.php
> +        self::$firestoreClient
Honestly, I have no idea. I was hoping to point this at a (separate) non-Datastore project, and test it against that.

2020-11-20 22:42 UTC, ace-n commented on functions/firebase_firestore/test/IntegrationTest.php
> +        }
cc @bshaffer

2020-12-08 23:10 UTC, ace-n commented
@grayside @bshaffer ready for re-review. We should figure out how we want to test this. (Any objection to a _separate GCP project_?)

2020-12-08 23:20 UTC, bshaffer commented
@ace-n we do have separate Firestore projects for testing!

2020-12-09 03:38 UTC, ace-n commented on functions/firebase_firestore/test/DeployTest.php
> +        self::$firestoreClient
Per @bshaffer's comments elsewhere on this PR - looks like we can use `FIRESTORE_PROJECT_ID` to get access to a dedicated Firestore project.

2020-12-09 16:39 UTC, bshaffer approved these changes

2020-12-09 16:39 UTC, bshaffer commented on functions/firebase_firestore/test/IntegrationTest.php
> +        }
Might even be worth adding something like that to the functions framework...

2020-12-09 16:56 UTC, bshaffer commented on functions/firebase_firestore/test/IntegrationTest.php
> +        }
https://github.com/GoogleCloudPlatform/php-tools/pull/96

2020-12-09 19:00 UTC, grayside approved these changes
Good work unearthing the `FIRESTORE_PROJECT_ID`, that seems like a really good solution to guaranteeing we get events for testing.

I left a nit and a couple points for consideration. I'm especially wondering if local testing will make sense to maintainers coming in without context.

2020-12-09 19:16 UTC, bshaffer commented on functions/firebase_firestore/test/DeployTest.php
> +            'projects/' . $project . '/databases/(default)/documents/' . self::$collectionName . '/' . self::$documentName;
Yes but I've taken care of them already

2020-12-09 19:20 UTC, bshaffer commented on functions/firebase_firestore/phpunit.xml.dist
> +            <directory>.</directory>
+1

2020-12-09 19:21 UTC, bshaffer commented on functions/firebase_firestore/test/DeployTest.php
> +        $project = self::requireEnv('FIRESTORE_PROJECT_ID');
We could use `requireOneOfEnv`:

```php
        self::$projectId = self::requireOneOfEnv([
            'FIRESTORE_PROJECT_ID',
            'GOOGLE_PROJECT_ID',
        ]);
```

2020-12-09 21:15 UTC, ace-n commented on functions/firebase_firestore/test/DeployTest.php
> +        $project = self::requireEnv('FIRESTORE_PROJECT_ID');
Done.

2020-12-09 21:37 UTC, ace-n commented
This should pass once [this `php-tools` PR](https://github.com/GoogleCloudPlatform/php-tools/pull/98) is merged.

2020-12-14 19:03 UTC, merged