docs: cleanup README for eventarc
GoogleCloudPlatform/php-docs-samples pull request #1227
Opened 2020-11-20 17:00 UTC by bshaffer

This replaces the manual steps to deploy to Cloud Run with the Cloud Run button

2020-11-20 17:33 UTC, grant reviewed
I don't think moving the Run button into the steps makes sense. The steps show how to deploy manually and the button does that for you, so they are exclusive. The button isn't the first step of running the sample on Cloud Run.

2020-11-20 17:36 UTC, bshaffer commented
@grant take a look now. It replaces the cloud build / manual deploy instructions. Having the button at the top without context doesn't serve a purpose. So this is a better flow all around.

2020-11-20 17:46 UTC, grant requested changes
Sorry, I believe the PR description and title are incorrect. This PR is not cleaning up the sample. It looks like it's forcing the use of the Cloud Run button rather than typical `gcloud` commands.

Using a UI / the Cloud Run button should not be a required step. That will make this sample not usable in a terminal environment for example. In most samples from what I know, we include `gcloud` steps for required actions via the terminal.

What's the goal of this change?

2020-11-20 17:47 UTC, grant commented
> @grant take a look now. It replaces the cloud build / manual deploy instructions. Having the button at the top without context doesn't serve a purpose. So this is a better flow all around.

Maybe simply remove the button?

2020-11-20 18:49 UTC, bshaffer commented
@grant Why would we remove the button? That's how they deploy to Cloud Run.

2020-11-20 19:07 UTC, bshaffer commented
Deploying using the cloud run button is more convenient than using gcloud commands. It's a better user experience.

We could include both, which complicates things a little bit, or just link to the docs on deploying with gcloud. I think for the purpose of the README, either would be sufficient.

2020-11-20 20:00 UTC, grant commented
Thanks for the PR again.

> @grant Why would we remove the button? That's how they deploy to Cloud Run. And it's easier than running the `gcloud` steps manually.

We could remove the button as the button doesn't make sense here and it does not function. Does the button function with this PR? Removing it might make sense if it doesn't function. Has the button been tested – and what is the result?

I disagree from a user experience POV that removing the `gcloud build` and `gcloud run deploy` commands provide a better UX. Why aren't we doing that in the Run sample? – that sample is simpler and I could imagine first changing that sample, then modifying this one.

2020-11-23 19:46 UTC, grant commented on eventarc/generic/README.md
> +[<img src="https://storage.googleapis.com/cloudrun/button.svg" alt="Run on Google Cloud" height="30"/>][run_button_generic]
This button doesn't deploy a Run service called `eventarc-generic-php`, so the rest of this README fails to work.

2021-02-08 21:06 UTC, closed without merging