feat: add public access prevention samples
GoogleCloudPlatform/php-docs-samples pull request #1229
Opened 2020-11-27 17:52 UTC by jdpedrie

Relies on https://github.com/googleapis/google-cloud-php/pull/3621 being merged and tagged.

cc @shaffeeullah

One of the tests is failing locally, I'll comment on it inline for reviewer thoughts.

2020-11-27 17:54 UTC, jdpedrie commented on storage/test/IamConfigurationTest.php
> +    public function testGetPublicAccessPrevention()
This test fails with the following error:

```
Undefined index: publicAccessPrevention

/path/to/php-docs-samples/storage/src/get_public_access_prevention.php:43
```

This is sort of strange, because `iamConfiguration.publicAccessPrevention` should be set to `unspecified`. Instead, it seems to be uninitialized.

2020-12-08 21:51 UTC, bshaffer commented
For the tests to pass I think we just need to add these methods in `composer.json` in the array under `autoload.files`

2020-12-08 21:51 UTC, bshaffer reviewed
For the tests to pass I think we just need to add these methods in `composer.json` in the array under `autoload.files`

2020-12-11 01:07 UTC, tritone reviewed
Generally looks good! A couple little comments.

2020-12-11 01:07 UTC, tritone commented on storage/src/set_public_access_prevention_enforced.php
> + * Get the Public Access Prevention setting for a bucket
Should be sets to "enforced" for this one.

2020-12-11 01:07 UTC, tritone commented on storage/src/set_public_access_prevention_unspecified.php
> + * Get the Public Access Prevention setting for a bucket
This comment also needs to be updated to correspond to the correct sample.

2020-12-11 01:07 UTC, tritone commented on storage/storage.php
> +The <info>%command.name%</info> command enables or disables public access prevention for a bucket.
I would stick to "enforced" and "unspecified" vs. enabled/disabled. Though perhaps it doesn't matter since this is just for testing, it looks like?

2020-12-11 01:07 UTC, tritone commented on storage/test/IamConfigurationTest.php
> +    public function testGetPublicAccessPrevention()
This is surprising. If you run the test now, do you still get the same error?

2020-12-11 19:02 UTC, jdpedrie commented on storage/test/IamConfigurationTest.php
> +    public function testGetPublicAccessPrevention()
I do. @bshaffer was correct that I had the autoload incorrect, but even after fixing that the problem seems to persist.

2020-12-11 19:03 UTC, jdpedrie commented
Thanks for the review @bshaffer @tritone. Still seeing the test issue, but other comments should be resolved.

2020-12-11 23:27 UTC, tritone commented on storage/test/IamConfigurationTest.php
> +    public function testGetPublicAccessPrevention()
@jdpedrie Does your library integration test show the field being present by default? And are you using the same project for both tests?

2020-12-14 19:14 UTC, bshaffer commented
@jdpedrie I am confused as when I run the samples and the tests I get the same error... the index doesn't exist. So this isn't a testing issue, this is a samples issue.  When I var_dump the variable `$iamConfiguration` I get the following:

```php
array(2) {
  ["bucketPolicyOnly"]=>
  array(2) {
    ["enabled"]=>
    bool(true)
    ["lockedTime"]=>
    string(24) "2020-05-28T18:52:22.505Z"
  }
  ["uniformBucketLevelAccess"]=>
  array(2) {
    ["enabled"]=>
    bool(true)
    ["lockedTime"]=>
    string(24) "2020-05-28T18:52:22.505Z"
  }
}
```

This happens both before and after I've enabled public access prevention via the samples. So I think one of two things may be happening here:

1. The `iamConfiguration` is not populating `publicAccessPrevention` as expected
2. `publicAccessPrevention` is only populated when it's enabled, and the `enable` sample is not working.

2020-12-15 19:34 UTC, shaffeeullah commented
> @jdpedrie I am confused as when I run the samples and the tests I get the same error... the index doesn't exist. So this isn't a testing issue, this is a samples issue. When I var_dump the variable `$iamConfiguration` I get the following:
> 
> ```
> array(2) {
>   ["bucketPolicyOnly"]=>
>   array(2) {
>     ["enabled"]=>
>     bool(true)
>     ["lockedTime"]=>
>     string(24) "2020-05-28T18:52:22.505Z"
>   }
>   ["uniformBucketLevelAccess"]=>
>   array(2) {
>     ["enabled"]=>
>     bool(true)
>     ["lockedTime"]=>
>     string(24) "2020-05-28T18:52:22.505Z"
>   }
> }
> ```
> 
> This happens both before and after I've enabled public access prevention via the samples. So I think one of two things may be happening here:
> 
> 1. The `iamConfiguration` is not populating `publicAccessPrevention` as expected
> 2. `publicAccessPrevention` is only populated when it's enabled, and the `enable` sample is not working.

re your second point: I've found `publicAccessPrevention` to be populated always, `unspecified` by default and `enforced` otherwise. This bug seems to be indicative of a bug in the library implementation.

2021-01-12 22:04 UTC, shaffeeullah commented on storage/test/IamConfigurationTest.php
> +    public function testGetPublicAccessPrevention()
@jdpedrie , is this test still failing?

2021-02-07 15:37 UTC, jdpedrie commented
@shaffeeullah I apologize for the long delay. I did more testing and found that the storage API does indeed omit the `publicAccessPrevention` key in certain cases. Below is a screenshot of the API response for the get-bucket call in the test which was failing.

I worked around it by checking that the value exists in the test.

![Screen Shot 2021-02-07 at 10 34 39 AM](https://user-images.githubusercontent.com/89034/107151420-807db200-6930-11eb-83b3-15eb6b4c6936.png)

2021-02-07 16:11 UTC, jdpedrie commented
I'm still trying to figure out why the value isn't returned after being set explicitly to `unspecified`. I can't replicate that outside the sample.

However, the initial value of `publicAccessPrevention` is not `unspecified`. It is not returned until it has been modified.

Here's the response from getBucket immediately after creating a bucket:

```json
{
    "kind": "storage#bucket",
    "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket",
    "id": "my-bucket",
    "name": "my-bucket",
    "projectNumber": "1234",
    "metageneration": "1",
    "location": "US",
    "storageClass": "STANDARD",
    "etag": "CAE=",
    "timeCreated": "2021-02-07T16:07:57.546Z",
    "updated": "2021-02-07T16:07:57.546Z",
    "iamConfiguration": {
        "bucketPolicyOnly": {
            "enabled": false
        },
        "uniformBucketLevelAccess": {
            "enabled": false
        }
    },
    "locationType": "multi-region"
}
```

And here's the response from getBucket after the value has been explicitly set to `unspecified`. Note this is separate testing, not via the samples:

```json
{
    "kind": "storage#bucket",
    "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket",
    "id": "my-bucket",
    "name": "my-bucket",
    "projectNumber": "1234",
    "metageneration": "3",
    "location": "US",
    "storageClass": "STANDARD",
    "etag": "CAM=",
    "timeCreated": "2021-02-07T16:07:57.546Z",
    "updated": "2021-02-07T16:07:57.995Z",
    "acl": [
        {
            "kind": "storage#bucketAccessControl",
            "id": "my-bucket/project-owners-1234",
            "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/acl/project-owners-1234",
            "bucket": "my-bucket",
            "entity": "project-owners-1234",
            "role": "OWNER",
            "etag": "CAM=",
            "projectTeam": {
                "projectNumber": "1234",
                "team": "owners"
            }
        },
        {
            "kind": "storage#bucketAccessControl",
            "id": "my-bucket/project-editors-1234",
            "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/acl/project-editors-1234",
            "bucket": "my-bucket",
            "entity": "project-editors-1234",
            "role": "OWNER",
            "etag": "CAM=",
            "projectTeam": {
                "projectNumber": "1234",
                "team": "editors"
            }
        },
        {
            "kind": "storage#bucketAccessControl",
            "id": "my-bucket/project-viewers-1234",
            "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/acl/project-viewers-1234",
            "bucket": "my-bucket",
            "entity": "project-viewers-1234",
            "role": "READER",
            "etag": "CAM=",
            "projectTeam": {
                "projectNumber": "1234",
                "team": "viewers"
            }
        }
    ],
    "defaultObjectAcl": [
        {
            "kind": "storage#objectAccessControl",
            "entity": "project-owners-1234",
            "role": "OWNER",
            "etag": "CAM=",
            "projectTeam": {
                "projectNumber": "1234",
                "team": "owners"
            }
        },
        {
            "kind": "storage#objectAccessControl",
            "entity": "project-editors-1234",
            "role": "OWNER",
            "etag": "CAM=",
            "projectTeam": {
                "projectNumber": "1234",
                "team": "editors"
            }
        },
        {
            "kind": "storage#objectAccessControl",
            "entity": "project-viewers-1234",
            "role": "READER",
            "etag": "CAM=",
            "projectTeam": {
                "projectNumber": "1234",
                "team": "viewers"
            }
        }
    ],
    "owner": {
        "entity": "project-owners-1234"
    },
    "iamConfiguration": {
        "bucketPolicyOnly": {
            "enabled": false
        },
        "uniformBucketLevelAccess": {
            "enabled": false
        },
        "publicAccessPrevention": "unspecified"
    },
    "locationType": "multi-region"
}
```

2021-02-08 16:44 UTC, tritone commented
> @shaffeeullah I'm sorry for the delay. I'm still trying to figure out why the value isn't returned after being set explicitly to `unspecified`. I can't replicate that outside the sample.
> 
> However, the initial value of `publicAccessPrevention` is not `unspecified`. It is not returned until it has been modified.
> 
> Here's the response from getBucket immediately after creating a bucket. This is the raw HTTP response body (formatted and with identifying information removed), not something that the client has modified in any manner. I've tested with multiple projects, though they likely all have similar whitelists applied. @bshaffer can put us in touch offline to share project IDs if you'd like to investigate possible issues with the projects.
> 
> ```json
> {
>     "kind": "storage#bucket",
>     "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket",
>     "id": "my-bucket",
>     "name": "my-bucket",
>     "projectNumber": "1234",
>     "metageneration": "1",
>     "location": "US",
>     "storageClass": "STANDARD",
>     "etag": "CAE=",
>     "timeCreated": "2021-02-07T16:07:57.546Z",
>     "updated": "2021-02-07T16:07:57.546Z",
>     "iamConfiguration": {
>         "bucketPolicyOnly": {
>             "enabled": false
>         },
>         "uniformBucketLevelAccess": {
>             "enabled": false
>         }
>     },
>     "locationType": "multi-region"
> }
> ```
> 
> And here's the response from getBucket after the value has been explicitly set to `unspecified`. Note this is separate testing, not via the samples:
> 
> ```json
> {
>     "kind": "storage#bucket",
>     "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket",
>     "id": "my-bucket",
>     "name": "my-bucket",
>     "projectNumber": "1234",
>     "metageneration": "3",
>     "location": "US",
>     "storageClass": "STANDARD",
>     "etag": "CAM=",
>     "timeCreated": "2021-02-07T16:07:57.546Z",
>     "updated": "2021-02-07T16:07:57.995Z",
>     "acl": [
>         {
>             "kind": "storage#bucketAccessControl",
>             "id": "my-bucket/project-owners-1234",
>             "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/acl/project-owners-1234",
>             "bucket": "my-bucket",
>             "entity": "project-owners-1234",
>             "role": "OWNER",
>             "etag": "CAM=",
>             "projectTeam": {
>                 "projectNumber": "1234",
>                 "team": "owners"
>             }
>         },
>         {
>             "kind": "storage#bucketAccessControl",
>             "id": "my-bucket/project-editors-1234",
>             "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/acl/project-editors-1234",
>             "bucket": "my-bucket",
>             "entity": "project-editors-1234",
>             "role": "OWNER",
>             "etag": "CAM=",
>             "projectTeam": {
>                 "projectNumber": "1234",
>                 "team": "editors"
>             }
>         },
>         {
>             "kind": "storage#bucketAccessControl",
>             "id": "my-bucket/project-viewers-1234",
>             "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/acl/project-viewers-1234",
>             "bucket": "my-bucket",
>             "entity": "project-viewers-1234",
>             "role": "READER",
>             "etag": "CAM=",
>             "projectTeam": {
>                 "projectNumber": "1234",
>                 "team": "viewers"
>             }
>         }
>     ],
>     "defaultObjectAcl": [
>         {
>             "kind": "storage#objectAccessControl",
>             "entity": "project-owners-1234",
>             "role": "OWNER",
>             "etag": "CAM=",
>             "projectTeam": {
>                 "projectNumber": "1234",
>                 "team": "owners"
>             }
>         },
>         {
>             "kind": "storage#objectAccessControl",
>             "entity": "project-editors-1234",
>             "role": "OWNER",
>             "etag": "CAM=",
>             "projectTeam": {
>                 "projectNumber": "1234",
>                 "team": "editors"
>             }
>         },
>         {
>             "kind": "storage#objectAccessControl",
>             "entity": "project-viewers-1234",
>             "role": "READER",
>             "etag": "CAM=",
>             "projectTeam": {
>                 "projectNumber": "1234",
>                 "team": "viewers"
>             }
>         }
>     ],
>     "owner": {
>         "entity": "project-owners-1234"
>     },
>     "iamConfiguration": {
>         "bucketPolicyOnly": {
>             "enabled": false
>         },
>         "uniformBucketLevelAccess": {
>             "enabled": false
>         },
>         "publicAccessPrevention": "unspecified"
>     },
>     "locationType": "multi-region"
> }
> ```

@jdpedrie , thanks for the detailed report here. This is a known bug and we have a fix that should be rolled out within the next week or two. We'll let you know when the fix is rolled out; could you confirm it's looking correct after that?

2021-02-08 16:54 UTC, jdpedrie commented
@tritone perfect, thanks! Yes, just drop me a note and I'll confirm.

2021-03-03 22:34 UTC, dwsupplee approved these changes
LGTM, but still pending the dependent PR being merged.

2021-03-08 19:15 UTC, frankyn commented
@jdpedrie the backend bug should now be addressed, could you try again?

2021-03-10 17:29 UTC, jdpedrie commented on storage/src/get_public_access_prevention.php
> + * Copyright 2020 Google LLC
done!

2021-04-20 21:12 UTC, bshaffer approved these changes

2021-04-21 12:55 UTC, jdpedrie commented
@shaffeeullah @tritone looks like tests are passing now! (the failure is from March -- the test matrix changed since then).

2021-06-11 20:02 UTC, shaffeeullah commented
Public access prevention rollout has been delayed due to a bug surfaced during Googler preview. I will keep this PR updated as I learn new release timeline details.

2021-06-28 18:10 UTC, shaffeeullah commented
@jdpedrie These samples can now be merged and released.

2021-06-28 18:40 UTC, bshaffer requested changes

2021-06-28 18:40 UTC, bshaffer commented on storage/storage.php
> +    });
@jdpedrie should we go ahead and upgrade these Storage samples to the new format? I set a precedent already by updating some of the other Storage samples, and I believe you have the remainder in progress.

2021-06-29 21:18 UTC, shaffeeullah commented on storage/storage.php
> +    });
@jdpedrie Would you be able to update this and merge this week?

2021-06-29 22:45 UTC, tritone approved these changes
Tests seem to pass now-- we can move forward with merging this ASAP (as long as @bshaffer is satisfied).

2021-06-30 12:42 UTC, jdpedrie commented
@bshaffer these are updated

2021-06-30 13:36 UTC, bshaffer approved these changes

2021-06-30 13:36 UTC, merged