feat: add dead letter queue samples
GoogleCloudPlatform/php-docs-samples pull request #1230
Opened 2020-11-27 19:26 UTC by jdpedrie

closes #1178.

2020-11-28 19:10 UTC, anguillanneuf commented on pubsub/api/src/dead_letter_update_subscription.php
> +# [START pubsub_dead_letter_remove]
This should be `pubsub_dead_letter_update_subscription`.

2020-11-28 19:11 UTC, anguillanneuf commented on pubsub/api/src/dead_letter_update_subscription.php
> +# [END pubsub_dead_letter_remove]
Ditto.

2020-12-03 18:39 UTC, jdpedrie commented
Thanks @anguillanneuf. This is fixed!

2020-12-03 18:47 UTC, anguillanneuf approved these changes

2020-12-07 17:59 UTC, bshaffer approved these changes

2020-12-07 19:32 UTC, bshaffer requested changes

2020-12-07 19:32 UTC, bshaffer commented on pubsub/api/pubsub.php
> +    EOF
Getting a kokoro syntax error for PHP 7.2 on this line. This needs to be flush with no indentation
```suggestion
EOF
```

2020-12-07 19:32 UTC, bshaffer commented on pubsub/api/test/DeadLetterPolicyTest.php
> +         self::$deadLetterTopic2->delete();
Looks like these four lines contain an extra space in their indentation:
```
   1) pubsub/api/test/DeadLetterPolicyTest.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
     {
-         self::$topic->delete();
-         self::$subscription->delete();
-         self::$deadLetterTopic->delete();
-         self::$deadLetterTopic2->delete();
+        self::$topic->delete();
+        self::$subscription->delete();
+        self::$deadLetterTopic->delete();
+        self::$deadLetterTopic2->delete();
     }
```

2020-12-07 20:24 UTC, bshaffer approved these changes

2020-12-07 20:32 UTC, merged