chore: added a profanity filter sample
GoogleCloudPlatform/php-docs-samples pull request #1236
Opened 2020-12-02 18:45 UTC by b-loved-dreamer

New sample that shows the use of profanity filtering

2020-12-02 19:41 UTC, bshaffer requested changes

2020-12-02 19:41 UTC, bshaffer commented on speech/src/profanity_filter_gcs.php
> +    ->setProfanityFilter(TRUE);
`true` needs to be lowercase

2020-12-02 19:41 UTC, bshaffer commented on speech/src/profanity_filter.php
> +    ->setProfanityFilter(TRUE);
`true` needs to be lowercase

2020-12-02 19:41 UTC, bshaffer commented on speech/test/speechTest.php
> +    // use TestTrait;
This should not be commented out

2020-12-02 19:41 UTC, bshaffer commented on speech/src/profanity_filter_gcs.php
> +
nit: remove unnecessary newline

2020-12-02 19:41 UTC, bshaffer commented on speech/src/profanity_filter.php
> +
nit: remove unnecessary newline

2020-12-02 19:41 UTC, bshaffer commented on speech/src/profanity_filter.php
> +$uri = 'gs://cloud-samples-tests/speech/brooklyn.flac';
This should be using a local file rather than a file from gcs.

2020-12-02 19:41 UTC, bshaffer commented on speech/test/speechTest.php
> +            ['profanity_filter', 'gs://' . self::$bucketName . '/speech/audio32KHz.raw'],
There should also be a `profanity_filter_gcs` to test both samples.

Also, you're passing an argument here but your sample does not allow for an argument. See one of the other speech samples for an example. At the top of the samples, it looks like this:

```php
if (count($argv) != 2) {
    return print("Usage: php base64_encode_audio.php AUDIO_FILE\n");
}
list($_, $audioFile) = $argv;

# [START base64_audio]
/** Uncomment and populate these variables in your code */
// $audioFile = 'path to an audio file';

//...
```

2020-12-07 23:03 UTC, bshaffer requested changes
Again, you need to uncomment `use TestTrait;`. The tests are failing because `runSnippet` is undefined.

2020-12-08 00:39 UTC, bshaffer requested changes

2020-12-08 00:39 UTC, bshaffer commented on speech/test/speechTest.php
> +            ['profanity_filter', __DIR__ . '/data/audio32KHz.raw'],
These tests are failing... possibly because there is no profanity in it, but I'm not sure. Is there a way we can test the profanity filter samples are working?

2020-12-08 00:39 UTC, bshaffer commented on speech/test/speechTest.php
> +        if (!self::$bucketName && in_array($command, ['transcribe_gcs', 'transcribe_async_gcs', 'profanity_filter_gcs', 'profanity_filter'])) {
You can remove `profanity_filter` from this line... this line is only for samples using cloud storage (e.g. ending in `_gcs`)

2020-12-08 01:58 UTC, b-loved-dreamer commented on speech/test/speechTest.php
> +            ['profanity_filter', __DIR__ . '/data/audio32KHz.raw'],
I wouldn't know what would be acceptable for a file containing profanity. I will ask.

2020-12-08 01:59 UTC, bshaffer commented on speech/test/speechTest.php
> +            ['profanity_filter', __DIR__ . '/data/audio32KHz.raw'],
Me neither, but we should find a way to test this! And for some reason the tests you added are failing...

2020-12-08 02:17 UTC, b-loved-dreamer commented on speech/test/speechTest.php
> +            ['profanity_filter', __DIR__ . '/data/audio32KHz.raw'],
Thank you. I will look into this more closely.

2020-12-08 20:54 UTC, bshaffer commented
The behavior I'm seeing is that this works for FLAC but not for RAW.

2020-12-08 21:30 UTC, bshaffer approved these changes

2020-12-08 21:30 UTC, merged

2020-12-08 21:48 UTC, tmatsuo commented
FYI, python uses product prefixes like `speech_recognize_with_profanity_filter_gcs`

https://github.com/googleapis/python-speech/pull/93