docs: Wrap samples with future prefix
GoogleCloudPlatform/php-docs-samples pull request #1239
Opened 2020-12-11 20:25 UTC by Strykrol

Standardizing Security Command Center samples to use 'securitycenter' prefixing. 

- Wrapped existing samples to keep published doclinks unbroken
- Replace region tags that aren't published. 

Once this PR is through, published sample inclusions will be updated to use the new prefix, then I'll come through again and remove the unused block wraps.

2021-01-11 20:35 UTC, bshaffer approved these changes

2021-01-11 20:35 UTC, bshaffer commented on securitycenter/src/receive_notification.php
> +// [START securitycenter_receive_notifications]
Curious why this one was removed while the others were wrapped, but otherwise LGTM

2021-01-11 21:59 UTC, Strykrol commented on securitycenter/src/receive_notification.php
> +// [START securitycenter_receive_notifications]
This PHP sample is not published live in any docs, so fully changing this should be no-harm-no-foul.

2021-01-12 01:09 UTC, bshaffer commented on securitycenter/src/list_notification.php
> +// [START securitycenter_list_notification_configs]
The tests are failing because there's trailing whitespace at the end of this line

2021-01-13 19:34 UTC, Strykrol commented on securitycenter/src/list_notification.php
> +// [START securitycenter_list_notification_configs]
Done, thank you!

2021-01-15 22:33 UTC, tmatsuo requested changes

2021-01-15 22:33 UTC, tmatsuo commented on securitycenter/src/create_notification.php
> +// [START securitycenter_ create_notification_config]
`[START securitycenter_ create_notification_config]`

There is a unnecessary space in the region tag part. Please fix.

2021-01-15 22:33 UTC, tmatsuo commented on securitycenter/src/create_notification.php
> +// [END securitycenter_ create_notification_config]
ditto

2021-01-16 00:02 UTC, Strykrol commented on securitycenter/src/create_notification.php
> +// [END securitycenter_ create_notification_config]
Thank you!

2021-01-16 00:02 UTC, Strykrol commented on securitycenter/src/create_notification.php
> +// [START securitycenter_ create_notification_config]
Good catch, thanks.

2021-02-02 20:27 UTC, tmatsuo approved these changes

2021-02-03 01:45 UTC, merged