chore(functions): add Firebase remote config sample
GoogleCloudPlatform/php-docs-samples pull request #1241
Opened 2020-12-15 04:54 UTC by ace-n

2020-12-15 22:03 UTC, ace-n commented
TODO: use stream wrappers.

2021-01-06 00:21 UTC, grayside requested changes
A quick pass. Overall looks good but a couple tweaks needed.

2021-01-06 00:21 UTC, grayside commented on functions/firebase_remote_config/composer.json
> +            "FUNCTION_SIGNATURE_TYPE=cloudevent FUNCTION_TARGET=firebaseFirestore php -S localhost:${PORT:-8080} vendor/bin/router.php"
FUNCTION_TARGET needs to match current function name.

2021-01-06 00:21 UTC, grayside commented on functions/firebase_remote_config/index.php
> +}
Future consideration: This sample seems to output specific fields from this event. It seems like it may be changed with one of the following:

1. Replace with event documentation & generic sample to log top-level fields from an event.
2. Generate based on an event schema.

2021-01-06 00:21 UTC, grayside commented on functions/firebase_remote_config/phpunit.xml.dist
> +            <exclude>vendor</exclude>
`vendor` is not needed as an exclusion from the test directory.

2021-01-06 00:21 UTC, grayside commented on functions/firebase_remote_config/composer.json
> +        "kreait/firebase-php": "^5.14"
Starting out-of-band discussion on this. Seems odd to use an unofficial Firebase library in these samples.

2021-01-06 00:23 UTC, ace-n commented on functions/firebase_remote_config/composer.json
> +        "kreait/firebase-php": "^5.14"
cc @samtstern - is this the recommended library for interacting with Firebase?

2021-01-06 11:00 UTC, samtstern commented on functions/firebase_remote_config/composer.json
> +        "kreait/firebase-php": "^5.14"
It's the highest-quality third party Firebase SDK that I know of but not something we officially support or recommend in any of our samples.

I would not recommend using it in an official Cloud sample.

2021-01-06 18:43 UTC, ace-n commented on functions/firebase_remote_config/composer.json
> +        "kreait/firebase-php": "^5.14"
Got it. What would the best alternative be? (Ideally something other than raw API requests!)

2021-01-06 19:19 UTC, samtstern commented
Unfortunately raw HTTP requests is my answer here.  The only product we
have a PHP SDK for is Firestore.

On Wed, Jan 6, 2021 at 6:43 PM Ace Nassri <notifications@github.com> wrote:

> *@ace-n* commented on this pull request.
> ------------------------------
>
> In functions/firebase_remote_config/composer.json
> <https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1241#discussion_r552896410>
> :
>
> > @@ -0,0 +1,16 @@
> +{
> +    "require": {
> +        "google/cloud-functions-framework": "^0.7.1",
> +        "google/cloud-firestore": "^1.18",
> +        "kreait/firebase-php": "^5.14"
>
> Got it. What would the best alternative be? (Ideally something other than
> raw API requests!)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1241#discussion_r552896410>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACATB2QJUBJ5VJEF6F5NTWLSYSVNXANCNFSM4U3YEAIQ>
> .
>

2021-01-06 20:01 UTC, ace-n commented on functions/firebase_remote_config/composer.json
> +        "kreait/firebase-php": "^5.14"
From @bshaffer - we can use the code below to do auth'd API requests:
```php
use Google\Auth\ApplicationDefaultCredentials;
use Google\Auth\CredentialsLoader;

$credentials = ApplicationDefaultCredentials::getCredentials();
$client = ClientLoader::makeHttpClient($credentials, [
    'base_url' => 'https://www.googleapis.com/taskqueue/v1beta2/projects/'
]);
$response = $client->get('myproject/taskqueues/myqueue');
```

2021-01-08 00:10 UTC, ace-n commented on functions/firebase_remote_config/composer.json
> +            "FUNCTION_SIGNATURE_TYPE=cloudevent FUNCTION_TARGET=firebaseFirestore php -S localhost:${PORT:-8080} vendor/bin/router.php"
Done.

2021-01-08 00:11 UTC, ace-n commented on functions/firebase_remote_config/phpunit.xml.dist
> +            <exclude>vendor</exclude>
Done.

2021-01-08 00:11 UTC, ace-n commented on functions/firebase_remote_config/composer.json
> +        "kreait/firebase-php": "^5.14"
This has been addressed. (We removed this library in favor of raw HTTP requests, as discussed above.)

2021-01-08 02:44 UTC, ace-n commented on functions/firebase_remote_config/index.php
> +}
I wouldn't be opposed to a generation system. (Maybe ping @busunkim96 or @JustinBeckwith internally, as they might have more context.)

2021-01-11 17:35 UTC, grayside commented on functions/firebase_remote_config/test/IntegrationTest.php
> +            if (is_string($value)) {
Should there be a failing assertion if the value is not a string?

2021-01-11 22:43 UTC, ace-n commented on functions/firebase_remote_config/test/IntegrationTest.php
> +            if (is_string($value)) {
In that case, `value` should `=== 2`. Added an assertion accordingly.

2021-01-11 23:56 UTC, grayside approved these changes

2021-01-12 00:45 UTC, bshaffer requested changes
I might be missing something, but I don't see anything firebase in this sample - it looks like it just prints the cloud event data. Is that intentional?

2021-01-12 00:45 UTC, bshaffer commented on functions/tips_phpinfo/.gcloudignore
> +vendor/
I think this file can be deleted?

2021-01-12 00:45 UTC, bshaffer commented on functions/firebase_remote_config/composer.json
> +        "google/auth": "^1.14"
I believe this can be moved to `require-dev`, as it's only a dependency used in tests AFAICT

2021-01-12 00:45 UTC, bshaffer commented on functions/firebase_remote_config/composer.json
> +        "google/cloud-firestore": "^1.18",
I don't see this dep being used anywhere

2021-01-13 12:52 UTC, ace-n commented on functions/tips_phpinfo/.gcloudignore
> +vendor/
A stowaway! 🏴‍☠️ Removed.

2021-01-13 12:53 UTC, ace-n commented on functions/firebase_remote_config/composer.json
> +        "google/cloud-firestore": "^1.18",
Removed.

2021-01-13 12:54 UTC, ace-n commented on functions/firebase_remote_config/composer.json
> +        "google/auth": "^1.14"
Done.

2021-01-13 13:15 UTC, ace-n commented
@bshaffer yeah - the "Firebase" here comes from the events [being triggered by](https://cloud.google.com/functions/docs/calling/firebase-remote-config) Firebase Remote Config.

2021-01-13 21:07 UTC, bshaffer approved these changes

2021-01-13 21:07 UTC, merged