feat(functions): add ImageMagick samples
GoogleCloudPlatform/php-docs-samples pull request #1245
Opened 2020-12-16 01:52 UTC by ace-n

2020-12-16 23:02 UTC, grayside requested changes

2020-12-16 23:02 UTC, grayside commented on functions/imagemagick/test/IntegrationTest.php
> +        ]);
I believe a helper method has been merged into the trait for this.

2020-12-16 23:02 UTC, grayside commented on functions/imagemagick/test/DeployTest.php
> +        }
This will result in all the tests passing even if something goes wrong with the file.

Maybe the missing file case should be split off into a separate integration_cases()?

2020-12-16 23:03 UTC, grayside commented on functions/imagemagick/index.php
> +    $filePath = 'gs://' . $data['bucket'] . '/' . $data['name'];
I've elaborated on this below: we should directly use the `gs://` stream wrapper passed to ImageMagick() rather than copy the file around.

2020-12-17 00:20 UTC, ace-n commented on functions/imagemagick/README.md
> +# Google Cloud Functions ImageMagick sample
Done (though I copied this from the Node.js repo).

2020-12-17 00:23 UTC, ace-n commented on functions/imagemagick/index.php
> +
Done.

2020-12-17 00:25 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +    private static $FIXTURE_SOURCE_BUCKET = 'cloud-devrel-public';
Judging based on the name, it should be.

(That said, maybe we want to define this via an env var because hardcoding it feels...kludgey?)

2020-12-17 00:25 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +        $object = $fixtureBucket->object($fileName);
I'll let @bshaffer be the tie-breaking vote here.

2020-12-17 00:27 UTC, ace-n commented on functions/imagemagick/test/IntegrationTest.php
> +        ]);
I'm not sure which one...can you point me to an example?

2020-12-17 00:32 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +        }
Done. (Thankfully [PHPUnit supports multiple `dataProvider`s.](https://stackoverflow.com/a/39944633))

2020-12-17 01:49 UTC, ace-n commented on functions/imagemagick/index.php
> +define('VERY_LIKELY', 5);
Per @bshaffer's suggestion, I replaced this with a constant from the client library.

2020-12-17 01:49 UTC, ace-n commented on functions/imagemagick/phpunit.xml.dist
> +            <directory>.</directory>
Done.

2020-12-17 01:50 UTC, ace-n commented on functions/imagemagick/test/IntegrationTest.php
> +        ]);
If so - added.

2020-12-17 04:53 UTC, ace-n commented on functions/imagemagick/index.php
> +    Object $file,
Done.

2020-12-17 04:53 UTC, ace-n commented on functions/imagemagick/index.php
> +    $filePath = 'gs://' . $data['bucket'] . '/' . $data['name'];
Noted - done.

2020-12-17 04:55 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +    // The test copies images from here...
Reworded.

2021-01-08 02:59 UTC, ace-n commented
@tmatsuo can you create the `php-docs-samples` and `php-docs-samples-functions` within the testing project (presumably `php-docs-samples`)?

2021-01-11 05:59 UTC, bshaffer commented on functions/imagemagick/test/DeployTest.php
> +        $object = $fixtureBucket->object($fileName);
I'd prefer to keep trait-based approach for consistency, unless there's a reason not to!

2021-01-11 19:38 UTC, bshaffer requested changes

2021-01-11 19:38 UTC, bshaffer commented on .kokoro/docker/php74/Dockerfile
> +RUN composer global require phpunit/phpunit:^8.0
Let's not increment phpunit in this PR... let's stick to just adding imagemagick

2021-01-11 19:38 UTC, bshaffer commented on .kokoro/docker/php74/Dockerfile
> +ENV PATH=${PATH}:/usr/local/bin:${PHP_DIR}/bin:~/.config/composer/vendor
We shouldn't need to add this line

2021-01-11 19:38 UTC, bshaffer commented on .kokoro/docker/php73/Dockerfile
> +RUN composer global require phpunit/phpunit:^8.0
Same here: revert this line

2021-01-11 19:38 UTC, bshaffer commented on .kokoro/docker/php73/Dockerfile
> +ENV PATH=${PATH}:/usr/local/bin:${PHP_DIR}/bin:~/.config/composer/vendor
Same here: revert this line

2021-01-12 17:35 UTC, grayside commented
Responding to the request for new storage buckets, I see gs://php-docs-samples-kokoro has product-specific test fixtures and several tests reference an environment variable `GOOGLE_STORAGE_BUCKET`. Is the php-docs-samples-functions bucket meant to be the target bucket for function output? I'm not sure if good bucket already exists for that, @bshaffer might.

2021-01-12 18:23 UTC, bshaffer requested changes

2021-01-12 18:23 UTC, bshaffer commented on .kokoro/secrets-example.sh
> +export FUNCTIONS_BUCKET=
The FOO env var here can be removed, and ideally the existing GOOGLE_STORAGE_BUCKET env car can be used as the buckets for these tests. I've used directories in the bucket to keep these separate.

2021-01-12 18:52 UTC, bshaffer commented on functions/imagemagick/test/TestCasesTrait.php
> +{
You could have this Trait use `TestTrait`, and that way we can use `requireEnv` instead of `getenv` below

2021-01-12 18:52 UTC, bshaffer commented on functions/imagemagick/test/TestCasesTrait.php
> +        $BLURRED_BUCKET_NAME = getenv('BLURRED_BUCKET_NAME');
I would prefer if we used `GOOGLE_CLOUD_BUCKET` here, and hardcoded a directory. e.g.:

```php
$startBucketName = self::requireEnv('GOOGLE_CLOUD_BUCKET') . '/functions/start';
$blurredBucketName = self::requireEnv('GOOGLE_CLOUD_BUCKET') . '/functions/blurred';
```

2021-01-12 18:52 UTC, bshaffer commented on functions/imagemagick/test/DeployTest.php
> +        }
Seems like we should be able to fetch these once in `TestCasesTrait` instead of 4 times across the individual tests

2021-01-13 11:07 UTC, ace-n commented on .kokoro/docker/php74/Dockerfile
> +RUN composer global require phpunit/phpunit:^8.0
Done - though I believe this was necessary for the image to build (at least on my machine).

(If you don't mind however, I'd prefer to let you fix any Docker build issues.)

2021-01-13 11:08 UTC, ace-n commented on .kokoro/docker/php74/Dockerfile
> +ENV PATH=${PATH}:/usr/local/bin:${PHP_DIR}/bin:~/.config/composer/vendor
Removed, but IME was necessary to find the PECL extension itself.

2021-01-13 11:08 UTC, ace-n commented on .kokoro/docker/php73/Dockerfile
> +RUN composer global require phpunit/phpunit:^8.0
Ditto.

2021-01-13 11:08 UTC, ace-n commented on .kokoro/docker/php73/Dockerfile
> +ENV PATH=${PATH}:/usr/local/bin:${PHP_DIR}/bin:~/.config/composer/vendor
Ditto.

2021-01-13 11:09 UTC, ace-n commented on .kokoro/secrets-example.sh
> +export FUNCTIONS_BUCKET=
I think FOO is for the [env vars sample](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/functions/env_vars/index.php#L24).

2021-01-13 11:14 UTC, ace-n commented on functions/imagemagick/test/TestCasesTrait.php
> +        $BLURRED_BUCKET_NAME = getenv('BLURRED_BUCKET_NAME');
Hmm - I like this idea, but this would cause inconsistency with the other languages' samples. (They are designed to be triggered on a _bucket_-wide basis, as GCF itself doesn't support _folder_-specific triggers AFAIK. So we'd have to have a check within the sample itself to see what folder was modified.)

@grayside perhaps it's worth updating those (and the docs) to follow this pattern too?

2021-01-13 12:23 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +        }
This is in the _deployment_ command - which I'm _assuming_ only runs once?

(That said - if it's cleaner to specify this in `TestCasesTrait`, I'm open to moving them.)

2021-01-14 17:41 UTC, grayside commented on functions/imagemagick/test/TestCasesTrait.php
> +        $BLURRED_BUCKET_NAME = getenv('BLURRED_BUCKET_NAME');
Since I instigated the change in the other samples, I'm against switching back to one bucket :)

The issue is if we write back to the originating bucket, it creates a second event. As a result, every file to process leads to two function invocations and requires extra logic in the function to identify which events need processing and which can be discarded. I'd prefer if we could add another bucket and a variable like `GOOGLE_CLOUD_BUCKET_OUTPUT`

2021-01-21 21:26 UTC, ace-n commented on functions/imagemagick/test/TestCasesTrait.php
> +{
(Already) done.

2021-01-22 20:38 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +        $object = $fixtureBucket->object($fileName);
@grayside I think [that's designed to upload a (text?) file directly to a bucket](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/functions/helloworld_storage/test/DeployTest.php#L152-L172), whereas this copies image files between buckets.

What we _could_ do is:
1) Store sample image locally (e.g. in a `resources` folder of some sort)
2) Retrieve it as a string (e.g. using `file_get_contents()`)
3) Upload that string to the target GCS bucket

Would that be a better approach?

2021-01-22 20:55 UTC, bshaffer reviewed
nits regarding variable names and types, otherwise LGTM

2021-01-22 20:55 UTC, bshaffer commented on functions/imagemagick/index.php
> +        $VERY_LIKELY = 5; // constant used by vision API
This variable is never used! Please remove it!

2021-01-22 20:55 UTC, bshaffer commented on functions/imagemagick/index.php
> +            $BLURRED_BUCKET_NAME = getenv('BLURRED_BUCKET_NAME');
This casing convention is reserved for constants. Please make this `$blurred_bucket_name`

2021-01-22 20:55 UTC, bshaffer commented on functions/imagemagick/test/DeployTest.php
> +    private static $BLURRED_BUCKET;
again this casing convention is reserved for constants. Please make them `$blurredBucket`, and `$monitoredBucket`

2021-01-22 20:55 UTC, bshaffer commented on functions/imagemagick/test/DeployTest.php
> +    private static $FIXTURE_SOURCE_BUCKET = 'cloud-devrel-public';
All of these strings can/should be private constants:

```php
    /** @var string */
    private const ENTRY_POINT = 'blurOffensiveImages';

    /** @var string */
    private const FUNCTION_SIGNATURE_TYPE = 'cloudevent';

    /** @var string */
    // The test starts by copying images from this bucket.
    private const FIXTURE_SOURCE_BUCKET = 'cloud-devrel-public';
```

2021-01-22 20:55 UTC, bshaffer commented on functions/imagemagick/test/TestCasesTrait.php
> +        $START_BUCKET_NAME = self::requireEnv('FUNCTIONS_BUCKET');
`$START_BUCKET_NAME` is not used in this function

2021-01-22 20:55 UTC, bshaffer commented on functions/imagemagick/test/TestCasesTrait.php
> +        $BLURRED_BUCKET_NAME = self::requireEnv('BLURRED_BUCKET_NAME');
please make this `$blurredbucketName`

2021-01-22 20:55 UTC, bshaffer commented on functions/imagemagick/test/TestCasesTrait.php
> +        $START_BUCKET_NAME = self::requireEnv('FUNCTIONS_BUCKET');
please make this `$startBucketName`

2021-01-22 21:00 UTC, bshaffer commented on functions/imagemagick/test/TestCasesTrait.php
> +        $START_BUCKET_NAME = self::requireEnv('FUNCTIONS_BUCKET');
Also, `$BLURRED_BUCKET_NAME` isn't used in this function

2021-01-22 22:45 UTC, ace-n commented on functions/imagemagick/index.php
> +            $BLURRED_BUCKET_NAME = getenv('BLURRED_BUCKET_NAME');
Changed to camelCase, since (AFAICT) that's more common in PHP.

2021-01-22 22:46 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +    private static $BLURRED_BUCKET;
Done.

2021-01-22 22:49 UTC, ace-n commented on functions/imagemagick/test/TestCasesTrait.php
> +        $START_BUCKET_NAME = self::requireEnv('FUNCTIONS_BUCKET');
Removed. (Replaced the other one with `bucketName` too, since it's not a constant.)

2021-01-22 22:49 UTC, ace-n commented on functions/imagemagick/test/TestCasesTrait.php
> +        $BLURRED_BUCKET_NAME = self::requireEnv('BLURRED_BUCKET_NAME');
Done, as `bucketName`.

2021-01-22 22:49 UTC, ace-n commented on functions/imagemagick/test/TestCasesTrait.php
> +        $START_BUCKET_NAME = self::requireEnv('FUNCTIONS_BUCKET');
Done, as `$bucketName`.

2021-01-22 22:50 UTC, ace-n commented on functions/imagemagick/index.php
> +        $VERY_LIKELY = 5; // constant used by vision API
Done.

2021-01-22 22:54 UTC, ace-n commented
FYI: `$entryPoint` and `$functionSignatureType` are required (in that casing, and as `private static` properties) by the testing framework. (Should we file an issue to change these to constants?)

```
/Users/anassri/Desktop/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/GcloudWrapper/CloudFunction.php:83
Stack trace:
#0 /Users/anassri/Desktop/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/GcloudWrapper/CloudFunction.php(111): Google\Cloud\TestUtils\GcloudWrapper\CloudFunction->__construct('nodejs-docs-sam...', '', 'cloudevent', '', '')
#1 /Users/anassri/Desktop/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/CloudFunctionDeploymentTrait.php(55): Google\Cloud\TestUtils\GcloudWrapper\CloudFunction::fromArray(Array)
#2 /Users/anassri/Desktop/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/CloudFunctionDeploymentTrait.php(81): Google\Cloud\Samples\Functions\ImageMagick\Test\DeployTest::setUpFunction()
#3 /Users/anassri/Desktop/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/DeploymentTrait.php(67): Google\Cloud\Samples\Functions\ImageMagick\Test\DeployTest::beforeDeploy()
#4 /Users/anassri/Desktop/php-docs-samples/testing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(703): Google\Cloud\Samples\Functions\ImageMagick\Test\DeployTest::deployApp()
#5 /Users/anassri/Desktop/php-docs-samples/testing/vendor/phpunit/phpunit/src/Framework/TestSuite.php(746): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 /Users/anassri/Desktop/php-docs-samples/testing/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(652): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /Users/anassri/Desktop/php-docs-samples/testing/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#8 /Users/anassri/Desktop/php-docs-samples/testing/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run(Array, true)
#9 /Users/anassri/Desktop/php-docs-samples/testing/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#10 {main}
```

2021-01-22 23:04 UTC, bshaffer commented
@ace-n oh!! My bad, I didn't know there was a functional purpose for setting those variables! Please leave them as-is then, my apologies!!

2021-01-22 23:05 UTC, bshaffer commented on functions/imagemagick/test/DeployTest.php
> +        }
As-is is fine. I experimented and it is indeed difficult to have them defined in one place.

2021-01-22 23:05 UTC, bshaffer commented on functions/imagemagick/index.php
> +            $BLURRED_BUCKET_NAME = getenv('BLURRED_BUCKET_NAME');
Works for me, I only suggested snake because of the casing of `$is_inappropriate`

2021-01-25 21:04 UTC, bshaffer approved these changes

2021-01-26 18:01 UTC, grayside commented on functions/imagemagick/test/DeployTest.php
> +        $object = $fixtureBucket->object($fileName);
Yes, I'd say we're talking about an image test fixture, the function as written accepts a parameter. As far as the stream wrapper is concerned if file_put_contents works nothing cares about type or file format. triggerStorageUpload() makes sense as a trait, just call with the output of file_get_contents().

You should be able to go a step further, and rely on file_put_contents() to do the read itself if you provide a stream as the $data, e.g., `$stream = fopen('resources/fixture.png', 'r')`

2021-01-26 18:18 UTC, grayside requested changes

2021-01-26 18:18 UTC, grayside commented on .kokoro/docker/php73/Dockerfile
> +            php-imagick \
Why install imagemagick for PHP 7.3?

2021-01-26 18:18 UTC, grayside commented on functions/imagemagick/php.ini
> +extension=imagick.so
nit: If this is going to be included in the docs, I think it's worth having a further clarifying comment is worthwhile:

```suggestion
# The imagick PHP extension is installed but disabled by default.
extension=imagick.so
```

Future: I would further suggest this comment **and the surrounding documentation** link to the eventual runtime documentation listing the available extensions.

2021-01-26 18:18 UTC, grayside commented on functions/imagemagick/test/DeployTest.php
> +    private const FIXTURE_SOURCE_BUCKET = 'cloud-devrel-public';
nit: active dependency of the tests on our internal infrastructure seems like it's worth avoiding.

2021-01-26 18:18 UTC, grayside commented on functions/imagemagick/test/DeployTest.php
> +        var_dump(self::FIXTURE_SOURCE_BUCKET);
nit: This var_dump() seems like a bit of debugging code? Not opposed to expanding to a more detailed log message.

2021-01-26 18:18 UTC, grayside commented on functions/imagemagick/index.php
> +    $filePath = 'gs://' . $data['bucket'] . '/' . $data['name'];
This sample is not using the stream wrapper. I think we should recommend the stream wrapper as the default way to interact with Cloud Storage objects.

1. It replicates the more familiar experience of working with files
2. It leads the code to be more generally portable, as all that's needed to switch the code to interact with a filesystem or another external storage is registering a different stream handler and swapping the protocol prefix
3. It leads to slightly more concise code

2021-01-26 19:33 UTC, bshaffer commented on functions/imagemagick/test/DeployTest.php
> +    private const FIXTURE_SOURCE_BUCKET = 'cloud-devrel-public';
Agreed - let's put whatever resources are used in `gs://php-docs-samples-kokoro/functions/*` instead

2021-01-26 19:33 UTC, bshaffer commented on functions/imagemagick/test/DeployTest.php
> +        var_dump(self::FIXTURE_SOURCE_BUCKET);
No, let's please remove it.

2021-01-26 19:37 UTC, bshaffer commented
@Adam Ross I do not agree we should use stream wrappers for tests
1. Using the client is less complicated and has fewer layers of abstraction
2. We don't recommend using the stream wrapper over the client library in the docs AFAIK
3. All the other tests in this repo use the storage client

2021-02-01 17:51 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +        var_dump(self::FIXTURE_SOURCE_BUCKET);
Done.

2021-02-01 17:52 UTC, ace-n commented on functions/imagemagick/test/DeployTest.php
> +    private const FIXTURE_SOURCE_BUCKET = 'cloud-devrel-public';
@grayside didn't you suggest using separate buckets for this? Or should we move to separate _files_?

(If we do the latter, we'll have to update docs + other samples for consistency.)

2021-02-01 17:54 UTC, ace-n commented
@bshaffer I'll wait to merge this until we have something both you and @grayside are happy with.

(That way, I can create a clean branch + copy-paste `functions/imagemagick` instead of dealing with merge conflict resolution.)

2021-02-01 22:15 UTC, ace-n commented on .kokoro/docker/php73/Dockerfile
> +            php-imagick \
We won't - this change will be removed in a future (force-)push.

2021-02-01 22:19 UTC, ace-n commented on functions/imagemagick/php.ini
> +extension=imagick.so
Added a link to this (which currently 404's):

https://cloud.google.com/functions/docs/concepts/php-runtime

2021-02-03 22:02 UTC, grayside approved these changes
This looks good, we can start here and if we find a path to agreeing on use of stream wrappers we can change it later.

2021-02-03 22:02 UTC, grayside commented on functions/imagemagick/README.md
> +**Note:** This example requires the `imagick` PECL package.
non-blocking idea: `composer check-platform-reqs` will verify this package is available because the extension is included in composer.json. Not required but nice to include if you do an update.

2021-02-03 22:14 UTC, ace-n commented on .kokoro/secrets-example.sh
> +export FUNCTIONS_BUCKET=
1) This is an _example_ secrets file that simply lists the variables that need to be specified. (The other lines in this file don't contain example values!)
2) In any case, I _think_ these changes will be dropped once I force-push a clean `main` pull to this branch.

2021-02-04 21:05 UTC, ace-n commented
Updated `secrets` files and force-pushed changes, as requested by @bshaffer.

@grayside over to you. 🛩️

2021-02-05 21:32 UTC, ace-n commented
Failures look unrelated ([only the PHP 8.0 build was failing](https://source.cloud.google.com/results/invocations/418498c2-6bf8-4670-977d-e235e627d365/log)).

@bshaffer can we merge this?

2021-02-05 22:37 UTC, merged