feat(functions): add retriable events sample
GoogleCloudPlatform/php-docs-samples pull request #1258
Opened 2021-01-16 02:33 UTC by ace-n

2021-01-19 18:59 UTC, grayside requested changes
Most of my comments are polish nits, with two blocking concerns on how we present the `retry` property and making sure the system test is sufficiently robust.

2021-01-19 18:59 UTC, grayside commented on functions/tips_retry/index.php
> +        return "";
nit: Are we unable to simply `return;`? The explicit string seems odd.

2021-01-19 18:59 UTC, grayside commented on functions/tips_retry/test/DeployTest.php
> +        return self::$fn->deploy(['--retry' => ''], '--trigger-topic=' . self::$topicName);
nit: What is this `--retry` flag controlling? Could you add a comment?

2021-01-19 18:59 UTC, grayside commented on functions/tips_retry/test/DeployTest.php
> +            'projectId' => self::$projectId,
nit: Is passing the project ID explicitly still required for Pub/Sub client?

2021-01-19 18:59 UTC, grayside commented on functions/tips_retry/test/DeployTest.php
> +            $retryCount = substr_count($actual, 'Retrying...');
This test cannot pass unless Pub/Sub tries, retries, and logs from both requests are processed by Cloud Logging. Is 5 seconds an adequate wait time?

2021-01-19 18:59 UTC, grayside commented on functions/tips_retry/test/IntegrationTest.php
> + * Integration Test for helloGCS.
nit: Not a helloGCS test

2021-01-19 18:59 UTC, grayside commented on functions/tips_retry/index.php
> +    $tryAgain = $data['retry'];
I think we need a comment here to clarify this "retry" property is an arbitrary value in the Pub/Sub message used to represent custom retry logic. I'd probably combine this with changing the property name to something like `yourCustomRetryPolicy`.

2021-01-19 18:59 UTC, grayside commented on functions/tips_retry/index.php
> +        // Retry execution
nit: expand this comment e.g., "Thrown exceptions or 5xx status codes result in a retry."

2021-01-20 12:20 UTC, ace-n commented on functions/tips_retry/index.php
> +        return "";
Nope - that causes a PHP error: `A function with return type must return a value`

2021-01-20 12:23 UTC, ace-n commented on functions/tips_retry/test/DeployTest.php
> +        return self::$fn->deploy(['--retry' => ''], '--trigger-topic=' . self::$topicName);
Done - added a comment.

2021-01-20 12:23 UTC, ace-n commented on functions/tips_retry/test/DeployTest.php
> +            $retryCount = substr_count($actual, 'Retrying...');
Akin to #1257, I increased this to 60 seconds.

2021-01-20 12:24 UTC, ace-n commented on functions/tips_retry/test/IntegrationTest.php
> + * Integration Test for helloGCS.
Good catch - fixed.

2021-01-20 12:37 UTC, ace-n commented on functions/tips_retry/index.php
> +        // Retry execution
Done.

2021-01-20 12:40 UTC, ace-n commented on functions/tips_retry/index.php
> +    $tryAgain = $data['retry'];
Changed to `some_parameter` + added comments about how this works to the sample itself.

2021-01-20 12:47 UTC, ace-n commented on functions/tips_retry/test/DeployTest.php
> +            'projectId' => self::$projectId,
Apparently not - removed.

2021-01-20 18:32 UTC, bshaffer approved these changes

2021-01-20 18:32 UTC, bshaffer commented on functions/tips_retry/test/DeployTest.php
> +    private function processFunctionLogs(CloudFunction $fn, string $startTime, callable $process)
Seems like we should put this in a `FunctionsTestTrait` in `google/cloud-tools` at some point

2021-01-20 18:38 UTC, ace-n commented on functions/tips_retry/test/DeployTest.php
> +    private function processFunctionLogs(CloudFunction $fn, string $startTime, callable $process)
See #1240

2021-01-26 18:29 UTC, grayside approved these changes
All feedback is minor, but there are two lower-priority conventions not included:

1. Start script in composer.json
2. Use of trait method to facilitate integration test

I'm going to approve because it's unclear if these should be blocking considerations, but we should consider that lack of consistency on these seems like tech debt to me.

2021-01-26 18:29 UTC, grayside commented on functions/tips_retry/composer.json
> +    "require-dev": {
Did we want to add the start script to this sample?

2021-01-26 18:29 UTC, grayside commented on functions/tips_retry/index.php
> +        throw new Exception('Retrying...');
nit: While "Retrying..." here is the result of sending the exception, all the function knows is:

1. Something went wrong
2. We want a retry to happen.

I'm unsure if the goal of this snippet should be hyper-focused on training retry expectations, or if we should also include the angle of making the retry semantics friendly to troubleshooting. The exception ideally includes context on why the retry is needed so Cloud Logging and Cloud Error Reporting can provide more details:

```suggestion
        throw new Exception('Try Again triggered, expecting retry...');
```

2021-01-26 18:29 UTC, grayside commented on functions/tips_retry/index.php
> +        fwrite($log, "Not retrying" . PHP_EOL);
nit: if this would be out of alignment with other languages, it's fine, but the function doesn't control the retry, it only controls whether or not it's asking the system to perform a retry.

```suggestion
        fwrite($log, "Not requesting retry" . PHP_EOL);
```

2021-01-26 18:29 UTC, grayside commented on functions/tips_retry/test/IntegrationTest.php
> +        // Prepare the HTTP headers for a CloudEvent.
Note we extracted this code to a method in the helper trait, so all these sections in the sample tests should be updated:

https://github.com/GoogleCloudPlatform/php-tools/blob/a3bd49833bb21a41e67f6decba654edff0508e4c/src/TestUtils/CloudFunctionLocalTestTrait.php#L121

New sample tests should use that trait function.

2021-01-27 20:31 UTC, ace-n commented on functions/tips_retry/index.php
> +        fwrite($log, "Not retrying" . PHP_EOL);
ACK - this is out of alignment, so I'll keep it as-is.

2021-01-27 21:19 UTC, ace-n commented on functions/tips_retry/test/IntegrationTest.php
> +        // Prepare the HTTP headers for a CloudEvent.
Done (for this sample).

Does this need to be refactored into existing samples? If so, mind filing an issue for that?

2021-01-27 21:24 UTC, ace-n commented
Added `start` script - @grayside can you review, and **merge this** if it looks good? Thanks!

2021-01-27 21:25 UTC, ace-n commented on functions/tips_retry/composer.json
> +    "require-dev": {
Done.

2021-01-28 20:31 UTC, ace-n commented
@bshaffer FYI - looks like the PHP 8.0 build isn't configured correctly.

2021-01-30 00:40 UTC, grayside approved these changes

2021-02-01 22:10 UTC, merged