[DO NOT MERGE] feat!(appengine): php72 -> php folder
GoogleCloudPlatform/php-docs-samples pull request #1270
Opened 2021-01-28 07:56 UTC by ace-n

**Do not merge** until we have the appropriate docs changes prepared.

2021-01-28 17:57 UTC, bshaffer requested changes
There are a LOT of instances of the path `appengine/php72/` in various sample `READMEs` and sample headers. We need to update them!

Examples:
 - https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/php72/storage/src/read_metadata.php#L21
 - https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/php72/auth/README.md#deploy-to-app-engine

2021-01-28 20:03 UTC, ace-n commented
@bshaffer good catch! Fixed those via `sed`.

2021-02-02 15:46 UTC, bshaffer reviewed
Do we think `appengine/php` is where these should go? Since we've removed `php55` samples, I would advocate `appengine/standard` is clearer and more informative.

2021-02-02 15:46 UTC, bshaffer commented on appengine/standard/README.md
> +Samples are now in appengine/php](../php72) for the PHP 7.2 version of App Engine Standard.
This also needs to be changed to `(../php)`

2021-02-02 21:59 UTC, ace-n commented on appengine/standard/README.md
> +Samples are now in appengine/php](../php72) for the PHP 7.2 version of App Engine Standard.
This was replaced with the `7.2` readme, which (now) has correct links.

2021-02-02 22:43 UTC, bshaffer approved these changes
LGTM!

2021-02-04 21:04 UTC, ace-n commented
Updated `secrets` files and force-pushed changes, as requested by @bshaffer.

@grayside over to you. 🛩️

2021-02-04 21:10 UTC, grayside approved these changes

2021-02-04 21:14 UTC, bshaffer commented
Adding do not merge as this is waiting on an internal docs change

2021-02-04 22:13 UTC, merged