docs: add a sample app using OAuth2 authorization flow
GoogleCloudPlatform/php-docs-samples pull request #1274
Opened 2021-02-04 21:09 UTC by ikuleshov

2021-02-17 20:11 UTC, ikuleshov commented on analyticsdata/quickstart_oauth2/index.php
> +    $oauth->updateToken(['refresh_token' => $_SESSION['access_token']]);
This line probably should be
  $oauth->updateToken(['access_token' => $_SESSION['access_token']]);

However, I get the following error if I try to set the access_token parameter instead of refresh_token:

Missing authorization code in /usr/local/google/home/ikuleshov/samples/php-analytics-data/samples/quickstart_oauth2/vendor/google/auth/src/OAuth2.php:492

However, passing the access token as refresh_token does the trick and the app works.

2021-02-18 21:36 UTC, dwsupplee requested changes

2021-02-18 21:36 UTC, dwsupplee commented on analyticsdata/quickstart.php
> +// $property_id = 'YOUR-GA4-PROPERTY-ID';
For folks checking this script out from the repository this conflicts with line 16 - would we be able to follow the style found here?: https://github.com/GoogleCloudPlatform/php-docs-samples/blob/40620bec1bc18775e79bc89cdcd41276786571b3/storage/quickstart.php#L25-L26

2021-02-18 21:36 UTC, dwsupplee commented on analyticsdata/test/quickstartTest.php
> +        $test_property_id = self::$testPropertyId || '222596558';
`$testPropertyId` looks to be missing a declaration

2021-02-18 21:36 UTC, dwsupplee commented on analyticsdata/quickstart.php
> +
Extra whitespace here

2021-02-18 21:36 UTC, dwsupplee commented on analyticsdata/quickstart_oauth2/composer.json
> +        "google/auth": "^1.14",
We shouldn't need to explicitly require auth, it is included transitively by the client package.

2021-02-18 21:36 UTC, dwsupplee commented on analyticsdata/quickstart_oauth2/index.php
> +    $oauth->setRefreshToken($_SESSION['refresh_token']);
We may want to check to ensure the refresh token is set before access too.

2021-02-18 21:36 UTC, dwsupplee commented on analyticsdata/quickstart_oauth2/index.php
> +
This whitespace can be dropped

2021-03-19 22:54 UTC, ikuleshov commented on analyticsdata/quickstart.php
> +// Copyright 2021 Google LLC
Done.

2021-03-19 22:55 UTC, ikuleshov commented on analyticsdata/test/quickstartTest.php
> +        $test_property_id = self::$testPropertyId || '222596558';
I renamed this to GA_TEST_PROPERTY_ID and added a placeholder to secrets-example.sh. Will now figure out how to actually add the default value to the secrets.

2021-03-19 22:56 UTC, ikuleshov commented on analyticsdata/quickstart.php
> +
Done

2021-03-19 22:56 UTC, ikuleshov commented on analyticsdata/quickstart_oauth2/composer.json
> +        "google/auth": "^1.14",
Done

2021-03-19 22:56 UTC, ikuleshov commented on analyticsdata/quickstart_oauth2/index.php
> +    $oauth->setRefreshToken($_SESSION['refresh_token']);
Done.

2021-03-19 22:58 UTC, ikuleshov commented on analyticsdata/quickstart_oauth2/index.php
> +
Done

2021-03-19 22:58 UTC, ikuleshov commented on analyticsdata/quickstart.php
> +// $property_id = 'YOUR-GA4-PROPERTY-ID';
Makes sense. Done!

2021-03-23 17:46 UTC, dwsupplee approved these changes
Looks good to me, just a few minor comments 👍

2021-03-23 17:46 UTC, dwsupplee commented on analyticsdata/README.md
> +5.  **Uncomment `$property_id` variable** if present in the snippet and specify
Would we please be able to update this from mentioning "uncomment" to something like "replace the placeholder value with..." since the sample was reworked a bit? This applies to https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1274/files#diff-c6a2ab981ff89383a2de2001d2ca6202f60a31ac07247bb22970b505d7aa0792R23 as well.

2021-03-23 19:06 UTC, ikuleshov commented on .kokoro/secrets-example.sh
> +export GA_TEST_PROPERTY_ID=
Done!

2021-03-23 19:09 UTC, ikuleshov commented on analyticsdata/README.md
> +5.  **Uncomment `$property_id` variable** if present in the snippet and specify
Done

2021-03-24 18:30 UTC, merged