chore(testing): add ability to skip GAE Flex tests
GoogleCloudPlatform/php-docs-samples pull request #1275
Opened 2021-02-06 00:11 UTC by ace-n

Related to cl/355949474

2021-02-08 20:48 UTC, bshaffer requested changes
Hmm, so we don't actually want to skip *all* flex tests. We just want to skip flex DEPLOYMENT tests. I think we could do this by:

1. Adding a check in each GAE flex deployment test to verify `RUN_FLEX_DEPLOYMENT_TESTS` should be `true`. This could be done by adding this to every `appengine/flexible/*/test/DeployTest.php` file:
    ```php
    /** @beforeClass */
    public static function checkProjectEnvVarBeforeClass()
    {
        self::requireEnv('RUN_FLEX_DEPLOYMENT_TESTS');
        self::checkProjectEnvVars();
    }
    ```

2. Add a block to `run_test_suite.sh` to temporarily set `RUN_DEPLOYMENT_TESTS` to false if the directory contains an `app.yaml` with `env: flex`. I can't really see a good/elegant way to do that with the current script though, so I prefer option 1

2021-02-08 20:48 UTC, bshaffer commented on .kokoro/common.cfg
> +}
We can remove this one!

2021-02-08 20:48 UTC, bshaffer commented on appengine/flexible/datastore/test.sh
> +fi
Do we need this file? I don't think so.

2021-02-08 20:50 UTC, ace-n commented
> Add a block to run_test_suite.sh to temporarily set RUN_DEPLOYMENT_TESTS to false if the directory contains an app.yaml with env: flex. I can't really see a good/elegant way to do that with the current script though, so I prefer option 1

We already do this - that's what the `grep` in `run_test_suite.sh` is for. 🙂

2021-02-08 20:53 UTC, ace-n commented on appengine/flexible/datastore/test.sh
> +fi
Good catch - reverted.

2021-02-08 20:53 UTC, ace-n commented on .kokoro/common.cfg
> +}
Done.

2021-02-10 21:06 UTC, bshaffer approved these changes
Looks great! Should we skip the deployment test in endpoints/getting-started as well? I believe so!

2021-02-11 00:56 UTC, merged