feat(functions): add Firestore reactive sample
GoogleCloudPlatform/php-docs-samples pull request #1292
Opened 2021-02-26 02:41 UTC by ace-n

2021-03-02 19:25 UTC, bshaffer approved these changes

2021-03-02 19:53 UTC, grayside requested changes

2021-03-02 19:53 UTC, grayside commented on functions/firebase_firestore_reactive/index.php
> +        'projectId' => getenv('GOOGLE_PROJECT_ID'),
nit: should not rely on GOOGLE_PROJECT_ID in samples. GOOGLE_CLOUD_PROJECT is the more recent variable name, but serverless samples shouldn't rely on a custom variable if we can help it.

2021-03-02 19:53 UTC, grayside commented on functions/firebase_firestore_reactive/index.php
> +        // Don't perform a(nother) write to avoid infinite loops
nit: parenthetical word will be confusing to non-native english readers.

2021-03-02 19:53 UTC, grayside commented on functions/firebase_firestore_reactive/php.ini
> +extension=grpc.so
Is this leaking from another PR? Why do we need to enable gRPC to use Firestore Reactive sample?

2021-03-02 19:53 UTC, grayside commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +            'projects/' . $project . '/databases/(default)/documents/' . self::$collectionName . '/' . self::$documentName;
nit: 80 char limit if possible, sprintf() for readability.

2021-03-02 19:53 UTC, grayside commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +    private function processFunctionLogs(CloudFunction $fn, string $startTime, callable $process)
Delete if it now available in php-utils trait.

2021-03-02 19:53 UTC, grayside commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +            self::$firestoreClient = new FirestoreClient();
If we don't need to set this explicitly here, should we remove from sample, adding a comment for what to name the variable?

2021-03-03 00:39 UTC, ace-n commented on functions/firebase_firestore_reactive/index.php
> +        'projectId' => getenv('GOOGLE_PROJECT_ID'),
Removed this variable.

2021-03-03 00:40 UTC, ace-n commented on functions/firebase_firestore_reactive/php.ini
> +extension=grpc.so
I believe the Firestore client library requires this, per @bshaffer.

2021-03-03 08:26 UTC, ace-n commented on functions/firebase_firestore_reactive/index.php
> +        // Don't perform a(nother) write to avoid infinite loops
Fixed.

2021-03-03 08:29 UTC, ace-n commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +            'projects/' . $project . '/databases/(default)/documents/' . self::$collectionName . '/' . self::$documentName;
Done.

2021-03-03 08:31 UTC, ace-n commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +            self::$firestoreClient = new FirestoreClient();
I think the top `if` statement should say `firestoreClient` instead of `firestore`. Updated accordingly.

2021-03-03 08:33 UTC, ace-n commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +    private function processFunctionLogs(CloudFunction $fn, string $startTime, callable $process)
Done.

2021-03-03 21:22 UTC, grayside commented on functions/firebase_firestore_reactive/php.ini
> +extension=grpc.so
Discussion in progress on enabling grpc by default. For now this makes sense.

2021-03-03 21:27 UTC, grayside approved these changes
Approval pending deleting the things.

2021-03-03 21:27 UTC, grayside commented on functions/firebase_firestore_reactive/test/IntegrationTest.php
> +        //$this->assertEquals($statusCode, $resp->getStatusCode());
Deleteme

2021-03-03 21:27 UTC, grayside commented on functions/firebase_firestore_reactive/test/IntegrationTest.php
> +                'statusCode' => '200',
Deleteme, we don't need status code check in this test.

2021-03-03 21:27 UTC, grayside commented on functions/firebase_firestore_reactive/test/IntegrationTest.php
> +        string $statusCode
deleteme

2021-03-03 21:27 UTC, grayside commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +            var_dump($actual);
deleteme

2021-03-03 21:30 UTC, grayside commented
PHP 7.4 failed for some reason, trying a retest.

2021-03-03 23:52 UTC, ace-n commented on functions/firebase_firestore_reactive/test/IntegrationTest.php
> +                'statusCode' => '200',
Done.

2021-03-03 23:52 UTC, ace-n commented on functions/firebase_firestore_reactive/test/IntegrationTest.php
> +        //$this->assertEquals($statusCode, $resp->getStatusCode());
Done.

2021-03-03 23:52 UTC, ace-n commented on functions/firebase_firestore_reactive/test/DeployTest.php
> +            var_dump($actual);
Done.

2021-03-03 23:53 UTC, ace-n commented on functions/firebase_firestore_reactive/test/IntegrationTest.php
> +        string $statusCode
Done.

2021-03-03 23:55 UTC, ace-n commented
PR failure seems to be lint-related. (There's probably a mismatch between the CI lint setup and my local machine.)

Fixed though, so hopefully tests will pass now.

2021-03-04 00:00 UTC, merged