fix(functions/http_content_type): PHP warning when header doesn't exist
GoogleCloudPlatform/php-docs-samples pull request #1298
Opened 2021-03-04 16:29 UTC by bshaffer

2021-03-04 16:46 UTC, ace-n approved these changes
LGTM.

2021-03-04 17:00 UTC, grayside requested changes

2021-03-04 17:00 UTC, grayside commented on functions/http_content_type/index.php
> +    switch ($request->getHeaderLine('content-type')) {
Double-checked the [spec](https://www.php-fig.org/psr/psr-7/#headers-with-multiple-values), and for headers that don't accept comma-delimited values, we should use `getHeader()`.

A further problem, this header accepts further attributes (such as charset) after a semicolon.

Something like this:

```suggestion
    $header = $request->getHeader('content-type');
    $content_type = trim(explode(';', $header)[0]);
    switch ($content_type) {
```

2021-03-04 19:54 UTC, bshaffer commented on functions/http_content_type/index.php
> +    switch ($request->getHeaderLine('content-type')) {
The `getHeaderLine` function is to provide convenience for working with headers as strings. It shouldn't be used with `Cookie-Set` because multiple headers with `Cookie-Set` can exist in a single request and `Cookie-Set` _cannot_ be concatenated with a comma.

However, `Content-Type` is not expected to have multiple headers sent in one request, so we can use `getHeaderLine` instead. In our example, if someone send in multiple `Content-Type` lines, the switch will not match. We could throw an exception under the `default` switch case if you'd prefer, but I do think `getHeaderLine` is acceptable to use here.

2021-03-08 22:12 UTC, dwsupplee approved these changes

2021-03-12 18:16 UTC, grayside commented on functions/http_content_type/index.php
> +    switch ($request->getHeaderLine('content-type')) {
I'm fine going with that part. Should I file a follow-up issue for handling further attributes like charset?

2021-03-12 18:16 UTC, grayside approved these changes

2021-03-12 19:04 UTC, merged

2021-03-12 19:05 UTC, bshaffer commented on functions/http_content_type/index.php
> +    switch ($request->getHeaderLine('content-type')) {
Sounds good to me!