chore(functions): add lazy global var details
GoogleCloudPlatform/php-docs-samples pull request #1302
Opened 2021-03-11 04:36 UTC by ace-n

**Note:** for the "lazy globals" section](https://cloud.google.com/functions/docs/bestpractices/tips#do_lazy_initialization_of_global_variables), I plan to highlight the comment I'm adding here within the sample.

2021-03-12 17:41 UTC, bshaffer approved these changes

2021-03-12 19:12 UTC, grayside requested changes

2021-03-12 19:14 UTC, grayside requested changes

2021-03-12 19:14 UTC, grayside commented on functions/tips_scopes/index.php
> +// [START functions_tips_lazy_globals]
This sample is shown in the docs in adjacent sections of the same doc, I don't think it makes a lot of sense to reuse across both. I think either we don't need this snippet or it needs to be separate for clarity.

2021-03-17 01:26 UTC, ace-n commented on functions/tips_scopes/index.php
> +    // the function itself
#1304 addresses preloading. @grayside we should discuss there how we want to approach this.

(If we _do_ decide to use preloading, then we can incorporate it into this sample.)

2021-04-02 19:58 UTC, ace-n commented
@grayside and I decided to skip this sample, given that it doesn't make sense for PHP.

(It's other-language counterparts aren't used in the docs either, so they should probably be deleted.)

2021-04-02 19:58 UTC, closed without merging