feat: add samples for Datastore Admin
GoogleCloudPlatform/php-docs-samples pull request #1329
Opened 2021-03-31 21:47 UTC by jdpedrie

These tests take ~15 minutes to execute.

2021-04-13 21:13 UTC, bshaffer requested changes

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/test/IndexTest.php
> +        TestTrait::runFunctionSnippet as traitRunFunctionSnippet;
No need for this override, just use `runFunctionSnippet`

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/test/IndexTest.php
> +        self::checkProjectEnvVars();
This also shouldn't be necessary, it'll be called automatically using the `@beforeClass` annotation.

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/test/EntitiesTest.php
> +        TestTrait::runFunctionSnippet as traitRunFunctionSnippet;
Same here!

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/test/EntitiesTest.php
> +        self::checkProjectEnvVars();
Same here!

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/src/index_get.php
> +function index_get($projectId, $indexId) {
nit: put curly brace on its own line
```suggestion
function index_get($projectId, $indexId)
{
```

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/src/index_list.php
> +function index_list($projectId, $filter = "") {
Same here: 
```suggestion
function index_list($projectId, $filter = "")
{
```

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/src/index_delete.php
> +function index_delete($projectId, $indexId) {
```suggestion
function index_delete($projectId, $indexId)
{
```

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/src/index_create.php
> +function index_create($projectId, $kind) {
```suggestion
function index_create($projectId, $kind)
{
```

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/src/entities_import.php
> +function entities_import($projectId, $inputUri) {
```suggestion
function entities_import($projectId, $inputUri)
{
```

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/src/entities_export.php
> +function entities_export($projectId, $outputUrlPrefix) {
```suggestion
function entities_export($projectId, $outputUrlPrefix)
{
```

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/quickstart.php
> +$projectId = 'YOUR_PROJECT_ID';
this is never used. Did you mean to pass this into `DatastoreAdminClient`?

2021-04-13 21:13 UTC, bshaffer commented on datastoreadmin/src/entities_export.php
> +        printf("The export operation succeeded. File location is %s", $operation->getResult()->getOutputUrl());
nit, but all of these `printf` statements should use single quotes and add newlines!

```suggestion
        printf('The export operation succeeded. File location is %s' . PHP_EOL, $operation->getResult()->getOutputUrl());
```

2021-05-15 18:59 UTC, jdpedrie commented
@bshaffer these tests are reliably passing locally against multiple projects, and failing reliably on kokoro against multiple projects. Is there perhaps something I'm missing with the configuration of the kokoro projects?

2021-07-14 15:03 UTC, bshaffer commented on datastoreadmin/test/EntitiesTest.php
> +            "gs://%s/%s",
```suggestion
            "gs://%s-datastoreadmin/%s",
```

2021-07-14 19:10 UTC, bshaffer commented on datastoreadmin/src/entities_export.php
> +    $admin = new DatastoreAdminClient();
We should explicitly set the `projectId` whenever it's being passed in, to make sure the project ID of the client and the project ID of the operation are the same. 

```suggestion
    $admin = new DatastoreAdminClient([
        'projectId' => $projectId,
    ]);
```

2021-08-04 22:29 UTC, bshaffer commented
I believe the cause of the problem is when tested on projects using "Datastore Legacy", the operation to create the index pass, but when tested on projects using "Firestore in Datastore Mode", the tests fail.

2023-02-27 19:10 UTC, meredithslota commented
My understanding is that the PHP Datastore client has an autogenerated admin client library (source: @kolea2) and thus has autogenerated code samples to go with it. Those code samples are found here: https://github.com/googleapis/google-cloud-php/tree/main/DatastoreAdmin/samples/V1/DatastoreAdminClient Closing this accordingly to reduce duplication.

2023-02-27 19:10 UTC, closed without merging