chore(CODEOWNERS): add Serverless folks
GoogleCloudPlatform/php-docs-samples pull request #1344
Opened 2021-04-13 01:02 UTC by ace-n

Let's (more) clearly denote who owns what

cc @iennae

2021-04-21 03:57 UTC, grayside requested changes

2021-04-21 03:57 UTC, grayside commented on CODEOWNERS
> +/run                       @grayside @GoogleCloudPlatform/cdpe-cbr-containers
run should have the same ownership as the other serverless products. I will double check and decommission `cdpe-cbr-containers`.

2021-04-21 03:57 UTC, grayside commented on CODEOWNERS
> +/run                       @grayside @GoogleCloudPlatform/cdpe-cbr-containers
It looks like the convention is for `php-admins` to remain as codeowner for all samples. This seems important to allow general repo maintenance. Same for the firebase analytics sample.

2021-04-21 03:57 UTC, grayside commented on CODEOWNERS
> +/functions/firebase_analytics   @schandel @samtstern
PHP admins here too.

2021-04-21 03:57 UTC, grayside commented on CODEOWNERS
> +/functions/firebase_analytics   @schandel @samtstern
Is there a firebase team that should be used here? Shouldn't they be reviewers of this PR?

2021-04-21 03:57 UTC, grayside commented on CODEOWNERS
> +/storage/                 @GoogleCloudPlatform/storage-dpe @GoogleCloudPlatform/php-admins
nit: Why move this out from the block of product directives above?

2021-04-21 05:08 UTC, ace-n commented on CODEOWNERS
> +/run                       @grayside @GoogleCloudPlatform/cdpe-cbr-containers
Thanks.

Should we remove the specific-person assignments here too, since we're trying to better distribute workloads within the team? (OTOH, a single point-of-contact can help ensure timely responses and prevent a "tragedy of the commons".)

cc @iennae

2021-04-21 05:08 UTC, ace-n commented on CODEOWNERS
> +/run                       @grayside @GoogleCloudPlatform/cdpe-cbr-containers
Done.

2021-04-21 05:08 UTC, ace-n commented on CODEOWNERS
> +/storage/                 @GoogleCloudPlatform/storage-dpe @GoogleCloudPlatform/php-admins
Not sure, honestly. Reverted.

2021-04-21 05:08 UTC, ace-n commented on CODEOWNERS
> +/functions/firebase_analytics   @schandel @samtstern
cc @schandel @samtstern (I don't think they're members of the GCP org, so I can't add them as reviewers)

2021-04-21 05:08 UTC, ace-n commented on CODEOWNERS
> +/functions/firebase_analytics   @schandel @samtstern
Done.

2021-04-21 15:03 UTC, bshaffer commented on CODEOWNERS
> +/run                       @grayside @GoogleCloudPlatform/cdpe-cbr-containers
I agree with this, seems like we should remove personal github handles.

Mine is included, but that is because it's an exception, and the samples are removed if I ever stop maintaining them 😃

2021-06-28 19:20 UTC, bshaffer requested changes

2021-06-28 19:20 UTC, bshaffer commented on CODEOWNERS
> +/functions/firebase_analytics   @schandel @samtstern @GoogleCloudPlatform/php-admins
This already exists in the file
```suggestion
```

2021-06-28 19:20 UTC, bshaffer approved these changes

2021-08-20 02:16 UTC, ace-n commented
@grayside ping? 🙂

2021-08-20 03:47 UTC, grayside requested changes

2021-08-20 03:47 UTC, grayside commented on CODEOWNERS
> +/run                      @GoogleCloudPlatform/cdpe-serverless @GoogleCloudPlatform/php-admins
Since this PR was created, we've changed our GitHub team. I'm just at the start of sending 
PRs around to update CODEOWNERS.

```suggestion
/appengine/standard       @GoogleCloudPlatform/aap-dpes @GoogleCloudPlatform/php-admins
/functions                @GoogleCloudPlatform/aap-dpes @GoogleCloudPlatform/php-admins
/run                      @GoogleCloudPlatform/aap-dpes @GoogleCloudPlatform/php-admins
```

2021-08-20 03:49 UTC, grayside commented on CODEOWNERS
> +/functions/firebase_analytics   @schandel @samtstern
If they're not in the org, how can they be CODEOWNERS?

2022-10-17 19:56 UTC, iennae commented
replaced by #1708

2022-10-17 19:56 UTC, closed without merging