feat: Compute Engine sample to present default values behaviour
GoogleCloudPlatform/php-docs-samples pull request #1383
Opened 2021-06-14 09:38 UTC by rsamborski

Compute Engine sample showcasing how to set usage reports bucket which presents the default values behaviour.

2021-06-16 18:20 UTC, bshaffer requested changes

2021-06-16 18:20 UTC, bshaffer commented on compute/cloud-client/instances/src/set_usage_export_bucket.php
> +}
To be consistent with the other samples in this repo, let's have only a single function in each file, and name the file the same name. So this needs to be three files, `src/set_usage_export_bucket.php`, `src/get_usage_export_bucket.php`, and `disable_usage_export_bucket.php`.

2021-06-16 20:58 UTC, rsamborski commented on compute/cloud-client/instances/src/set_usage_export_bucket.php
> +}
I was thinking of how to do that and there is a slight problem with the split approach. We are trying to kill two birds with these samples: 

 1) Prepare individual samples (region tags: compute_usage_report_set, compute_usage_report_get, compute_usage_report_disable) for this page: https://cloud.google.com/compute/docs/logging/usage-export
No issue with splitting.

 2) Showcase the default value behavior for GCE GAPIC release (region tag: compute_instances_verify_default_value) which should present the set_usage_export_bucket and get_usage_export_bucket functions.
This can be split only in case one region tag can exist in two different files. Is this something that is possible?

Regardless to the answer above the disable function is not used in 2, so it can be moved to another file.

2021-06-17 17:12 UTC, bshaffer approved these changes
One small change otherwise this looks great

2021-06-17 17:12 UTC, bshaffer commented on CODEOWNERS
> +/compute/cloud-client/
I believe you're missing the owning entity after ther directory

2021-06-17 20:00 UTC, rsamborski commented on CODEOWNERS
> +/compute/cloud-client/
Fixed

2021-06-17 20:10 UTC, merged