feat: fill storage sample gap
GoogleCloudPlatform/php-docs-samples pull request #1421
Opened 2021-06-22 01:44 UTC by jdpedrie

Relies on and includes code from #1384.

This PR adds missing samples and accompanying tests. It also finishes upgrading storage samples to the new runner.

Some of these are a bit difficult to run locally, so I think I'll have to fix a few failures once kokoro finishes.

2021-06-23 23:55 UTC, JesseLovelace requested changes
Hi, thank you! Have a few notes so far, still reading everything. One big thing is that, per part two of the [sample guidelines](https://docs.google.com/document/d/1HXdroH24LfNRlsuWYXH5wOeaAC9y73WVnUI-eJSBqgw/edit?resourcekey=0-G_6ID_1JogvVhxoQNggFLw), every argument in a sample should have an example as well as a description.

For example, if $bucketName is a parameter, it should have an example like `$bucketName = "your-unique-bucket-name";` under the description (`@param string $bucketName the name of your Cloud Storage bucket.`)

Every parameter should have an example in the documentation, please add these. Thanks!

2021-06-23 23:55 UTC, JesseLovelace commented on storage/src/add_bucket_default_owner.php
> + * @param array $options
Missing description

2021-06-23 23:55 UTC, JesseLovelace commented on storage/src/add_bucket_owner.php
> + * @param array $options
Missing description

2021-06-23 23:55 UTC, JesseLovelace commented on storage/src/add_file_owner.php
> + * @param array $options
Missing description

2021-06-23 23:55 UTC, JesseLovelace commented on storage/src/compose_file.php
> +    $objectsToCompose = [$firstObjectName, $secondObjectName];
Add a comment here like "//Here we're only composing two objects, but we could compose up to 32"

2021-06-26 19:25 UTC, jdpedrie commented
Thanks @JesseLovelace,

I updated all the samples to include the examples of parameter values and in general to make them consistent. I opted to place the sample values within the docblock, but if you don't like that I'll move them into the function body to align closer with how it's done in java.

Still working on a couple tests, but so long as you're happy with this direction, it should be nearly finished.

2021-06-28 18:53 UTC, bshaffer requested changes
Mostly nits!

2021-06-28 18:53 UTC, bshaffer commented on storage/src/add_bucket_acl.php
>   *
I think this should be removed, so the example is with the  `$role` param?
```suggestion
```

2021-06-28 18:53 UTC, bshaffer commented on storage/src/activate_hmac_key.php
>  # [END storage_activate_hmac_key]
super-nit, but for consistency can we add a full line of whitespace after the region tags and before the sample helper lines?
```suggestion
# [END storage_activate_hmac_key]

```

2021-06-28 18:53 UTC, bshaffer commented on storage/src/add_bucket_owner.php
> + * Copyright 2016 Google Inc.
```suggestion
 * Copyright 2021 Google Inc.
```

2021-06-28 18:53 UTC, bshaffer commented on storage/src/add_bucket_default_owner.php
> + * Copyright 2016 Google Inc.
```suggestion
 * Copyright 2021 Google Inc.
```

2021-06-28 18:53 UTC, bshaffer commented on storage/src/add_file_owner.php
> + * Copyright 2016 Google Inc.
```suggestion
 * Copyright 2021 Google Inc.
```

2021-06-28 18:53 UTC, bshaffer commented on storage/test/BucketLockTest.php
> +class BucketLockCommandTest extends TestCase
```suggestion
class BucketLockTest extends TestCase
```

2021-06-28 18:53 UTC, bshaffer commented on storage/test/BucketLockTest.php
> +//     public function testEnableDisableGetDefaultEventBasedHold()
I'm guessing this is commented out by mistake?

2021-06-28 20:05 UTC, bshaffer requested changes
These parameters are out of order and should be changed in either the test or the sample. I suggest changing the sample for consistency, but I can only suggest changing in the test so 🤷‍♂️

2021-06-28 20:05 UTC, bshaffer commented on storage/test/HmacTest.php
> +            $this->hmacServiceAccount,
```suggestion
            $this->hmacServiceAccount,
            self::$projectId
```

2021-06-29 22:44 UTC, bshaffer commented
There seems to be a lot of errors happening still. The `HmacTest` probably should just use `self::$projectId . '@appspot.gserviceaccount.com'` as the HMAC service account.  I looked into the other failing tests and I am not sure what's happening, but one of them is from the newly added `object_csek_to_cmek`. The other errors are very strange, and as they aren't failing on `master`, they must be being introduced by this change.

I'd like to get this merged soon, so let me know if you want to work together to get the tests passing...

2021-06-30 13:45 UTC, bshaffer commented on storage/src/define_bucket_website_configuration.php
> + *     Example: `$notFoundPageObject = '404.html';`
```suggestion
 * @param string $indexPageObject the name of an object in the bucket to use as
 *     an index page for a static website bucket.
 *     Example: `$indexPageObject = 'index.html';`
 * @param string $notFoundPageObject the name of an object in the bucket to use
 *     as the 404 Not Found page.
 *     Example: `$notFoundPageObject = '404.html';`
```

2021-06-30 13:45 UTC, bshaffer commented on storage/src/download_encrypted_object.php
>   *
```suggestion
```

2021-06-30 13:45 UTC, bshaffer commented on storage/src/enable_default_kms_key.php
>   *
```suggestion
```

2021-06-30 13:45 UTC, bshaffer commented on storage/src/get_hmac_key.php
> + *     Example: `$projectId = 'my-project-id';`
I'm not going to request to revert all of these, but do we really think this is a useful example?

I can see for some things, such as `$accessId` or `$userId`, it may be helpful to have an example of what the string looks like. But for `$projectId`, `$bucketName`, etc, it doesn't seem necessary. I'm just interested to know the reasoning here, definitely not a blocker!

2021-06-30 13:45 UTC, bshaffer commented on storage/src/compose_file.php
> + *     Example: `$firstObjectName = 'my-object-1';`
I imagine most objects would have extensions. So if the purpose here is to give an example, shouldn't we provide an extension?

2021-06-30 14:08 UTC, jdpedrie commented on storage/src/get_hmac_key.php
> + *     Example: `$projectId = 'my-project-id';`
I'm following the lead of the [java samples](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/ChangeObjectStorageClass.java#L29-L36), but trying to fit it into the existing docblocks we use.

2021-06-30 14:08 UTC, jdpedrie commented on storage/src/compose_file.php
> + *     Example: `$firstObjectName = 'my-object-1';`
Java, being the example here, generally seem to not use extensions. (see link in previous comment).

2021-06-30 18:12 UTC, JesseLovelace commented on storage/src/get_hmac_key.php
> + *     Example: `$projectId = 'my-project-id';`
@bshaffer It's per my suggestion and it's just for consistency with the storage samples in other languages, i'm directing all storage samples to do this

2021-06-30 18:20 UTC, JesseLovelace commented
@jdpedrie: Thank you! Actually, I would prefer them to be within the method body and for the "example" word to be removed, more like in java. the idea is supposed to be that the user can uncomment the line to work with that example. (Note: I don't know too much about PHP, if variable overriding doesn't work like how it does in Java and uncommenting a line like that would lead to errors, then we can figure out a better way or leave it how it is)

2021-06-30 18:55 UTC, bshaffer commented
@JesseLovelace It would be possible to what you suggest, but not in the docblock. It would need to be in the function body, like this:

```php
/**
 * Activate an HMAC key.
 *
 * @param string $projectId The ID of your Google Cloud Platform project.
 * @param string $accessId Access ID for an inactive HMAC key.
 */
function activate_hmac_key($projectId, $accessId)
{
    // $projectId = 'my-project-id';
    // $accessId = 'GOOG0234230X00';
    // THE REST OF THE SAMPLE
}
```

```

2021-06-30 20:07 UTC, JesseLovelace commented
I agree! The way you've proposed here with the examples in the function body is perfect

2021-06-30 23:37 UTC, JesseLovelace approved these changes
Thanks for making those changes! LGTM from my perspective, but still needs Brent's review as a language expert

2021-07-01 13:11 UTC, bshaffer commented on storage/src/add_bucket_conditional_iam_binding.php
>  function add_bucket_conditional_iam_binding($bucketName, $role, $members, $title, $description, $expression)
for parameter values that are arrays, the `samples_helper.php` function needs a typehint so it can explode user-input:
```suggestion
function add_bucket_conditional_iam_binding($bucketName, $role, array $members, $title, $description, $expression)
```

Otherwise a string will be passed in on the CLI, and that will result in an error somewhere down the line, I assume.

2021-07-01 13:11 UTC, bshaffer commented on storage/src/add_bucket_iam_member.php
>  function add_bucket_iam_member($bucketName, $role, $members)
For the same reason as above
```suggestion
function add_bucket_iam_member($bucketName, $role, array $members)
```

2021-07-01 13:30 UTC, bshaffer commented on storage/src/get_metadata.php
> +function get_metadata($bucketName, $objectName)
Does this have a test?

2021-07-01 13:30 UTC, bshaffer commented on storage/src/get_metadata.php
> + * Copyright 2016 Google Inc.
```suggestion
 * Copyright 2021 Google Inc.
```

2021-07-01 13:30 UTC, bshaffer commented on storage/src/add_bucket_default_acl.php
>  # [END storage_add_bucket_default_owner]
Shouldn't this and the above region tag be `storage_add_bucket_default_acl`?
```suggestion
# [END storage_add_bucket_default_acl]
```

2021-07-01 13:30 UTC, bshaffer commented on storage/src/add_bucket_default_owner.php
> +function add_bucket_default_owner($bucketName, $entity, $role)
Does this have a test?

2021-07-01 13:30 UTC, bshaffer commented on storage/src/add_bucket_owner.php
> +function add_bucket_owner($bucketName, $entity, $role)
Does this have a test?

2021-07-01 13:30 UTC, bshaffer commented on storage/src/add_object_acl.php
>  # [END storage_add_file_owner]
Both of these tags should be `storage_add_object_acl`
```suggestion
# [END storage_add_object_acl]
```

2021-07-01 13:30 UTC, bshaffer commented on storage/src/add_file_owner.php
> +function add_file_owner($bucketName, $objectName, $entity, $role)
Does this have a test?

2021-07-01 13:30 UTC, bshaffer commented on storage/src/delete_object_acl.php
>  # [END storage_remove_file_owner]
I'm starting to think all these were renamed but the tests and these files didn't get removed/refactored, and that's why we have duplicate region tags...

2021-07-01 13:30 UTC, bshaffer commented on storage/src/generate_signed_url.php
> +function generate_signed_url($bucketName, $objectName)
I'm not seeing a test for this one... I think because it's supposed to replace `get_object_v2_signed_url`?

2021-07-01 13:30 UTC, bshaffer commented on storage/src/print_bucket_acl.php
> +function print_bucket_acl($bucketName)
I couldn't find tests for this

2021-07-01 13:30 UTC, bshaffer commented on storage/src/print_file_acl.php
> +function print_file_acl($bucketName, $objectName)
I couldn't find tests for this

2021-07-01 13:30 UTC, bshaffer commented on storage/src/generate_upload_signed_url_v4.php
> +function generate_upload_signed_url_v4($bucketName, $objectName)
Not seeing a test for this one

2021-07-01 13:30 UTC, bshaffer commented on storage/src/remove_bucket_default_owner.php
> +function remove_bucket_default_owner($bucketName, $entity)
I couldn't find tests for this

2021-07-01 13:30 UTC, bshaffer commented on storage/src/remove_bucket_owner.php
> +function remove_bucket_owner($bucketName, $entity)
I couldn't find tests for this

2021-07-01 13:30 UTC, bshaffer commented on storage/src/remove_file_owner.php
> +function remove_file_owner($bucketName, $objectName, $entity)
I couldn't find tests for this

2021-07-01 13:30 UTC, bshaffer commented on storage/src/set_bucket_default_kms_key.php
> +function set_bucket_default_kms_key($bucketName, $kmsKeyName)
I couldn't find tests for this

2021-08-04 20:36 UTC, bshaffer approved these changes

2021-08-04 20:37 UTC, merged