feat: update query option samples with optimizerStatisticsPackage
GoogleCloudPlatform/php-docs-samples pull request #1425
Opened 2021-06-23 23:50 UTC by larkee

2021-06-23 23:56 UTC, skuruppu approved these changes

2021-06-24 03:25 UTC, dwsupplee approved these changes

2021-06-28 19:16 UTC, bshaffer requested changes
I'm thinking that it's explained in the context of cloudsite, but I'd still appreciate a little context or clarification into the values provided

2021-06-28 19:16 UTC, bshaffer commented on spanner/src/create_client_with_query_options.php
> +            'optimizerStatisticsPackage' => 'auto_20191128_14_47_22UTC'
This is a strange  value to have here (as opposed to `latest` below). Can we get a clarifying comment as to why it's set to the value it has?

2021-06-28 19:16 UTC, bshaffer commented on spanner/src/query_data_with_query_options.php
> +                'optimizerStatisticsPackage' => 'latest'
Also here, even though the value makes no sense, I'd love a little clarify as to why.

2021-07-01 06:31 UTC, skuruppu commented on spanner/src/create_client_with_query_options.php
> +            'optimizerStatisticsPackage' => 'auto_20191128_14_47_22UTC'
@larkee is on vacation so I tried to push a commit to their repo but didn't have the permissions.

If you're ok with it, I created #1438 to replace this PR.

2021-07-02 17:20 UTC, closed without merging