Refactoring set, get and disable usage export bucket samples
GoogleCloudPlatform/php-docs-samples pull request #1433
Opened 2021-06-30 20:17 UTC by rsamborski

Refactoring set, get and disable usage export bucket samples by putting them in separate files. Removal of compute_instances_verify_default_value region tag as we decided not to use it.

2021-07-01 13:00 UTC, bshaffer requested changes

2021-07-01 13:00 UTC, bshaffer commented on compute/cloud-client/instances/test/instancesTest.php
>          ob_start();
We shouldn't need these

2021-07-01 13:33 UTC, bshaffer commented on compute/cloud-client/instances/test/instancesTest.php
>          $operation = set_usage_export_bucket(self::$projectId, self::$bucketName);
So instead of doing this, we would typically print the operation ID in the output of the sample, and then use that in the test to check the operation....

But an even better way is just to include the `wait` function in the sample, and then check the export bucket directly after that.

2021-07-02 08:16 UTC, rsamborski commented on compute/cloud-client/instances/src/disable_usage_export_bucket.php
> +    return $projectsClient->setUsageExportBucket($projectId, null);
Fixed

2021-07-02 08:17 UTC, rsamborski commented on compute/cloud-client/instances/test/instancesTest.php
> +        require_once "src/disable_usage_export_bucket.php";
Fixed

2021-07-02 08:17 UTC, rsamborski commented on compute/cloud-client/instances/test/instancesTest.php
>          $operation = set_usage_export_bucket(self::$projectId, self::$bucketName);
Fixed, I moved waiting inside the sample code instead of keeping it only in tests.

2021-07-02 08:18 UTC, rsamborski commented
Pending TW's review before merging

2021-07-02 09:08 UTC, rsamborski commented on compute/cloud-client/instances/test/instancesTest.php
>          ob_start();
Fixed

2021-07-02 09:08 UTC, rsamborski commented on compute/cloud-client/instances/src/get_usage_export_bucket.php
> +        return null;
Fixed

2021-07-02 14:36 UTC, bshaffer approved these changes

2021-07-05 09:22 UTC, merged