feat(spanner): add samples for CMMR
GoogleCloudPlatform/php-docs-samples pull request #1457
Opened 2021-07-29 07:57 UTC by larkee

This PR adds samples for Customer Managed Multi Region instance configurations.

2021-07-30 03:11 UTC, larkee commented
Test failures are unrelated and will be fixed by #1459

2021-07-30 03:22 UTC, devbww commented on spanner/src/create_database_with_default_leader.php
> +        version_retention_period = '$defaultLeader')"
s/version_retention_period/default_leader/

2021-07-30 03:38 UTC, larkee commented on spanner/src/create_database_with_default_leader.php
> +        version_retention_period = '$defaultLeader')"
Good catch! Fixed :+1:

2021-07-30 14:08 UTC, hengfengli commented on spanner/test/spannerTest.php
> +        $this->assertStringContainsString(self::$defaultLeader, $output);
Shouldn't this be `self::$updatedDefaultLeader`?

2021-07-30 14:09 UTC, hengfengli commented on spanner/test/spannerTest.php
> +        $output = $this->runFunctionSnippet('create_database_with_default_leader', [
The snippet does not match the test name.

2021-07-30 14:11 UTC, hengfengli commented on spanner/test/spannerTest.php
> +        self::$defaultLeader = 'us-east4';
Maybe change this to `us-central1` to keep `defaultLeader` and `updatedDefaultLeader` being different?

2021-07-30 14:12 UTC, hengfengli approved these changes
LGTM. Some small issues.

2021-08-05 04:32 UTC, larkee commented on spanner/test/spannerTest.php
> +        $this->assertStringContainsString(self::$defaultLeader, $output);
Correct!

2021-08-05 04:32 UTC, larkee commented on spanner/test/spannerTest.php
> +        self::$defaultLeader = 'us-east4';
Whoops! :sweat_smile:

2021-08-05 04:35 UTC, larkee commented on spanner/test/spannerTest.php
> +        $output = $this->runFunctionSnippet('create_database_with_default_leader', [
Good catch!

2021-08-09 00:52 UTC, hengfengli commented
Hi @dwsupplee , can we get an approval from you? Thanks.

2021-08-10 19:54 UTC, dwsupplee requested changes

2021-08-10 19:54 UTC, dwsupplee commented on spanner/src/create_database_with_default_leader.php
> +require_once __DIR__ . '/../../testing/sample_helpers.php';
https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1422 introduced adding `// The following 2 lines are only needed to run the samples` prior to these lines for clarification - would you be open to following the same pattern here?

2021-08-10 19:54 UTC, dwsupplee commented on spanner/src/get_database_ddl.php
> + * Updates the default leader of the database.
This description is incorrect.

2021-08-10 19:54 UTC, dwsupplee commented on spanner/src/get_instance_config.php
> +function get_instance_config($instanceConfig)
The body of the method gets the leader options, which seems like a subset of the instance config. What are your thoughts on updating this to be something like `get_instance_config_leader_options` , or more broadly just printing out all the instance config options?

2021-08-10 19:54 UTC, dwsupplee commented on spanner/src/query_information_schema_database_options.php
> + * Updates the default leader of the database.
This is incorrect.

2021-08-10 19:54 UTC, dwsupplee commented on spanner/src/query_information_schema_database_options.php
> +    if (!$results->stats()['rowCountExact']) {
I don't have a strong knowledge of the underlying call here, but just wanted to confirm - does `rowCountExact` equate to not having an option for `default_leader`?

2021-08-10 19:54 UTC, dwsupplee commented on spanner/src/query_information_schema_database_options.php
> +        WHERE s.OPTION_NAME = 'default_leader'");
I trust your judgement on what you'd like to do here, but most PHP style guides prefer the closing bracket on a newline: 

```
$results = $database->execute(
    "SELECT s.OPTION_NAME, s.OPTION_VALUE
    FROM INFORMATION_SCHEMA.DATABASE_OPTIONS s
    WHERE s.OPTION_NAME = 'default_leader'"
);
```

2021-08-10 19:54 UTC, dwsupplee commented on spanner/src/query_information_schema_database_options.php
> +        $optionName = $row['OPTION_NAME'];
Will these options always be set?

2021-08-10 19:54 UTC, dwsupplee commented on spanner/test/spannerTest.php
> +    /** @var $multiInstance Instance */
```suggestion
    /** @var Instance $multiInstance */
```

2021-08-10 20:25 UTC, dwsupplee requested changes

2021-08-10 20:25 UTC, dwsupplee commented on spanner/src/get_instance_config.php
> +function get_instance_config($instanceConfig)
The body of the method gets the leader options, which seems like a subset of the instance config. What are your thoughts on updating this to be something like get_instance_config_leader_options , or more broadly just printing out all the instance config options?

2021-08-11 02:56 UTC, hengfengli commented on spanner/src/get_instance_config.php
> +function get_instance_config($instanceConfig)
We prefer to use the current tag. The tag is same for samples across all languages. This is intended to make it more generic to avoid too many similar samples. Currently, we only need to print out the default leader. We may get more requests in the future to print out other fields.

2021-08-11 03:00 UTC, hengfengli commented on spanner/src/query_information_schema_database_options.php
> +        $optionName = $row['OPTION_NAME'];
Yes, as in the SQL query, we specified `s.OPTION_NAME` and `s.OPTION_VALUE`. If the `default_leader` option is not set, then it will not return any rows in `$results`. I don't think this would cause a key error.

2021-08-11 03:25 UTC, larkee commented on spanner/src/create_database_with_default_leader.php
> +require_once __DIR__ . '/../../testing/sample_helpers.php';
Done :)

2021-08-11 03:25 UTC, larkee commented on spanner/src/query_information_schema_database_options.php
> +    if (!$results->stats()['rowCountExact']) {
Yes. If no rows are returned then the `default_leader` must not be set.

2021-08-11 03:26 UTC, larkee commented on spanner/src/query_information_schema_database_options.php
> + * Updates the default leader of the database.
Good catch! Updated :+1:

2021-08-11 03:32 UTC, larkee commented on spanner/src/query_information_schema_database_options.php
> +        WHERE s.OPTION_NAME = 'default_leader'");
Whoops! Fixed :+1:

2021-08-11 03:32 UTC, larkee commented on spanner/test/spannerTest.php
> +    /** @var $multiInstance Instance */
Done :+1:

2021-08-12 00:26 UTC, hengfengli commented
@dwsupplee Could you please take another look? Thanks.

2021-08-12 00:44 UTC, dwsupplee approved these changes

2021-08-12 03:36 UTC, merged