chore: Upgrade remaining bigtable samples - issue #1389
GoogleCloudPlatform/php-docs-samples pull request #1496
Opened 2021-09-01 14:56 UTC by saranshdhingra

2021-09-03 12:58 UTC, saranshdhingra commented
The extra tag removed out of the 19 deleted region tags(bigtable_filters_print) isn't used in any page in the docs for any language.

2021-09-03 16:07 UTC, bshaffer reviewed
One suggestion (which applies to each sample), a few style nits, and this looks really good!

2021-09-03 16:07 UTC, bshaffer commented on bigtable/src/filter_composing_chain.php
> +        // helper function defined in https://cloud.google.com/bigtable/docs/samples/bigtable-reads-print
Nit, but let's use a complete sentence here to be absolutely crystal clear:
```suggestion
        // The "print_row" helper function is defined in https://cloud.google.com/bigtable/docs/samples/bigtable-reads-print
```

2021-09-03 16:07 UTC, bshaffer commented on bigtable/src/quickstart.php
> +
remove extra newline
```suggestion
```

2021-09-03 16:07 UTC, bshaffer commented on bigtable/src/quickstart.php
> +
Remove extra newline
```suggestion
```

2021-09-09 19:37 UTC, bshaffer approved these changes

2021-09-09 19:39 UTC, bshaffer requested changes
Just a few nits I missed

2021-09-09 19:39 UTC, bshaffer commented on bigtable/src/filter_limit_cells_per_col.php
> + * Copyright 2019 Google LLC.
The copyright years need updated on all these files!

2021-09-09 19:39 UTC, bshaffer commented on bigtable/src/filter_limit_cells_per_col.php
> +namespace Google\Cloud\Samples\Bigtable;
Namespace should go just above the region tags, to be consistent with our other samples

2021-09-09 19:39 UTC, bshaffer commented on bigtable/src/filter_limit_col_family_regex.php
> + * Create a limiting filter on a column family with a regex
nit: lets put a newline between the description and `@param` tags
```suggestion
 * Create a limiting filter on a column family with a regex
 *
```

2021-09-10 14:49 UTC, saranshdhingra commented
> Just a few nits I missed. Also, do we have a plan for the snippet bot errors?

@bshaffer 

Namespace position: Updated in all bigtable samples
Line b/w description and `@param`: Updated in all bigtable samples
Copyright year change: Changed only in the new files(read snippets, write snippets, filter files, new samples added) as I imagine it's only for new files.

The CL for the new region tag paths is ready and as soon as this PR is merged we can proceed with that like the read and write snippets splitting.

2021-09-10 15:14 UTC, bshaffer approved these changes

2021-09-10 15:15 UTC, merged