feat(storage): Turbo Replication Samples added
GoogleCloudPlatform/php-docs-samples pull request #1546
Opened 2021-10-20 15:37 UTC by saranshdhingra

Issue #1536

2021-11-29 20:45 UTC, bshaffer approved these changes
this looks great! Just a few suggestions

2021-11-29 20:45 UTC, bshaffer commented on storage/src/create_bucket_turbo_replication.php
> +    $rpo = 'ASYNC_TURBO';
Is this not a Proto constant somewhere? It seems like it should be...

2021-11-29 20:45 UTC, bshaffer commented on storage/src/set_turbo_replication_async_turbo.php
> +        'rpo' => 'ASYNC_TURBO'
maybe for consistency, set this to a `$rpo` variable like in the first example?

2021-11-29 20:45 UTC, bshaffer commented on storage/src/set_turbo_replication_default.php
> +        'rpo' => 'DEFAULT'
Same here...

2021-11-29 20:46 UTC, bshaffer commented
Looks like you have an error in your assertion: 
```
--

There was 1 failure:

1) Google\Cloud\Samples\Storage\Tests\TurboReplicationTest::testCreateBucketWithTurboReplication
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'ASYNC_TURBO'
+'DEFAULT'

/tmpfs/src/github/php-docs-samples/storage/test/TurboReplicationTest.php:62

--

```

2021-11-30 06:26 UTC, saranshdhingra commented
> Looks like you have an error in your assertion:
> 
> ```
> --
> 
> There was 1 failure:
> 
> 1) Google\Cloud\Samples\Storage\Tests\TurboReplicationTest::testCreateBucketWithTurboReplication
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'ASYNC_TURBO'
> +'DEFAULT'
> 
> /tmpfs/src/github/php-docs-samples/storage/test/TurboReplicationTest.php:62
> 
> --
> ```

Hey @bshaffer 
Thanks for the review :) 
Yes, I expect this error to stay until the library isn't released.
The [PR](https://github.com/googleapis/google-cloud-php/pull/4543) for the library is ready but still has the `Do not merge` label.

2022-01-10 22:35 UTC, ddelgrosso1 requested changes
The region tags for samples should be:

storage_create_bucket_turbo_replication
storage_get_rpo
storage_set_rpo_async_turbo
storage_set_rpo_default

2022-01-11 15:35 UTC, saranshdhingra commented on storage/src/create_bucket_turbo_replication.php
> +    $rpo = 'ASYNC_TURBO';
@dwsupplee and I discussed that in the library PR previously.
https://github.com/googleapis/google-cloud-php/pull/4543

I previously had used class constants, but then we changed it to regular strings.
Nothing in the proto though.

2022-01-13 13:04 UTC, merged