feat: add code sample and test for concatenating two input videos
GoogleCloudPlatform/php-docs-samples pull request #1574
Opened 2021-12-14 21:13 UTC by irataxy

b:197546828

2021-12-15 00:11 UTC, irataxy commented on media/transcoder/src/create_job_with_concatenated_inputs.php
> +    $startTimeInput1Nanos = (int)(1000000000 * bcsub(abs($startTimeInput1), floor(abs($startTimeInput1)), 4));
Do I need to add BCMath to `composer.json`?

2021-12-22 15:11 UTC, bshaffer commented on media/transcoder/src/create_job_with_concatenated_inputs.php
> +    $startTimeInput1Nanos = (int)(1000000000 * bcsub(abs($startTimeInput1), floor(abs($startTimeInput1)), 4));
yes, that's a good idea. Just `ext-bcmath` under the required section

2021-12-22 15:12 UTC, bshaffer reviewed
The linter needs you to fix the following things:

```diff
-    $startTimeInput1Sec = (int)floor(abs($startTimeInput1));
-    $startTimeInput1Nanos = (int)(1000000000 * bcsub(abs($startTimeInput1), floor(abs($startTimeInput1)), 4));
-    $endTimeInput1Sec = (int)floor(abs($endTimeInput1));
-    $endTimeInput1Nanos = (int)(1000000000 * bcsub(abs($endTimeInput1), floor(abs($endTimeInput1)), 4));
+    $startTimeInput1Sec = (int) floor(abs($startTimeInput1));
+    $startTimeInput1Nanos = (int) (1000000000 * bcsub(abs($startTimeInput1), floor(abs($startTimeInput1)), 4));
+    $endTimeInput1Sec = (int) floor(abs($endTimeInput1));
+    $endTimeInput1Nanos = (int) (1000000000 * bcsub(abs($endTimeInput1), floor(abs($endTimeInput1)), 4));

-    $startTimeInput2Sec = (int)floor(abs($startTimeInput2));
-    $startTimeInput2Nanos = (int)(1000000000 * bcsub(abs($startTimeInput2), floor(abs($startTimeInput2)), 4));
-    $endTimeInput2Sec = (int)floor(abs($endTimeInput2));
-    $endTimeInput2Nanos = (int)(1000000000 * bcsub(abs($endTimeInput2), floor(abs($endTimeInput2)), 4));
+    $startTimeInput2Sec = (int) floor(abs($startTimeInput2));
+    $startTimeInput2Nanos = (int) (1000000000 * bcsub(abs($startTimeInput2), floor(abs($startTimeInput2)), 4));
+    $endTimeInput2Sec = (int) floor(abs($endTimeInput2));
+    $endTimeInput2Nanos = (int) (1000000000 * bcsub(abs($endTimeInput2), floor(abs($endTimeInput2)), 4));
```

2021-12-22 15:13 UTC, bshaffer requested changes

2021-12-22 15:13 UTC, bshaffer commented on media/transcoder/README
> +PHP Fatal error:  Uncaught Error: Call to undefined function Google\Protobuf\Internal\bcsub() in /usr/local/google/home/user/github/GoogleCloudPlatform/php-docs-samples/media/transcoder/vendor/google
Your error message includes your local path to the files, and is way too specific.
```suggestion
PHP Fatal error:  Uncaught Error: Call to undefined function Google\Protobuf\Internal\bcsub()
```

2021-12-22 15:14 UTC, bshaffer commented on media/transcoder/README
> +```
as mentioned before, these samples _all_ require BC-math. So change this message to simply "you need to install the BC-Math extension" (no instructions necessary, it varies per platform and PHP version, so writing out installation instructions will do more harm than good), and add "ext-bcmath" to the required section of `composer.json`

2021-12-22 18:03 UTC, irataxy commented on media/transcoder/README
> +```
Added

2021-12-22 18:04 UTC, irataxy commented on media/transcoder/src/create_job_with_concatenated_inputs.php
> +    $startTimeInput1Nanos = (int)(1000000000 * bcsub(abs($startTimeInput1), floor(abs($startTimeInput1)), 4));
Done

2021-12-30 18:50 UTC, bshaffer approved these changes

2021-12-30 18:51 UTC, merged