Implementing sample firestore_data_get_as_custom_type
GoogleCloudPlatform/php-docs-samples pull request #1600
Opened 2022-03-02 13:55 UTC by vishwarajanand

## Background

PHP has not yet implemented any sample to show how a class can be fetched using PHP code. This sample will cover that.

## Change Summary

1. Added a new custom type which encapsulates the underlying class -> `City`.
2. Added `from_map` and `to_map` in City class.
3. Added `testGetCustomType` which can be executed and validated.

## Tests

1. The custom type class `City` and the custom type get both seem to run fine by the following command:

```
➜  firestore git:(get_as_custom_type) ✗ 
➜  firestore git:(get_as_custom_type) ✗ XDEBUG_MODE=coverage  ../testing/vendor/bin/phpunit -c phpunit.xml.dist test
PHPUnit 8.5.23 by Sebastian Bergmann and contributors.

....................S...............S...................S.        58 / 58 (100%)

Time: 2.92 minutes, Memory: 16.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 58, Assertions: 123, Skipped: 3.

Generating code coverage report in Clover XML format ... done [114 ms]
➜  firestore git:(get_as_custom_type) ✗ 
➜  firestore git:(get_as_custom_type) ✗ 

```

> Test run succeeded on local.

2022-03-03 22:30 UTC, bshaffer commented on firestore/src/City.php
> +        # [END_EXCLUDE]
what is this? Will it extend the code here from the sample? if so, why not exclude the whole function?

2022-03-03 22:30 UTC, bshaffer commented on firestore/src/data_get_as_custom_type.php
> +include 'City.php';
This is relative to the user's CWD, so make it absolute with `__DIR__`:
```suggestion
include __DIR__ . '/City.php';
```

2022-03-04 11:54 UTC, vishwarajanand commented on firestore/src/City.php
> +        # [END_EXCLUDE]
Similar to [Python equivalent](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/firestore/cloud-client/snippets.py#L136), this placeholder class function depicts how to do get a class object queries from Firestore by implementing `from_map` and `to_map` functions.

2022-03-04 11:58 UTC, vishwarajanand commented on firestore/src/City.php
> +        # [END_EXCLUDE]
Commenting the whole function could confuse developers on how a map got translated to a class object.

2022-03-07 14:30 UTC, bshaffer commented on firestore/src/City.php
> +        # [END_EXCLUDE]
That makes sense to me (although I'd prefer to just keep the function).

Can we put a comment outside the exclude to make this clear, something like...

```
// implementation of this function is excluded for brevity
```

or 

```
// implementation of fromArray goes here
```

2022-03-07 14:55 UTC, bshaffer requested changes

2022-03-07 14:55 UTC, bshaffer commented on firestore/src/City.php
> +        $regions = []
we should be using typehints for everything. Right now it's really hard to know what the types are, and which ones can be nullable. 
```suggestion
        string $name,
        string $state,
        string $country,
        bool $capital = false,
        int $population = 0,
        array $regions = []
```

2022-03-07 14:55 UTC, bshaffer commented on firestore/src/City.php
> +    public static function from_map($source)
three things here:
1. names should be camel cased
2. maps don't exist in PHP, so this should be `array`, not `map`
3. we need return types and argument type hints
```suggestion
    public static function fromArray(array $source): void
```

2022-03-07 14:55 UTC, bshaffer commented on firestore/src/City.php
> +    public function to_map()
```suggestion
    public function toArray(): array
```

2022-03-07 14:55 UTC, bshaffer commented on firestore/src/City.php
> +       )");
We usually prefer `sprintf` for something like this, to make it more readable. Also, `regions` and `capital`  require special handling because they are not strings (`population` is okay because PHP will properly cast it to a string):
```suggestion
        return sprintf(<<<EOF
Custom Type data(
    name=%s,
    country=%s,
    population=%s,
    capital=%s,
    regions=%s
)
EOF,
            $this->name,
            $this->country,
            $this->population,
            $this->captital ? 'true' : 'false', 
            implode(", ", $this->regions)
        );
```

2022-03-07 14:55 UTC, bshaffer commented on firestore/src/City.php
> +    public function __toString()
I'm a little confused why we'd expose the `__toString()` method but exclude the others. The logic here is not very interesting, so if we're excluding functions for brevity then this should be excluded. I'm guessing it makes sense in the context of the sample?

2022-03-07 14:55 UTC, bshaffer commented on firestore/test/firestoreTest.php
> +        $this->assertStringContainsString('[capital] =>', $output);
make this assert a value, and add a test for `regions`

2022-03-07 14:55 UTC, bshaffer commented on firestore/src/City.php
> +        $city->regions = $source['regions'] ?? null;
this doesn't make sense the way you're doing this... they're available in the constructor properties so we should be consistent and set them there. Also, you're using nulls instead of the types / defaults for `capital`, `population`, and `region`. This is bad because 1. you're overriding the defaults you have in the constructor, and 2. you're adding `null` types but not adding proper handling of those types in the `toString` function. This is what I think you want:
```suggestion
        $city = new City(
            $source['name'],
            $source['state'],
            $source['country'],
            $source['capital'] ?? false,
            $source['population'] ?? 0,
            $source['regions'] ?? []
        );
```

This isn't great because our default values are essentially being defined twice, but that's better than setting them to `null`. Another option would be: 
```suggestion
        $city = new City($source['name'], $source['state'], $source['country']);
        if (isset($source['capital'])) {
            $city->capital = $source['capital'];
        }
        if (isset($source['population'])) {
            $city->population = $source['population'];
        }
        if (isset($source['regions'])) {
            $city->regions = $source['regions'];
        }
```

2022-03-07 14:55 UTC, bshaffer commented on firestore/src/City.php
> +    public $regions;
These should have types as well
```suggestion
    public string $name;
    public string $state;
    public string $country;
    public bool $capital;
    public int $population;
    public array $regions;
```

2022-03-09 14:59 UTC, vishwarajanand commented on firestore/src/City.php
> +    public static function from_map($source)
Added `public static function fromArray(array $source): City`

2022-03-09 15:00 UTC, vishwarajanand commented on firestore/src/City.php
> +       )");
I wasnt used to using sprintf.. it seems v cluttered personally to me. 😅 
But I edited it since thats what we follow at Google.

2022-03-09 15:02 UTC, vishwarajanand commented on firestore/src/City.php
> +    public function __toString()
This method is actually used by tests only. I tried to mimic the python sample which also uses a similar approach, [ref link here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/firestore/cloud-client/snippets.py#L156)

2022-03-09 15:05 UTC, vishwarajanand commented on firestore/test/firestoreTest.php
> +        $this->assertStringContainsString('[capital] =>', $output);
This firestore document ([source link here](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/firestore/src/data_get_dataset.php#L42)) didnt have region field hence I had originally skipped it. Now I put it back like this:

```
        $this->assertStringContainsString('[regions] => Array', $output);
```

2022-03-09 15:08 UTC, bshaffer commented
1. The linter failed... take a look at the kokoro job to see why.
2. My suggestion to add property types was a bad one, as we are still running tests on PHP 7.3, and that syntax was added in 7.4.  So we should remove it for now (my fault).

2022-03-16 11:12 UTC, bshaffer commented on firestore/src/data_get_as_custom_type.php
> +        print_r($city);
If we added a toString function, why are we printing the object?

Im ok doing it this way, but then we should remove the toString funtion on the object because it isn't being used

2022-03-16 17:38 UTC, vishwarajanand commented on firestore/src/data_get_as_custom_type.php
> +        print_r($city);
It took a while to pinpoint that I missed the `string` cast here. I intended to use `__toString`because printing object will have to test the classpath like`Google\Cloud\Samples\Firestore\City` which might change later causing the tests to be flaky.

2022-03-16 19:29 UTC, bshaffer commented on firestore/src/data_get_as_custom_type.php
> +        print_r((string) $city);
NIT: Since it's already a string, let's just make this `print` instead of `print_r`
```suggestion
        print((string) $city);
```

2022-03-16 19:29 UTC, bshaffer commented on firestore/src/data_get_as_custom_type.php
> +        print_r($city);
That makes sense! I've added one final nit and then this'll be good to go!

2022-03-23 13:44 UTC, bshaffer approved these changes

2022-03-23 13:45 UTC, merged