Autoscaling cluster config bigtable
GoogleCloudPlatform/php-docs-samples pull request #1620
Opened 2022-05-02 13:38 UTC by vishwarajanand

## Change Summary

1. Adding samples for autoscaling Bigtable clusters: `create_cluster_autoscale_config`, `update_cluster_autoscale_config` and `disable_cluster_autoscale_config`.
2. [WIP] Adding tests for the above

## Tests summary

1. `create_cluster_autoscale_config` works successfully:
```
➜  bigtable git:(autoscaling_cluster_config_bigtable) ✗ php src/create_cluster_autoscale_config.php $GOOGLE_PROJECT_ID $GOOGLE_BIGTABLE_INSTANCE_ID "test-book-club-c2"        
Adding Cluster to Instance test-book-club
Listing Clusters:
projects/the-book-club-337319/instances/test-book-club/clusters/test-book-club-c1
Cluster created: test-book-club-c2%                                                                                                                                                                                                                              
➜  bigtable git:(autoscaling_cluster_config_bigtable) ✗ 
```

2. [WIP] `update_cluster_autoscale_config` fails:

```
➜  bigtable git:(autoscaling_cluster_config_bigtable) ✗ php src/update_cluster_autoscale_config.php $GOOGLE_PROJECT_ID $GOOGLE_BIGTABLE_INSTANCE_ID "test-book-club-c2"  1

string(262) "{"name":"projects/the-book-club-337319/instances/test-book-club/clusters/test-book-club-c2","serveNodes":1,"clusterConfig":{"clusterAutoscalingConfig":{"autoscalingLimits":{"minServeNodes":2,"maxServeNodes":5},"autoscalingTargets":{"cpuUtilizationPercent":10}}}}"

Cluster failed to update.
➜  bigtable git:(autoscaling_cluster_config_bigtable) ✗
```

3. [WIP] `disable_cluster_autoscale_config` fails:
```
➜  bigtable git:(autoscaling_cluster_config_bigtable) php src/disable_cluster_autoscale_config.php $GOOGLE_PROJECT_ID $GOOGLE_BIGTABLE_INSTANCE_ID $GOOGLE_BIGTABLE_CLUSTER_ID 1 
PHP Fatal error:  Uncaught Google\ApiCore\ApiException: {
    "message": "A non-empty 'update_mask' must be specified. Output only fields are ignored.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": "google.rpc.debuginfo-bin",
            "stackEntries": [],
            "detail": "[ORIGINAL ERROR] generic::invalid_argument: A non-empty 'update_mask' must be specified. Output only fields are ignored. [google.rpc.error_details_ext] { message: \"A non-empty \\'update_mask\\' must be specified. Output only fields are ignored.\" }"
        },
        {
            "@type": "grpc-status-details-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "grpc-server-stats-bin",
            "data": "<Unknown Binary Data>"
        }
    ]
}

  thrown in /usr/local/google/home/vishwarajanand/github/php-docs-samples/bigtable/vendor/google/gax/src/ApiException.php on line 259
➜  bigtable git:(autoscaling_cluster_config_bigtable) 
```

2022-05-10 16:15 UTC, saranshdhingra requested changes

2022-05-10 16:15 UTC, saranshdhingra commented on bigtable/src/disable_cluster_autoscale_config.php
> +    try {
Same 'spacing' changes request for this sample too.

2022-05-10 16:15 UTC, saranshdhingra commented on bigtable/src/update_cluster_autoscale_config.php
> +          // the server will silently ignore the serve nodes
```suggestion
          // the server will silently ignore the `serve_nodes` argument.
```

Will be useful to add a docs link that specifies this.

2022-05-10 16:15 UTC, saranshdhingra commented on bigtable/src/update_cluster_autoscale_config.php
> +            var_dump($error->code);
Same as sample 2?

2022-05-10 16:15 UTC, saranshdhingra commented on bigtable/test/bigtableTest.php
> +        $content .= self::runFunctionSnippet('disable_cluster_autoscale_config', [
Why do we not have the 3 sample tests in a separate function each like the other samples?

2022-05-10 16:15 UTC, saranshdhingra commented on bigtable/src/disable_cluster_autoscale_config.php
> +            printf('Cluster %s failed to update: %s.' . PHP_EOL, $clusterId, $error->message);
1. Seems like `$error->message` would be a prvt variable, can we confirm if that's not the case?
2. For consistency with let's use the getter as in sample 1.

2022-05-10 18:21 UTC, saranshdhingra commented on bigtable/src/disable_cluster_autoscale_config.php
> +    int $newNumNodes
If the only reason to use this is to set the cluster nodes as static, then instead of asking this from the user, perhaps it's best to set it to a static `1` as `$cluster->setServeNodes(1);`.
WDYT?

2022-05-11 08:45 UTC, vishwarajanand commented on bigtable/src/disable_cluster_autoscale_config.php
> +    int $newNumNodes
This parameter decides the number of notes present in the cluster after performing the update and hence the cluster capacity also. I think removing it may confuse some developers about always requiring the same `serve_nodes` constant for disabling.
To make it clearer, I have added `1` as a default parameter value.

2022-05-11 08:47 UTC, vishwarajanand commented on bigtable/src/disable_cluster_autoscale_config.php
> +            printf('Cluster %s failed to update: %s.' . PHP_EOL, $clusterId, $error->message);
Yes its my bad. 
I was using `error->getMessage()` while testing the code.. but while copy pasting it got mixed up. Also, removed the `var_dump` everywhere.

2022-05-11 08:54 UTC, vishwarajanand commented on bigtable/test/bigtableTest.php
> +        $content .= self::runFunctionSnippet('disable_cluster_autoscale_config', [
I preferred one function over three because otherwise we would have redundant functions to:
1. create & delete a cluster
2. create & update autoscaling & delete cluster
3. create & disable autoscaling & delete cluster

Compared to current:
create & update autoscaling & disable autoscaling & delete cluster

Also, by the nature of these configs, our tests will fail either way if the configs change. So, i concluded I will get sufficient coverage and with no loss on code readability.

2022-05-11 08:54 UTC, vishwarajanand commented on bigtable/src/disable_cluster_autoscale_config.php
> +            var_dump($error->code);
it was a copy paste error while submitting the diff. reverted.

2022-05-11 13:14 UTC, vishwarajanand commented on bigtable/test/bigtableTest.php
> +        $content .= self::runFunctionSnippet('disable_cluster_autoscale_config', [
After a discussion, I split the tests into multiple test methods.

2022-05-11 13:15 UTC, vishwarajanand commented on bigtable/test/bigtableTest.php
> +        $content .= self::runFunctionSnippet('disable_cluster_autoscale_config', [
Now the test commands look like this:
```
➜  bigtable git:(autoscaling_cluster_config_bigtable) ✗ XDEBUG_MODE=coverage ../testing/vendor/bin/phpunit --verbose -c phpunit.xml.dist test/bigtableTest.php --filter="testCreateProductionInstance|testUpdateClusterWithAutoscaling|testDisableAutoscalingInCluster|testCreateClusterWithAutoscaling"

PHPUnit 8.5.23 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.28 with Xdebug 3.1.2
Configuration: /usr/local/google/home/vishwarajanand/github/php-docs-samples/bigtable/phpunit.xml.dist

....                                                                4 / 4 (100%)

Time: 17.84 seconds, Memory: 10.00 MB

OK (4 tests, 5 assertions)

Generating code coverage report in Clover XML format ... done [283 ms]
➜  bigtable git:(autoscaling_cluster_config_bigtable) ✗ 
➜  bigtable git:(autoscaling_cluster_config_bigtable) ✗
```

2022-05-19 09:24 UTC, vishwarajanand commented
Note: Tests seem to be failing due to `DEADLINE_EXCEEDED` here but pass in my local.

2022-06-06 13:01 UTC, saranshdhingra approved these changes
LGTM

2022-06-06 13:03 UTC, merged