feat: samples for dual region bucket creation
GoogleCloudPlatform/php-docs-samples pull request #1659
Opened 2022-07-14 18:30 UTC by vishwarajanand

Fixing sample for dual region bucket creation

Fixes: 
https://github.com/googleapis/google-cloud-php/issues/5313
and
https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1645

# Tests

```
php-docs-samples/storage % php src/create_bucket_dual_region.php 'samples-create-bucket-dual-region-xyz12321' 'US' 'US-EAST1' 'US-WEST1'
Created dual-region bucket 'samples-create-bucket-dual-region-xyz12321' in 'US-EAST1+US-WEST1'
php-docs-samples/storage %
```

Shows up as:
<img width="658" alt="Screenshot 2022-07-14 at 23 59 41" src="https://user-images.githubusercontent.com/7369612/179056378-6b71cabe-ca42-41d2-9fb7-e6e842c7aa53.png">

2022-07-14 20:18 UTC, danielbankhead requested changes
Looks good so far, a couple of items to address

2022-07-14 20:18 UTC, danielbankhead commented on storage/src/create_bucket_dual_region.php
> +    printf("Created dual-region bucket '%s' in '%s+%s'", $bucket->name(), $region1, $region2);
This should be `${bucket.name} created in '${region1}' and '${region2}'`;

2022-07-14 20:18 UTC, danielbankhead commented on storage/test/storageTest.php
>          $this->assertTrue($exists);
As 'us' alone is a valid location (e.g. if `customPlacementConfig` isn't passed to the API a valid bucket would be created), the bucket's `customPlacementConfig` and `locationType` metadata fields should checked.

See for example: https://github.com/googleapis/nodejs-storage/blob/91aeab6aec7a8aea5122590edfaed6e87d8cb639/samples/system-test/buckets.test.js#L238-L246

2022-07-15 04:48 UTC, vishwarajanand commented on storage/test/storageTest.php
>          $this->assertTrue($exists);
@danielbankhead  I did add a check to that. But I dont see `customPlacementConfig` in the metadata of bucket hence created. Are you using any other API for this purpose?

## HTTP call to get metadata
<img width="597" alt="Screenshot 2022-07-15 at 09 51 57" src="https://user-images.githubusercontent.com/7369612/179152679-72dc9794-e7f0-4adf-8466-72399eef1458.png">


## Response

<img width="513" alt="Screenshot 2022-07-15 at 09 47 09" src="https://user-images.githubusercontent.com/7369612/179152607-e74ac823-fb12-4c4e-b22c-67bba0d6694b.png">

2022-07-15 04:49 UTC, vishwarajanand commented on storage/src/create_bucket_dual_region.php
> +    printf("Created dual-region bucket '%s' in '%s+%s'", $bucket->name(), $region1, $region2);
I am too lazy 🥇

2022-07-15 04:53 UTC, vishwarajanand commented
Reviewers, pls ignore the `/bigquery/*` changes.. it should not show once my other PR is merged. I accidently pushed it. 💾

2022-07-15 05:19 UTC, danielbankhead commented on storage/test/storageTest.php
>          $this->assertTrue($exists);
Yes. That’s expected as it needs to be implemented in PHP (per https://github.com/googleapis/google-cloud-php/issues/5313#issuecomment-1184808024).

Review the initial issue request.

2022-07-15 06:48 UTC, vishwarajanand commented on storage/test/storageTest.php
>          $this->assertTrue($exists);
Yes, even if I make the change per https://github.com/googleapis/google-cloud-php/issues/5313 it might not show up immediately unless we have a release. Are you asking each client library to make a release?
(not mentioned in [go/gcs-dpe-dual-region-milestones-api-refactor](http://go/gcs-dpe-dual-region-milestones-api-refactor))

2022-07-15 21:02 UTC, vishwarajanand commented on storage/test/storageTest.php
>          $this->assertTrue($exists);
I have fixed it, but I think I will still need to bump up the client library version in `composer.json` for this to appropriately work. Will do as needed.

2022-07-16 00:28 UTC, bshaffer commented
This looks great,  but we should wait to release it until the feature rolls out

2022-07-16 00:54 UTC, danielbankhead commented
> This looks great, but we should wait to release it until the feature rolls out

We actually need this for the GA release (documentation on c.g.c); current customers shouldn’t be affected.

See internal coordination details here: [go/gcs-dpe-dual-region-milestones-api-refactor](http://go/gcs-dpe-dual-region-milestones-api-refactor)

2022-07-19 20:37 UTC, bshaffer commented
@danielbankhead @vishwarajanand happy to merge this as soon as the tests are passing. If you can whitelist our test projects then this should be good to go

2022-07-20 11:36 UTC, vishwarajanand commented
@bshaffer it seems `php-docs-samples-kokoro<X>` where our tests run are already allowlisted [ref](https://source.corp.google.com/piper///depot/google3/configs/cloud/bigstore/override-prod.gcl;l=176-185), but I still cant see any `customPlacementConfig` in the metadata when I create the bucket.

Not quite sure whats happening inside.

2022-07-29 16:11 UTC, bshaffer approved these changes

2022-07-29 16:11 UTC, merged