feat(storage): sample for autoclass
GoogleCloudPlatform/php-docs-samples pull request #1685
Opened 2022-09-04 08:18 UTC by vishwarajanand

Addresses: https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1682
(couldn't test in local, since feature not enabled)

2022-09-05 13:07 UTC, vishwarajanand commented on storage/src/create_bucket_autoclass.php
> +    $location = 'ASIA';
May need to change this, since the feature is geo restricted in Oct. Will check and confirm.

2022-09-19 10:22 UTC, saranshdhingra requested changes

2022-09-19 10:22 UTC, saranshdhingra commented on storage/src/create_bucket_autoclass.php
> +function create_bucket_autoclass($bucketName)
```suggestion
function create_bucket_autoclass(string $bucketName): void
{
```

2022-09-19 10:22 UTC, saranshdhingra commented on storage/src/create_bucket_autoclass.php
> +    // $bucketName = 'my-bucket';
Super nit, but I think when the arguments don't have a default, let's not include these comments.

Even if the user uncomments these, they still won't be able to run these samples without modifying the code to either remove the argument from the function definition, or add a default.

2022-09-19 10:22 UTC, saranshdhingra commented on storage/src/get_bucket_autoclass.php
> +function get_bucket_autoclass($bucketName)
Func definition changes like sample 1.

2022-09-19 10:22 UTC, saranshdhingra commented on storage/src/set_bucket_autoclass.php
> +    // $toggle = false;
Remove this if not needed, or add a default in the function definition.
If you end up adding a default, then probably `$autoclassStatus` or `$status` would be better suited?

2022-09-19 10:22 UTC, saranshdhingra commented on storage/test/storageTest.php
> +        $output = self::runFunctionSnippet('create_bucket_autoclass', [
If there are indeed 3 samples, I think they should be called separately in separate tests.

Also, to verify `create_ bucket_autoclass` we don't really need to call `get_bucket_autoclass`.

The test should only be the existence of `Created bucket %s in %s with autoclass enabled` in the `$output`.

2022-09-19 10:22 UTC, saranshdhingra commented on storage/src/create_bucket_autoclass.php
> +# [START storage_create_autoclass]
I didn't find this region tag in the internal doc or the github issue attached. Do we need this sample?

2022-09-19 22:56 UTC, bshaffer commented on storage/src/create_bucket_autoclass.php
> +function create_bucket_autoclass($bucketName)
+1

2022-09-21 05:29 UTC, vishwarajanand commented on storage/test/storageTest.php
> +        $output = self::runFunctionSnippet('create_bucket_autoclass', [
@cojenco confirmed with tech writing team that create sample isn't needed. So I removed them.

2022-09-21 05:30 UTC, vishwarajanand commented on storage/src/create_bucket_autoclass.php
> +# [START storage_create_autoclass]
Removed now after confirmation from tech writing team.

2022-09-21 06:05 UTC, vishwarajanand commented on storage/src/create_bucket_autoclass.php
> +    // $bucketName = 'my-bucket';
Nide suggestion, I am curious why don't we follow this convention across samples?
For now, I am inclined to keep it this way. Because adding a default value will be different from other samples, so it might look odd one out on cdc page. Also it will print an exception for users who re-run the sample, without providing the actual way to run it.

But I am open to discuss and convert all samples to the default param values if needed.

2022-09-23 00:25 UTC, bshaffer commented on storage/src/get_bucket_autoclass.php
> +
nit: remove extra newline
```suggestion
```

2022-09-23 00:25 UTC, bshaffer commented on storage/src/get_bucket_autoclass.php
> +
I would rather put. this in the parameter description, for example:

```
 * @param string $bucketName The name of your Cloud Storage bucket (e.g. 'my-bucket')
```

But I am not super opinionated on it!

2022-09-23 00:25 UTC, bshaffer commented on storage/src/set_bucket_autoclass.php
> +
```suggestion
```

2022-09-23 00:25 UTC, bshaffer commented on storage/test/storageTest.php
> +                true
I think the `true` is here by accident
```suggestion
                $bucket->name()
```

2022-09-23 21:29 UTC, cojenco commented on storage/src/set_bucket_autoclass.php
> +    // $autoclassStatus = true;
Could we instead **disable** Autoclass in this sample with `$autoclassStatus = false`?
As previously discussed, users can disable Autoclass on an existing bucket upon our 1st launch in Oct (unfortunately not the same case for enabling the feature on an existing bucket...) 

For a better user experience, I'd suggest to set bucket autoclass to false in this sample. Otherwise, looking good. Thanks @vishwarajanand for adding these samples.

2022-09-25 17:00 UTC, vishwarajanand commented on storage/src/set_bucket_autoclass.php
> +    // $autoclassStatus = true;
I changed the comment to false and also in tests, I reflected this change.

2022-09-25 17:03 UTC, vishwarajanand commented on storage/src/get_bucket_autoclass.php
> +
Very similar to Saransh's comment https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1685#discussion_r974079050, do you think we should remove comments like this from all samples to instead have them as default params or as `(e.g. '<value>')`.

I am hesitating because all other samples are written with such comments and a PHP user will be confused while reading samples on cgc page. Thoughts?

2022-09-27 08:26 UTC, saranshdhingra commented on storage/src/create_bucket_autoclass.php
> +    // $bucketName = 'my-bucket';
Just to clarify, wasn't asking to put a default, I was just saying that uncommenting this line doesn't help for the user.

Regarding why other samples have it, we did have an old format for these samples before, where we didn't used to wrap everything in a function. Probably left overs from them.

I'd say let's not include this for any new samples we do and let's create a task to remove these from the existing samples as well.

2022-09-27 10:28 UTC, vishwarajanand commented on storage/src/create_bucket_autoclass.php
> +    // $bucketName = 'my-bucket';
Added a task to clear samples with commented values. b/249236170

2022-10-21 07:33 UTC, vishwarajanand commented
Update: To be merged in the first week of Nov.

2022-11-01 21:04 UTC, cojenco approved these changes
Thanks for working on the samples. Deferring to @saranshdhingra for further review

2022-11-01 21:04 UTC, cojenco commented on storage/src/set_bucket_autoclass.php
> + *
Could we add a comment here to emphasize that currently v1 Autoclass can only be enabled upon bucket creation? Otherwise, LGTM

```
# Note: Only patch requests that disable autoclass are currently supported.
# To enable autoclass, you must set it at bucket creation time.
```

2022-11-02 18:30 UTC, vishwarajanand commented on storage/src/set_bucket_autoclass.php
> + *
Done :-)

2022-11-08 16:32 UTC, saranshdhingra approved these changes

2022-11-08 16:32 UTC, merged