Add sample for add and drop database roles for Spanner
GoogleCloudPlatform/php-docs-samples pull request #1689
Opened 2022-09-26 05:58 UTC by ajupazhamayil

This PR creates a sample for Spanner database role add and drop.

2022-09-26 07:51 UTC, ajupazhamayil commented on spanner/src/add_and_drop_database_role.php
> +
Let me open in VS Code and see, Vim was showing in a different way!

2022-09-26 08:15 UTC, ajupazhamayil commented on spanner/src/add_and_drop_database_role.php
> +
Great, Now the lint issue is gone, thank you for the suggestion!

2022-09-26 08:28 UTC, ajupazhamayil commented
rerun tests please

2022-09-26 08:37 UTC, ajupazhamayil commented
kokoro:force-run

2022-09-27 11:01 UTC, saranshdhingra requested changes

2022-09-28 11:21 UTC, ajupazhamayil commented on spanner/src/add_and_drop_database_role.php
> +    $role_parent = 'new_parent';
Done

2022-09-28 11:21 UTC, ajupazhamayil commented on spanner/src/add_and_drop_database_role.php
> +        'CREATE ROLE ' . $role_parent,
Done

2022-09-28 12:06 UTC, ajupazhamayil commented on spanner/test/spannerTest.php
> +    /**
Sounds good to me, Done!

2022-09-28 12:08 UTC, saranshdhingra requested changes

2022-09-28 12:08 UTC, saranshdhingra commented on spanner/src/add_and_drop_database_role.php
> +    print(sprintf('Waiting for revoke role and drop role operation to complete... %s', PHP_EOL));
No need for a `printf(sprintf())` call, simply calling printf will work.

2022-09-28 12:08 UTC, saranshdhingra commented on spanner/src/add_and_drop_database_role.php
> +    printf(sprintf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL));
Same as above

2022-09-28 13:19 UTC, saranshdhingra commented on spanner/src/add_and_drop_database_role.php
> +function add_and_drop_database_role($instanceId, $databaseId)
```suggestion
function add_and_drop_database_role(string $instanceId, string $databaseId): void
```

Reference: https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/spanner/src/pg_create_database.php#L36

2022-09-28 13:20 UTC, saranshdhingra commented on spanner/src/add_and_drop_database_role.php
> +function add_and_drop_database_role($instanceId, $databaseId)
nit: Probably can remove `and` from the file name and the method.

2022-09-28 16:44 UTC, ajupazhamayil commented on spanner/src/add_and_drop_database_role.php
> +    print(sprintf('Waiting for revoke role and drop role operation to complete... %s', PHP_EOL));
Done

2022-09-28 16:44 UTC, ajupazhamayil commented on spanner/src/add_and_drop_database_role.php
> +    printf(sprintf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL));
Done

2022-09-28 17:04 UTC, bshaffer commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
Having this in one sample is strange.... it would typically look like two samples, one to add and one to drop. I assume the sample is set up this way across languages, but if there's wiggle-room here, I'd much rather see this as two separate samples.

2022-09-28 17:28 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
I was following the Ruby style here (ref: https://devrel.corp.google.com/snippets/spanner_add_and_drop_database_role?t=ruby)

But if it is the right way, we can make it two samples. What do you think?

2022-10-02 18:57 UTC, vishwarajanand commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
I agree with Brent. We follow one usecase per sample, in this repo and in cgc page.
@ajupazhamayil  can you pls split this to two files? I am not sure of the region tag though, I see there are no published samples by this tag too.

2022-10-03 09:18 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
Thats the same region tag from the ruby file I mentioned above...

2022-10-03 10:29 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
Let me check with the owner of the ruby file/ region tag and get back here the reason behind it

2022-10-03 12:36 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
This Sample comes with respect tho FGAC Doc here: https://docs.google.com/document/d/17vh8nazkkdiZBJ8D7PjGFZuTR1Amwp3-F8o50AnuFMc/edit#heading=h.tw0d3ze7x5dx
Got it from Ruby team

2022-10-04 12:02 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
Relevant comment: https://docs.google.com/document/d/17vh8nazkkdiZBJ8D7PjGFZuTR1Amwp3-F8o50AnuFMc/edit?disco=AAAAhYbMvBI

2022-10-05 05:55 UTC, vishwarajanand commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped roles %s and %s %s', $roleChild, $roleParent, PHP_EOL);
@bshaffer per the discussion with SWE, it seems this particular sample is planned to be used in documentation (together not separated).

2022-10-05 05:56 UTC, vishwarajanand approved these changes
LGTM

2022-10-18 19:02 UTC, vishwarajanand approved these changes

2022-10-19 07:04 UTC, vishwarajanand commented
Since this sample is not yet published, I am merging this change.

2022-11-22 10:44 UTC, saranshdhingra approved these changes
LGTM

2022-11-22 10:44 UTC, merged