[Storage][Sample] Get bucket class and location
GoogleCloudPlatform/php-docs-samples pull request #1690
Opened 2022-09-27 06:21 UTC by yash30201

Wrote a sample and its test for fetching and displaying the bucket's storage class and location.

2022-09-27 08:27 UTC, saranshdhingra requested changes

2022-09-27 08:27 UTC, saranshdhingra commented on storage/test/storageTest.php
> +        $output = $this->runFunctionSnippet('get_bucket_class_and_location', [$bucketName]);
This needs to be called in a different test method itself.
You can use PHPunit's `@depends` annotation if you need a bucket created.

2022-09-27 08:27 UTC, saranshdhingra commented on storage/test/storageTest.php
> +        $this->assertStringContainsString("Bucket: $bucketName, storage class: " . $bucketInfo['storageClass'] . ', location: ' . $bucketInfo['location'], $output);
```suggestion
        $this->assertStringContainsString(sprintf('Bucket: %s, storage class: %s, location: %s', $bucketName, $bucketInfo['storageClass'], $bucketInfo['location']) $output);
```

2022-09-27 08:27 UTC, saranshdhingra commented on storage/src/get_bucket_class_and_location.php
> +    // $bucketName = 'my-bucket';
We are discussing removing this in another PR, my nit suggestion would be to remove this comment.

2022-09-27 13:02 UTC, vishwarajanand commented on storage/src/get_bucket_class_and_location.php
> +    printf('Bucket: %s, storage class: %s, location: %s' . PHP_EOL, $info['name'], $info['storageClass'], $info['location']);
Break into multiple lines if exceeding 80 chars?

2022-09-28 05:19 UTC, yash30201 commented on storage/src/get_bucket_class_and_location.php
> +    // $bucketName = 'my-bucket';
Removed that. Marking this as resolved.

2022-09-28 05:19 UTC, yash30201 commented on storage/test/storageTest.php
> +        $this->assertStringContainsString(sprintf('Bucket: %s, storage class: %s, location: %s' . PHP_EOL, $bucketInfo['name'], $bucketInfo['storageClass'], $bucketInfo['location']), $output);
Done

2022-09-28 05:19 UTC, yash30201 commented on storage/src/get_bucket_class_and_location.php
> +    printf('Bucket: %s, storage class: %s, location: %s' . PHP_EOL, $info['name'], $info['storageClass'], $info['location']);
Apllied this everywhere required

2022-09-28 12:15 UTC, saranshdhingra reviewed
LGTM, but need to fix the CLA issue

2022-11-07 05:44 UTC, vishwarajanand commented on storage/test/storageTest.php
> +          [self::$tempBucket->name()],
Convert to 4 spaces.

2022-11-07 05:44 UTC, vishwarajanand commented on storage/test/storageTest.php
> +          $bucketInfo['location'],
Convert to 4 spaces

2022-11-07 05:45 UTC, vishwarajanand requested changes
LGTM
nits on formatting

2022-11-10 09:58 UTC, vishwarajanand approved these changes

2022-11-10 09:58 UTC, merged