Add Spanner read write retry sample
GoogleCloudPlatform/php-docs-samples pull request #1694
Opened 2022-09-28 11:13 UTC by ajupazhamayil

This PR create a sample for maxRetry option in runTransaction

2022-09-30 09:24 UTC, saranshdhingra requested changes

2022-09-30 09:24 UTC, saranshdhingra commented on spanner/src/read_write_retry.php
> + * too low, it will raise an exception.
```suggestion
```

2022-09-30 09:24 UTC, saranshdhingra commented on spanner/src/read_write_retry.php
> +    // Variable to set max number of retries in the event of AbortedException
```suggestion
```

The var is self explanatory.

2022-09-30 09:24 UTC, saranshdhingra commented on spanner/src/read_write_retry.php
> +    }, array('maxRetries' => $maxRetries));
```suggestion
    }, ['maxRetries' => $maxRetries]);
```

2022-09-30 09:24 UTC, saranshdhingra commented on spanner/test/spannerTest.php
> +        $this->runFunctionSnippet('update_data');
Don't need to run this as this test already depends on `testUpdateData`.

2022-09-30 09:24 UTC, saranshdhingra commented on spanner/src/read_write_retry.php
> +        $transferAmount = 200000;
I wonder if we could have a simpler sample?
In this sample the user has to spend more time in understanding the business logic rather than how to use the `maxRetries` option. WDYT?

2022-10-03 09:16 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> +        $transferAmount = 200000;
I think it make sense for me to change to something simpler, will work on that...

2022-10-03 14:00 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> + * too low, it will raise an exception.
Done

2022-10-03 14:01 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> +    // Variable to set max number of retries in the event of AbortedException
Sounds good, Removed, thank you!

2022-10-03 14:02 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> +    }, array('maxRetries' => $maxRetries));
Done, Thank you!

2022-10-03 14:25 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> +        $transferAmount = 200000;
Done, Changed the sample to a simple read from a record and update the value to the second the record.

2022-10-03 14:30 UTC, ajupazhamayil commented on spanner/test/spannerTest.php
> +        $this->runFunctionSnippet('update_data');
you are right, thank you!

2022-11-15 10:45 UTC, vishwarajanand commented on spanner/src/read_write_retry.php
> + * ```
Did you mean to `update_data` in the Example?

2022-11-15 10:45 UTC, vishwarajanand commented on spanner/src/read_write_retry.php
> +
Can be removed

2022-11-15 10:46 UTC, vishwarajanand commented on spanner/src/read_write_retry.php
> +        // Read the second album's budget.
Extra line in between?

2022-11-15 10:46 UTC, vishwarajanand commented on spanner/src/read_write_retry.php
> +
Remove this line too?

2022-11-15 10:49 UTC, vishwarajanand approved these changes
LGTM, pls do extra new line removals before merge.

2022-11-15 13:04 UTC, saranshdhingra approved these changes
LGTM after Anand's comments are sorted/replied.

2022-11-22 12:37 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> +
Done

2022-11-22 12:38 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> + * ```
Yes, We need to run the update_data sample to have the second album's budget

2022-11-22 12:47 UTC, vishwarajanand commented on spanner/src/read_write_retry.php
> +    $maxRetries = 5;
Consider reducing this.
```suggestion
    $maxRetries = 2;
```

2022-11-22 13:19 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> +    $maxRetries = 5;
I will change that to 2

2022-11-22 14:10 UTC, ajupazhamayil commented on spanner/src/read_write_retry.php
> +    $maxRetries = 5;
Changed

2022-11-22 16:11 UTC, merged