feat: add new sample for analytics data
GoogleCloudPlatform/php-docs-samples pull request #1707
Opened 2022-10-06 22:05 UTC by anweshan

Adds sample for analytics data v1beta run_report with aggregations

2022-10-19 17:21 UTC, ikuleshov approved these changes

2022-10-19 18:06 UTC, bshaffer requested changes

2022-10-19 18:06 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +*/
```suggestion
 * Google Analytics Data API sample application demonstrating the usage of
 * metric aggregations in a report.
 * See https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport#body.request_body.FIELDS.metric_aggregations
 * for more information.
 * Usage:
 *   composer update
 *   php run_report_with_aggregations.php YOUR-GA4-PROPERTY-ID
 */
```

2022-10-19 18:06 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +
needs PHPDoc
```suggestion
/**
 * @param string $propertyId
 */
```

2022-10-19 18:06 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +function printRunReportResponseWithAggregations($response)
Needs PHPDoc and typehint
```suggestion
/**
 * @param RunReportResponse $response
 */
function printRunReportResponseWithAggregations(RunReportResponse $response)
```

2022-10-19 18:07 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +function printRunReportResponseWithAggregations($response)
This also will require an import at the top for `RunReportResponse`

2022-10-28 21:29 UTC, anweshan commented
@bshaffer the changes were made

2022-12-14 21:54 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +        ]
fix whitespace
```suggestion
        'metricAggregations' => [
            MetricAggregation::TOTAL,
            MetricAggregation::MAXIMUM,
            MetricAggregation::MINIMUM
        ]
```

2022-12-14 21:54 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +        printf('Metric header name: %s (%s)%s', $metricHeader->getName(), MetricType::name($metricHeader->getType()), PHP_EOL);
more readable format:
```suggestion
        printf(
            'Metric header name: %s (%s)' . PHP_EOL,
            $metricHeader->getName(),
            MetricType::name($metricHeader->getType())
        );
```

2022-12-14 21:54 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +        . ' ' . $row->getMetricValues()[0]->getValue() . PHP_EOL;
nit but more readable formatting
```suggestion
        printf(
            '%s %s' . PHP_EOL,
            $row->getDimensionValues()[0]->getValue()
            $row->getMetricValues()[0]->getValue()
        );
```

2022-12-14 21:54 UTC, bshaffer commented on analyticsdata/src/run_report_with_aggregations.php
> +        )],
This is a little hard to follow. I might suggest breaking these into variables, such as
```php
$dimension = new Dimension(['name' => 'country']);
$metric = new Metric(['name' => 'sessions']);
$dateRange = (new DateRange())->setStartDate('365daysago')->setEndDate('today');
$metricAggregations = [
    MetricAggregation::TOTAL,
    MetricAggregation::MAXIMUM,
    MetricAggregation::MINIMUM
];
$response = $client->runReport([
    'property' => 'properties/' . $propertyId,
    'dimensions' => [$dimension],
    'metrics' => [$metric],
    'dateRanges' => [$dateRange],
]);
````

```

2022-12-14 21:54 UTC, bshaffer commented on analyticsdata/test/analyticsDataTest.php
> +        $this->assertRegExp('/Report result/', $output);
can we assert something more than just this? This is thin coverage for all the logic happening in the print test

2022-12-15 00:04 UTC, anweshan commented on analyticsdata/test/analyticsDataTest.php
> +        $this->assertRegExp('/Report result/', $output);
The purpose of the test is simply to test that the parameters used in the sample are indeed a valid query to analytics, rather than testing the logic of the analytics query itself. There isn't any static test data that exists that could test for example, that with the metric aggregations total, maximum, minimum that the report would look a certain way. But if all the parameters are valid syntax, the report will at least run and print out "Report result"

Also, the purpose of the analytics samples is to create samples representing different endpoints in consistency with the analytics samples for other languages such as Python, NodeJS, Java - where the tests also similarly test if the query runs and prints out Report Result, so we don't want inconsistency between the tests for samples

While I agree as a long term goal it would be great to create a static dataset that could be used for more comprehensive tests, as a minimum since it's just sample code, it's important to test that there aren't any typos/incorrect syntax, and that the report itself runs a valid query.

2022-12-16 21:57 UTC, bshaffer commented on analyticsdata/test/analyticsDataTest.php
> +        $this->assertRegExp('/Report result/', $output);
That seems fair to me, although I still think it'd be better to add a few more assertions, such as:

```php
$this->assertStringContainsString('rows received', $output);
$this->assertStringContainsString('Dimension header name:', $output);
$this->assertStringContainsString('Metric header name:', $output);
$this->assertStringContainsString('ReportResult:', $output);
```

2022-12-22 22:08 UTC, bshaffer approved these changes

2022-12-22 22:09 UTC, merged