chore(storage) Remove commented defaults for arguments in Storage samples
GoogleCloudPlatform/php-docs-samples pull request #1715
Opened 2022-10-26 08:08 UTC by ajupazhamayil

This PR is related to the comment https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1685#discussion_r974079050

2022-10-26 12:14 UTC, ajupazhamayil commented
Total number of files in the src of Storage = 110
Total number of files changed = 106

Four unchanged files are:

1. generate_encryption_key.php
2. list_buckets.php
3. print_bucket_default_acl.php
4. print_bucket_website_configuration.php

2022-10-26 12:23 UTC, ajupazhamayil commented
This PR used a script in the repository: https://github.com/ajupazhamayil/function_default_comment_remover

2022-10-26 16:32 UTC, bshaffer commented on storage/src/remove_bucket_conditional_iam_binding.php
> -    // $expression = 'resource.name.startsWith("projects/_/buckets/bucket-name/objects/prefix-a-")';
Personally I think these are helpful as they are not hurting anything. I know the previous maintainers felt strongly about having example values supplied _somewhere_, so if not here, we should put them somewhere else.

2022-10-27 03:04 UTC, vishwarajanand commented on storage/src/add_bucket_acl.php
> -    // $bucketName = 'my-bucket';
The docblock before the function is supposed to capture the suggested value at the end. Such as:
`(e.g. 'my-bucket')`

2022-10-27 03:05 UTC, vishwarajanand requested changes
Need to change the docblocks accordingly.

2022-10-27 05:27 UTC, ajupazhamayil commented on storage/src/add_bucket_acl.php
> -    // $bucketName = 'my-bucket';
Will do this way!

2022-10-27 05:28 UTC, ajupazhamayil commented on storage/src/remove_bucket_conditional_iam_binding.php
> -    // $expression = 'resource.name.startsWith("projects/_/buckets/bucket-name/objects/prefix-a-")';
@bshaffer Thank you for the suggestion, As @vishwarajanand suggested, we can add it to the parameter comment section itself. Example:

```
 /*
 * @param string $projectId The ID of your Google Cloud Platform project (e.g. 'my-project-id').
 * @param string $accessId Access ID for an inactive HMAC key (e.g. 'GOOG0234230X00').
 */
```

2022-10-27 05:46 UTC, ajupazhamayil commented
Great, will change according to the comments, moved the PR to draft, will make it open after the changes, thank you all!

2022-10-27 14:00 UTC, vishwarajanand commented on storage/src/remove_bucket_conditional_iam_binding.php
> + * @param string $expression Te condition specified in CEL expression language. (e.g. 'resource.name.startsWith("projects/_/buckets/bucket-name/objects/prefix-a-")')
Too long, break into two sentences?

2022-10-27 14:02 UTC, vishwarajanand commented on storage/src/remove_bucket_conditional_iam_binding.php
> + * @param string $expression Te condition specified in CEL expression language. (e.g. 'resource.name.startsWith("projects/_/buckets/bucket-name/objects/prefix-a-")')
Usually we try to break sentences once it's way more than 80 chars.

2022-10-27 14:06 UTC, vishwarajanand commented on storage/src/rotate_encryption_key.php
> + * @param string $newBase64EncryptionKey The new base64 encoded encryption key. (e.g. '0mMWhFvQOdS4AmxRpo8SJxXn5MjFhbz7DkKBUdUIef8=')
This may also need to be broken into multiple lines like this:

```suggestion
 * @param string $newBase64EncryptionKey The new base64 encoded encryption key.
          (e.g. '0mMWhFvQOdS4AmxRpo8SJxXn5MjFhbz7DkKBUdUIef8=')
```

2022-10-27 14:23 UTC, vishwarajanand commented on storage/src/remove_bucket_conditional_iam_binding.php
> + * @param string $expression Te condition specified in CEL expression language. (e.g. 'resource.name.startsWith("projects/_/buckets/bucket-name/objects/prefix-a-")')
May need a change here: [ref](https://github.com/ajupazhamayil/function_param_example_comment_remover/blob/main/function_param_example_comment_remover.py#L52)

2022-11-02 07:17 UTC, vishwarajanand approved these changes
LGTM

2022-11-03 10:30 UTC, merged