feat(Spanner): DML returning samples
GoogleCloudPlatform/php-docs-samples pull request #1721
Opened 2022-11-14 08:39 UTC by yash30201

Samples showcasing how to use dml returning feature in spanner using php client library.

2022-11-15 10:40 UTC, saranshdhingra requested changes

2022-11-15 10:40 UTC, saranshdhingra commented on spanner/src/delete_dml_returning.php
> +            'Row (%s, %s, %s) deleted\n' . PHP_EOL,
```suggestion
            'Row (%s, %s, %s) deleted' . PHP_EOL,
```

Can you remove it from other samples too?

2022-11-15 10:40 UTC, saranshdhingra commented on spanner/src/delete_dml_returning.php
> + * Delete data from the given database using DML returning feature.
```suggestion
 * Delete data from the given database using DML returning.
```

nit: Can you please remove the word 'feature' from other samples too?

2022-11-15 10:40 UTC, saranshdhingra commented on spanner/test/spannerPgTest.php
> +        $this->assertStringContainsString('Melissa', $output);
These assertions should check for the whole line that was used in `printf`.

2022-11-15 11:06 UTC, yash30201 commented on spanner/src/delete_dml_returning.php
> +            'Row (%s, %s, %s) deleted\n' . PHP_EOL,
Thanks, fixed in [de8e44b](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1721/commits/de8e44bd199f023ac080a6a21e409e6d98943f58).

2022-11-15 11:06 UTC, yash30201 commented on spanner/test/spannerPgTest.php
> +        $this->assertStringContainsString('Melissa', $output);
Thanks, fixed in [de8e44b](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1721/commits/de8e44bd199f023ac080a6a21e409e6d98943f58)

2022-11-15 11:06 UTC, yash30201 commented on spanner/src/delete_dml_returning.php
> + * Delete data from the given database using DML returning feature.
Thanks, fixed in [de8e44b](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1721/commits/de8e44bd199f023ac080a6a21e409e6d98943f58)

2022-11-21 08:22 UTC, saranshdhingra commented on spanner/src/update_dml_returning.php
> +        'UPDATE Singers SET LastName = @lastName WHERE SingerId = @singerId THEN RETURN *',
nit: Split this.

2022-11-21 11:42 UTC, yash30201 commented on spanner/src/update_dml_returning.php
> +        'UPDATE Singers SET LastName = @lastName WHERE SingerId = @singerId THEN RETURN *',
Fixed

2022-11-21 17:06 UTC, saranshdhingra approved these changes

2022-11-21 17:07 UTC, merged