feat: add Video Stitcher samples and tests
GoogleCloudPlatform/php-docs-samples pull request #1727
Opened 2022-11-22 21:24 UTC by irataxy

b:202972981

Part 2 of 4: CDN keys (see https://cloud.google.com/video-stitcher/docs/how-to/managing-cdn-keys)

2022-12-07 20:48 UTC, bshaffer requested changes
Everything looks good other than the whitespace. I've also added a request to refactor the tests. Please let me know if you have any questions and I can provide more guidance!

2022-12-07 20:48 UTC, bshaffer commented on media/videostitcher/src/create_cdn_key.php
> + *  create a Cloud CDN key.
nit:
```suggestion
 * @param string  $privateKey         For a Media CDN key, this is a 64-byte Ed25519 private
 *                                    key encoded as a base64-encoded string. For a Cloud CDN key,
 *                                    this is a base64-encoded string secret.
 * @param boolean $isMediaCdn         If true, create a Media CDN key. If false,
 *                                    create a Cloud CDN key.
```

2022-12-07 20:48 UTC, bshaffer commented on media/videostitcher/src/create_cdn_key_akamai.php
> + * the Akamai CDN edge configuration
nit
```suggestion
 * @param string  $tokenKey           The base64-encoded string token key for
 *                                    the Akamai CDN edge configuration
```

2022-12-07 20:48 UTC, bshaffer commented on media/videostitcher/src/update_cdn_key.php
> + *  update a Cloud CDN key.
```suggestion
 * @param string  $privateKey         For a Media CDN key, this is a 64-byte Ed25519 private
 *                                    key encoded as a base64-encoded string. For a Cloud CDN key,
 *                                    this is a base64-encoded string secret.
 * @param boolean $isMediaCdn         If true, update a Media CDN key. If false,
 *                                    update a Cloud CDN key.
```

2022-12-07 20:48 UTC, bshaffer commented on media/videostitcher/src/update_cdn_key_akamai.php
> + * the Akamai CDN edge configuration
```suggestion
 * @param string  $tokenKey           The base64-encoded string token key for
 *                                    the Akamai CDN edge configuration
```

2022-12-07 20:48 UTC, bshaffer commented on media/videostitcher/test/videoStitcherTest.php
> +        $this->assertStringContainsString($cdnKeyName, $output);
These tests would be _much better_ if written individually and depending on each other (for example, see the "uptime check" tests in [monitoringTest.php](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/main/monitoring/test/monitoringTest.php#L62-L107)

2022-12-07 20:48 UTC, bshaffer commented on media/videostitcher/test/videoStitcherTest.php
> +    private static $updatedAkamaiKey = 'VGhpcyBpcyBhbiB1cGRhdGVkIHRlc3Qgc3RyaW5nLg==';
I assume these are test keys and don't actually contain any sensitive information, yes?

2022-12-07 21:57 UTC, irataxy commented on media/videostitcher/test/videoStitcherTest.php
> +    private static $updatedAkamaiKey = 'VGhpcyBpcyBhbiB1cGRhdGVkIHRlc3Qgc3RyaW5nLg==';
Correct, just gibberish or encoded "This is a test string"

2022-12-09 01:02 UTC, irataxy commented on media/videostitcher/test/videoStitcherTest.php
> +        $this->assertStringContainsString($cdnKeyName, $output);
Done

2022-12-16 22:31 UTC, bshaffer approved these changes

2022-12-16 23:27 UTC, merged