feat(analyticsdata): add samples for run_report with ordering, pagination, property quota
GoogleCloudPlatform/php-docs-samples pull request #1744
Opened 2022-12-12 17:50 UTC by anweshan

2022-12-28 21:36 UTC, bshaffer commented on analyticsdata/src/run_report.php
> +    // [END analyticsdata_initialize]
```suggestion
    // Create an instance of the Google Analytics Data API client library.
    $client = new BetaAnalyticsDataClient();
```

2022-12-28 21:37 UTC, bshaffer approved these changes

2022-12-28 21:47 UTC, bshaffer commented on analyticsdata/src/run_report_with_pagination.php
> + * using pagination.
PHPDoc tags should be last
```suggestion
 * Runs a report several times, each time retrieving a portion of result
 * using pagination.
 * @param string $propertyId Your GA-4 Property ID
```

2022-12-28 21:47 UTC, bshaffer commented on analyticsdata/src/run_report_with_ordering.php
> + * the total revenue in descending order.
```suggestion
 * Runs a report of active users grouped by three dimensions, ordered by
 * the total revenue in descending order.
 * @param string $propertyId Your GA-4 Property ID
```

2022-12-28 21:47 UTC, bshaffer commented on analyticsdata/src/run_report_with_property_quota.php
> + * Runs a report and prints property quota information.
```suggestion
 * Runs a report and prints property quota information.
 * @param string $propertyId Your GA-4 Property ID
```

2022-12-28 21:48 UTC, bshaffer approved these changes

2022-12-28 21:55 UTC, bshaffer commented on analyticsdata/src/run_report_with_property_quota.php
> +    if ($response.hasPropertyQuota()) {
```suggestion
    if ($response->hasPropertyQuota()) {
```

2022-12-28 21:55 UTC, bshaffer commented on analyticsdata/src/run_report_with_property_quota.php
> +       echo 'doesnt have it';
```suggestion
        echo 'doesnt have it';
```

2022-12-28 21:58 UTC, bshaffer requested changes

2022-12-28 21:58 UTC, bshaffer commented on analyticsdata/test/quickstartTest.php
> -}
Why are we removing this?

2022-12-28 21:59 UTC, bshaffer commented on analyticsdata/src/run_report_with_property_quota.php
> +use Google\Analytics\Data\V1beta\PropertyQuota;
remove unused use
```suggestion
```

2022-12-28 23:24 UTC, bshaffer commented on analyticsdata/test/quickstartTest.php
> +
```suggestion
```

2022-12-28 23:27 UTC, bshaffer commented on analyticsdata/src/run_report_with_property_quota.php
> +    }
I think this is outdated and needs to be updated. I looked through the merges to make sure that I didn't accidentally revert your changes, and I couldn't find anything.

2022-12-28 23:27 UTC, bshaffer commented on analyticsdata/test/quickstartTest.php
> -}
I think this was the result of a bad merge. I've added the test back.

2022-12-28 23:28 UTC, anweshan commented on analyticsdata/src/run_report_with_property_quota.php
> +    }
I think I accidentally overwrote this, instead of committing the correct version - seem to be having some merge conflicts on my end

2022-12-28 23:29 UTC, bshaffer commented on analyticsdata/src/run_report_with_property_quota.php
> +    }
That's my fault... I resolved the conflicts from `main`, but in the process made some things worse.

I would try looking through my local git history for the commit with the change, and try to cherry-pick it or just copy the printResponse function over.

2022-12-29 17:22 UTC, bshaffer approved these changes

2022-12-29 17:22 UTC, merged