feat(analyticsdata): add samples for metadata requests
GoogleCloudPlatform/php-docs-samples pull request #1745
Opened 2022-12-12 17:51 UTC by anweshan

2022-12-28 22:25 UTC, bshaffer requested changes

2022-12-28 22:25 UTC, bshaffer commented on analyticsdata/src/get_common_metadata.php
> +*/
```suggestion
 * Retrieves dimensions and metrics available for all Google Analytics 4 properties.
 */
```

2022-12-28 22:25 UTC, bshaffer commented on analyticsdata/src/get_common_metadata.php
> +   // printGetCommonMetadata($response);
This does not look right

2022-12-28 22:25 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> + */
this is not valid PHPDoc

2022-12-28 22:25 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> +    ]
looks like these are not formatted as we discussed

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_common_metadata.php
> +    */
```suggestion
    /**
     * Set the Property ID to 0 for dimensions and metrics common
     * to all properties. In this special mode, this method will
     * not return custom dimensions and metrics.
     */
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> +function get_metadata_by_property_id($propertyId)
```suggestion
function get_metadata_by_property_id(string $propertyId)
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_common_metadata.php
> +    $formattedName = 'properties/' . $propertyId . '/metadata';
Let's explicitly convert the int to a string
```suggestion
    $formattedName = sprintf('properties/%s/metadata', $propertyId);
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_common_metadata.php
> +function printGetCommonMetadata($response)
```suggestion
function printGetCommonMetadata(Metadata $response)
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> +    $formattedName = 'properties/' . $propertyId . '/metadata';
```suggestion
    $formattedName = sprintf('properties/%s/metadata', $propertyId);
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> +              . ' %s (including custom fields):' . PHP_EOL, $propertyId
```suggestion
            . ' %s (including custom fields):' . PHP_EOL,
        $propertyId
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> +function printGetMetadataByPropertyId($response)
```suggestion
function printGetMetadataByPropertyId(Metadata $response)
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> +            $dimension->getCustomDefinition()? 'true' : 'false'
```suggestion
            $dimension->getCustomDefinition() ? 'true' : 'false'
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_metadata_by_property_id.php
> +            $metric->getCustomDefinition()? 'true' : 'false'
```suggestion
            $metric->getCustomDefinition() ? 'true' : 'false'
```

2022-12-29 22:59 UTC, bshaffer commented on analyticsdata/src/get_common_metadata.php
> +    }
There's a lot of logic going on in these print functions - if we aren't going to have the automated tests cover them, have we at least had local testing to ensure they print results as expected?

2022-12-29 23:01 UTC, bshaffer commented on analyticsdata/test/analyticsDataTest.php
> +        $output = $this->runFunctionSnippet('get_common_metadata', [$propertyId]);
The tests are failing because `get_common_metadata()` doesn't take an argument
```suggestion
        $output = $this->runFunctionSnippet('get_common_metadata');
```

2022-12-30 00:51 UTC, anweshan commented on analyticsdata/src/get_common_metadata.php
> +    }
I've locally tested and they print results as expected

Stuff like
```
METRIC
userConversionRate:wfh_session (User conversion rate for wfh_session): The percentage of users who triggered a specific conversion event.
custom definition: false
```

2022-12-30 16:12 UTC, bshaffer approved these changes

2022-12-30 16:12 UTC, merged