chore: change READMEs to point to new docs urls
GoogleCloudPlatform/php-docs-samples pull request #1754
Opened 2022-12-13 23:35 UTC by bshaffer

2022-12-13 23:54 UTC, dwsupplee requested changes

2022-12-13 23:54 UTC, dwsupplee commented on firestore/README.md
>  [google-cloud-php-source]: https://github.com/GoogleCloudPlatform/google-cloud-php
I understand not updating these since it is unrelated, but just since I noticed - we might want to update the organization on these too.

2022-12-13 23:54 UTC, dwsupplee commented on speech/README.md
>  Library for PHP][google-cloud-php] to make REST calls as well as
```suggestion
Library for PHP][google-cloud-php-speech] to make REST calls as well as
```

2022-12-14 09:28 UTC, rsamborski commented on compute/cloud-client/firewall/README.md
> +[google-cloud-php]: https://cloud.google.com/php/docs/reference/cloud-compute/latest
```suggestion
[google-cloud-php-compute]: https://cloud.google.com/php/docs/reference/cloud-compute/latest
```

2022-12-14 09:36 UTC, rsamborski commented on compute/cloud-client/firewall/README.md
>  You can read the documentation for more details on API usage and use GitHub
For some reason I can't add suggestion to line 132, but please fix accordingly to my comment in line 136: `[google-cloud-php-compute]`

2022-12-14 09:36 UTC, rsamborski commented on compute/cloud-client/instances/README.md
> +[google-cloud-php]: https://cloud.google.com/php/docs/reference/cloud-compute/latest
```suggestion
[google-cloud-php-compute]: https://cloud.google.com/php/docs/reference/cloud-compute/latest
```

2022-12-14 09:37 UTC, rsamborski commented on compute/cloud-client/instances/README.md
>  You can read the documentation for more details on API usage and use GitHub
Same here, please change in line 161 to: `[google-cloud-php-compute]`

2022-12-14 18:46 UTC, anweshan commented
Can the site http://googleapis.github.io/google-cloud-php/ redirect to this URL as well?

2022-12-14 20:50 UTC, bshaffer commented on compute/cloud-client/firewall/README.md
>  You can read the documentation for more details on API usage and use GitHub
done!

2022-12-14 20:55 UTC, bshaffer commented
@anweshan we are working on it! We would like this to be the case, yes

2022-12-14 21:44 UTC, bshaffer commented on firestore/README.md
>  [google-cloud-php-source]: https://github.com/GoogleCloudPlatform/google-cloud-php
There _might_ be a good reason we are keeping the samples here instead of as part of `googleapis` (for instance, we have samples for things outside the API clients like as for deploying to Cloud Run)

2022-12-14 22:01 UTC, dwsupplee commented on firestore/README.md
>  [google-cloud-php-source]: https://github.com/GoogleCloudPlatform/google-cloud-php
I didn't mean to suggest we change this repo to live under googleapis, just that the link here (e.g., https://github.com/GoogleCloudPlatform/google-cloud-php) redirects to https://github.com/googleapis/google-cloud-php, so it might be worthwhile to update it accordingly to skip the redirect.

2022-12-15 00:24 UTC, dwsupplee approved these changes

2022-12-15 01:04 UTC, merged