feat(Spanner): Add FGAC Samples
GoogleCloudPlatform/php-docs-samples pull request #1766
Opened 2023-01-17 15:46 UTC by ajupazhamayil

2023-01-18 12:49 UTC, vishwarajanand requested changes
Thanks for adding these changes, I have few comments which is better to resolve before merge.

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/test/spannerTest.php
> +        ]);
abstract out client into a different method (maybe `getIamHttpClient`), so that its not duped in `createServiceAccount` and `deleteServiceAccount` and these methods only deal with the actual operation of creation/deletion.

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/src/add_drop_database_role.php
> +    $roleParent = $databaseRole;
this var isn't needed?

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped role %s %s', $roleChild, PHP_EOL);
No space needed?
```suggestion
    printf('Revoked privileges and dropped role %s%s', $roleChild, PHP_EOL);
```

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/test/spannerTest.php
> +        self::$databaseRole]);
nit: formating
```suggestion
        $output = $this->runFunctionSnippet('add_drop_database_role', [
            self::$instanceId,
            self::$databaseId,
            self::$databaseRole
        ]);
```

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/test/spannerTest.php
> +        $this->assertStringContainsString('Revoked privileges and dropped role new_child ' . PHP_EOL, $output);
if you fix the above comment, probably this needs to be fixed as below:

```suggestion
        $this->assertStringContainsString('Revoked privileges and dropped role new_child' . PHP_EOL, $output);
```

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/test/spannerTest.php
> +        self::$databaseRole]);
Same for other tests

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/test/spannerTest.php
> +     * @depends testInsertDataWithDml
Is this needed, why?

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/test/spannerTest.php
> +        $this->assertStringContainsString('Enabled fine-grained access in IAM.', $output);
If you accept suggestion above, this needs to be changed:

```suggestion
        $this->assertStringContainsString('Enabled fine-grained access in IAM', $output);
```

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/src/enable_fine_grained_access.php
> +    printf('Enabled fine-grained access in IAM.' . PHP_EOL);
Usually we don't add full stop into print statements:

```suggestion
    printf('Enabled fine-grained access in IAM' . PHP_EOL);
```

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/test/spannerTest.php
> +        if (self::$serviceAccountEmail !== null) {
```suggestion
        if (!is_null(self::$serviceAccountEmail)) {
```

2023-01-18 12:49 UTC, vishwarajanand commented on spanner/src/add_drop_database_role.php
> +function add_drop_database_role(string $instanceId, string $databaseId, string $databaseRole): void
Consider checking with Spanner team, whether they have any preference to add `databaseRole` as a param or hardcoded string.
This gets published on cgc, so we wish to maintain uniformity with other languages.

2023-01-18 12:50 UTC, vishwarajanand commented
@ajupazhamayil also update the description of PR, since now the tests for `spanner_enable_fine_grained_access` are added.

2023-01-18 14:30 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +    printf('Revoked privileges and dropped role %s %s', $roleChild, PHP_EOL);
Done

2023-01-18 14:34 UTC, ajupazhamayil commented on spanner/test/spannerTest.php
> +        $this->assertStringContainsString('Revoked privileges and dropped role new_child ' . PHP_EOL, $output);
Done

2023-01-18 14:36 UTC, ajupazhamayil commented on spanner/test/spannerTest.php
> +     * @depends testInsertDataWithDml
Its because, the test has the following pre-requisites:
1. Need the role `new_parent` so that the function can read with that role
2. The table should have the required data inserted.
Thats what those 2 dependencies are doing

2023-01-18 14:36 UTC, ajupazhamayil commented on spanner/test/spannerTest.php
> +        $this->assertStringContainsString('Enabled fine-grained access in IAM.', $output);
Done

2023-01-18 14:37 UTC, ajupazhamayil commented on spanner/src/enable_fine_grained_access.php
> +    printf('Enabled fine-grained access in IAM.' . PHP_EOL);
Done

2023-01-18 14:37 UTC, ajupazhamayil commented on spanner/test/spannerTest.php
> +        if (self::$serviceAccountEmail !== null) {
Done

2023-01-18 14:42 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +function add_drop_database_role(string $instanceId, string $databaseId, string $databaseRole): void
The C# implemented as https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/2013/files#diff-b341473197a2d1aa585e3b271a0c0b88cb846d20f1edcc9c1320b394f53ad65c and Ruby implemented as https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/2013/files#diff-b341473197a2d1aa585e3b271a0c0b88cb846d20f1edcc9c1320b394f53ad65c

Basically one has `databaseRole` and the other does not. Will wait for your reply on what to do here.

2023-01-19 07:04 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +function add_drop_database_role(string $instanceId, string $databaseId, string $databaseRole): void
Done the changes to align with Ruby. Thank you!

2023-01-19 09:32 UTC, vishwarajanand commented on spanner/src/add_drop_database_role.php
> +        sprintf('DROP ROLE %s', $roleChild)
Why is this change needed?
Not dropping `roleParent` might lead to accumulation of roles on the DB which is capped to 100 per DB, [ref](https://cloud.google.com/spanner/quotas#database-limits).

2023-01-19 09:36 UTC, ajupazhamayil commented on spanner/src/add_drop_database_role.php
> +        sprintf('DROP ROLE %s', $roleChild)
This is required because we need this role for the next two tests.

Then not dropping this will not make any issues because the roles reside inside the DB and when the DB get dropped, this role also goes away. This is how other languages also did.

Ref: https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/1010/files#diff-a9737d3799347782cca3742a8ff9cfd5ae93159f34ac381a8e8d06d56ce5ff21R42

They never dropped the parent role.

2023-01-19 09:56 UTC, vishwarajanand commented on spanner/src/enable_fine_grained_access.php
> + * the IAM member.
```suggestion
 * @param string $iamMember The IAM member. Eg: `user:{emailid}`, 
 *        `serviceAccount:{emailid}`, `group:{emailid}`, `domain:{domain}`
 * @param string $databaseRole The database role bound to
 *        the IAM member.
```

2023-01-19 09:58 UTC, vishwarajanand commented on spanner/src/enable_fine_grained_access.php
> +    ): void {
```suggestion
): void {
```

2023-01-19 09:59 UTC, vishwarajanand commented on spanner/src/enable_fine_grained_access.php
> +            'expression' => sprintf("resource.name.endsWith('/databaseRoles/%s')", $databaseRole)
```suggestion
                'title' => $title,
                'expression' => sprintf("resource.name.endsWith('/databaseRoles/%s')", $databaseRole)
```

2023-01-19 10:00 UTC, vishwarajanand commented on spanner/src/enable_fine_grained_access.php
> +            ])
```suggestion
        ])
```

2023-01-19 10:01 UTC, vishwarajanand commented on spanner/src/list_database_roles.php
> +    ): void {
```suggestion
): void {
```

2023-01-19 10:36 UTC, vishwarajanand commented
I commented out `testCreateDatabaseWithEncryptionKey` and ran the tests in this PR and they ran successfully:

```
php-docs-samples/spanner % XDEBUG_MODE=coverage ../testing/vendor/bin/phpunit -c phpunit.xml.dist test/spannerTest.php --filter="testCreateInstance|testCreateDatabase|testAddDropDatabaseRole|testInsertDataWithDml|testReadDataWithDatabaseRole|testReadDataWithDatabaseRole"
PHPUnit 8.5.26 #StandWithUkraine

.......                                                             7 / 7 (100%)

Time: 2.02 minutes, Memory: 14.00 MB

OK (7 tests, 13 assertions)

Generating code coverage report in Clover XML format ... done [488 ms]
php-docs-samples/spanner %
```

Beyond style nits and checks, I have no comments on this PR.

2023-01-19 11:08 UTC, ajupazhamayil commented
@vishwarajanand Done all the changes you suggested, Thank you!

2023-01-19 16:36 UTC, vishwarajanand commented on spanner/src/read_data_with_database_role.php
> +        printf('SingerId: %s, Firstname: %s, LastName: %s' . PHP_EOL, $row['SingerId'], $row['FirstName'], $row['LastName']);
```suggestion
        printf(
            'SingerId: %s, Firstname: %s, LastName: %s' . PHP_EOL, 
            $row['SingerId'], 
            $row['FirstName'], 
            $row['LastName']
        );
```

2023-01-19 16:39 UTC, vishwarajanand approved these changes
leaving 2 nits, but LGTM otherwise.

2023-01-23 08:48 UTC, vishwarajanand commented on spanner/src/enable_fine_grained_access.php
> +    if ($policy->getVersion() != 3) {
```suggestion
    // IAM conditions need at least version 3
    if ($policy->getVersion() != 3) {
```

2023-01-23 08:49 UTC, ajupazhamayil commented on spanner/src/enable_fine_grained_access.php
> +    }
Added a comment, thank you!

2023-01-23 08:50 UTC, ajupazhamayil commented on spanner/src/read_data_with_database_role.php
> +        printf('SingerId: %s, Firstname: %s, LastName: %s' . PHP_EOL, $row['SingerId'], $row['FirstName'], $row['LastName']);
We already have similar length line in the same file, So, we are good here, thank you!

2023-01-23 09:19 UTC, merged

2023-01-23 19:41 UTC, bshaffer commented on spanner/src/read_data_with_database_role.php
> +        printf('SingerId: %s, Firstname: %s, LastName: %s' . PHP_EOL, $row['SingerId'], $row['FirstName'], $row['LastName']);
We do not want to exceed 80, and this length is 126. This is too long, and we should update it in a follow-up PR (i'm surprised this passed our linter)