feat[BigqueryStorage]: Added quickstart sample
GoogleCloudPlatform/php-docs-samples pull request #1781
Opened 2023-03-03 04:23 UTC by yash30201

This sample showcases a basic quickstart for using the Bigquery Storage API.

The corresponsing published samples are [here](https://cloud.google.com/bigquery/docs/samples/bigquerystorage-quickstart)

2023-03-05 02:58 UTC, yash30201 commented on bigquerystorage/composer.json
> +        "google/cloud-bigquery-storage": "^1.2"
This is the latest stable version of cloud bigquery storage, do we go ahead with this?

2023-03-05 02:59 UTC, yash30201 commented on bigquerystorage/phpunit.xml.dist
> +        <testsuite name="Google BigQuery Storage Quickstart Tests">
This name is just to describe the test configuration, right? Or is there any convention for it?

2023-03-05 03:01 UTC, yash30201 commented on bigquerystorage/phpunit.xml.dist
> +            <file>quickstart.php</file>
It's directly specified to the `quickstart.php` file because we are required to create a basic quickstart for this product just like `bigquerydatatranfer API`.

2023-03-05 03:07 UTC, yash30201 commented
I was confused on how to write this sample between a functional format or a standalone script format and then choose the script style as this felt inline as a quickstart.

2023-04-04 12:04 UTC, vishwarajanand commented on bigquerystorage/composer.json
> +        "google/cloud-bigquery-storage": "^1.2"
Confirmed the [release version to 1.2.11](https://github.com/googleapis/google-cloud-php-bigquery-storage/releases/tag/v1.2.11)

2023-04-04 17:25 UTC, vishwarajanand commented on bigquerystorage/quickstart.php
> +}
This code-snippet will never execute, you needed to pass it as an argument.

2023-04-04 17:32 UTC, vishwarajanand commented on bigquerystorage/test/quickstartTest.php
> +        $contents = file_get_contents(__DIR__ . '/../quickstart.php');
Why are we copying the contents to a temp script?

2023-04-04 17:41 UTC, vishwarajanand commented on bigquerystorage/test/quickstartTest.php
> +        );
Consider also doing this for `$snapshotMillis`, something like below:

```suggestion
        $milliseconds = floor(microtime(true) * 1000);
        $contents = str_replace(
            ['YOUR_PROJECT_ID', 'YOUR_SNAPSHOT_MILLIS', '__DIR__'],
            [$projectId, $milliseconds, sprintf('"%s/.."', __DIR__)],
            $contents
        );
```

2023-04-04 17:52 UTC, vishwarajanand commented on bigquerystorage/quickstart.php
> +}
In python ([code pointer link](https://github.com/googleapis/python-bigquery-storage/blob/ad439bc83e52e753805ceca6e35a5f307e72a0c7/samples/quickstart/quickstart_test.py#L27-L36)), we are testing against **(A)** not setting the snapshotMillis at all _AND_ **(B)** passing a value of current time in milliseconds minus 5000.
Maybe replicate that here as well in two different test methods?

2023-04-04 17:53 UTC, vishwarajanand commented on bigquerystorage/test/quickstartTest.php
> +        $contents = file_get_contents(__DIR__ . '/../quickstart.php');
Understood, this is needed to replace the values of variables.

2023-04-04 17:54 UTC, vishwarajanand requested changes
Pls re-structure the code to make use of snapshit millis as an argument and the avro package.

2023-04-05 08:42 UTC, vishwarajanand commented on bigquerystorage/test/quickstartTest.php
> +        $expected = sprintf('Got 6482 unique names in states: WA');
Both these assertions are same and might result in test pass when only one of the invocations give correct output. 
Pls split to two test methods (cleanest) _OR_ including the `$file` again without timestamp and just compare its output.

2023-04-05 08:44 UTC, vishwarajanand commented on bigquerystorage/quickstart.php
> +    }
There is a duplication of code. It would be better to call `getRowsStream` just once. 
Previous design was neater, to call `setSnapshotTime` when timestamp is provided. Previously we were not setting the timestamp value.

2023-04-05 19:35 UTC, merged

2023-04-05 19:36 UTC, bshaffer commented on bigquerystorage/quickstart.php
> +$snapshotMillis = 'YOUR_SNAPSHOT_MILLIS';
Why not just supply a default value here? It seems strange to require this since it's not actually required for the sample to work (like `projectId` is)

2023-04-05 19:40 UTC, bshaffer commented on bigquerystorage/quickstart.php
> +$snapshotMillis = 'YOUR_SNAPSHOT_MILLIS';
I've been told that this is probably referenced in the devsite docs because other languages have the same requirement, so LGTM!