chore: Allowed composer logs
GoogleCloudPlatform/php-docs-samples pull request #1860
Opened 2023-06-28 08:55 UTC by yash30201

This PR is to inpect what versions of product libraries are getting installed.

2023-06-28 21:59 UTC, bshaffer requested changes

2023-06-28 21:59 UTC, bshaffer commented on bigtable/src/create_app_profile.php
> +    $instanceAdminClient = 'Hello';
?

2023-06-29 07:43 UTC, yash30201 commented on bigtable/src/create_app_profile.php
> +    $instanceAdminClient = 'Hello';
This PR is just a test PR to enable composer logs while they install packages for gcp products. Earlier we had a `-q` flag.

I've verified that after the gax version upgrade, we've solved the issue of authentication scopes not passing properly so I'll close this PR now.

2023-06-29 07:45 UTC, yash30201 commented
This is obselete, hence closing this now.

2023-06-29 07:45 UTC, closed without merging