feat(functions): create new samples for typed function signature
GoogleCloudPlatform/php-docs-samples pull request #1866
Opened 2023-07-11 23:35 UTC by garethgeorge

Creates new samples for GCF python strongly typed function signature. Samples added are

 * greeting - a typed hello world (accepting JSON)
 * googlechatbot - a typed function that matches the functionality documented in https://developers.google.com/chat/quickstart/gcf-app

2023-07-20 17:52 UTC, garethgeorge commented
CC @bshaffer for familiarity with the typed functions project (if you have review bandwidth)

2023-07-27 21:41 UTC, bshaffer requested changes
One suggestion - can simplify tests into into one file by copying the method over. Traits are typically for code reuse, so if you're only including the trait in one test, it doesn't really make sense. 

If you think you'll be a `SystemTest` or `DeployTest` soon (like we have in the other function samples), then we can keep them!

2023-07-27 21:41 UTC, bshaffer commented on functions/typed_greeting/test/TestCasesTrait.php
> +}
Just for simplicity I'd just put this function in the `UnitTest.php` file for simplification

2023-08-07 18:49 UTC, garethgeorge commented on functions/typed_greeting/test/TestCasesTrait.php
> +}
Thanks @bshaffer! Makes sense, I don't think we'll be needing more tests out of this sample.

2023-08-17 21:48 UTC, grayside approved these changes

2023-08-22 19:58 UTC, bshaffer approved these changes

2023-08-22 19:58 UTC, bshaffer commented on functions/typed_greeting/test/UnitTest.php
> +require_once __DIR__ . '/TestCasesTrait.php';
```suggestion
```

2023-08-22 20:12 UTC, merged