feat(spanner): Replace database admin samples
GoogleCloudPlatform/php-docs-samples pull request #1966
Opened 2024-02-14 18:58 UTC by ajupazhamayil

2024-02-16 19:33 UTC, vishwarajanand commented on spanner/src/add_column.php
> +function add_column(string $projectId, string $instanceId, string $databaseId): void
instead you can just do with full database name?
But either way works.. pls ensure this is consistent with other languages

2024-02-16 19:35 UTC, vishwarajanand commented on spanner/src/add_column.php
>  // [START spanner_add_column]
Will the tag remain the same? I mean the `src/add_column` **VS** `admin/archives/add_column`?

2024-02-16 19:41 UTC, vishwarajanand commented on spanner/test/spannerBackupTest.php
> +    private function runAdminFunctionSnippet($sampleName, $params = [])
Can you try to make this function coherent with the other two implementation which are same but different from this one, and move it to a common place like `SpannerTestCase`?

2024-02-16 19:41 UTC, vishwarajanand commented on spanner/test/spannerBackupTest.php
> +    private function runAdminFunctionSnippet($sampleName, $params = [])
I am not sure whether its doable entirely..

2024-02-16 19:42 UTC, vishwarajanand requested changes
Left few questions for clarifications

2024-02-16 21:09 UTC, ajupazhamayil commented on spanner/src/add_column.php
>  // [START spanner_add_column]
Yes, tags remains same

2024-02-16 21:14 UTC, ajupazhamayil commented on spanner/src/add_column.php
> +function add_column(string $projectId, string $instanceId, string $databaseId): void
I see `Java` used this way here: https://github.com/googleapis/java-spanner/blob/c58042375a216ec42330cc7a11b22f3b1d3c450b/samples/snippets/src/main/java/com/example/spanner/CreateSequenceSample.java#L43

So, we are in sync with Java

2024-02-16 21:17 UTC, ajupazhamayil commented on spanner/test/spannerBackupTest.php
> +    private function runAdminFunctionSnippet($sampleName, $params = [])
Yeah, I am also not sure, I have added it here since they already have other functions locally. Also, its just a function call from the trait. Let me know if it needs to be moved. I am okay with both.

2024-02-16 21:18 UTC, ajupazhamayil commented
Second PR raised here: https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1966

2024-02-18 17:22 UTC, ajupazhamayil commented on spanner/test/spannerBackupTest.php
> +    private function runAdminFunctionSnippet($sampleName, $params = [])
Also, I have removed this function from `spannerBackupTest` file as it is not required there. So, this is a function that required by two of the test files in a little different way.

2024-02-19 15:12 UTC, vishwarajanand commented on spanner/src/admin/archived/list_database_operations.php
Seems this the admin-samples are supposed to be in `/src` as well as `/src/archived`.
But I don't see this being followed for following files:
```
src/enable_fine_grained_access.php
src/get_instance_config.php
src/list_database_operations.php
src/list_instance_configs.php
```

2024-02-19 15:15 UTC, vishwarajanand commented on spanner/src/admin/archived/list_database_operations.php
Okay, I see the three of these are covered in #1969 but not the `enable_fine_grained_access` can you check why its only in src and not in src/admin/archived as well?

2024-02-19 15:18 UTC, vishwarajanand commented
One more Q, why do we have `admin/archived` and not just `admin`?

2024-02-19 15:28 UTC, vishwarajanand approved these changes
I tested that the new samples are passing in tests, follow our style guide and they indeed run correct functionality. 
I also see that kokoro tests are running, so the changes lgtm.

2024-02-20 07:53 UTC, ajupazhamayil commented on spanner/src/admin/archived/list_database_operations.php
Its because `enable_fine_grained_access` was already using the required auto generated admin client. I just modified the way the sample creates `databaseName` just for simplicity. But I still created a copy of it just for completion. Thank you!

2024-02-20 07:54 UTC, ajupazhamayil commented
Third PR raised here https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1973

2024-02-20 08:08 UTC, ajupazhamayil commented
Other two PRs are merged to this branch. We will wait for the green signal from Spanner team to merge this PR to `main`.

Other two PRs are:
PR1: https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1969
PR2: https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1973

2024-03-04 06:53 UTC, merged