feat(spanner): add MR CMEK samples
GoogleCloudPlatform/php-docs-samples pull request #2044
Opened 2024-08-28 15:49 UTC by panerorenn9541

Add samples and tests for create database, create backup, copy backup, and restore backup.

2024-09-03 20:54 UTC, Hectorhammett requested changes

2024-09-03 20:54 UTC, Hectorhammett commented on spanner/src/copy_backup_with_MR_CMEK.php
> +    string $sourceBackupId
Missing `,`

2024-09-03 20:54 UTC, Hectorhammett commented on spanner/src/copy_backup_with_MR_CMEK.php
> +    } else {
This is just a nit, but I always believe that is best to handle errors before the "main logic" or "happy path" if you will:
```php
if (!operationResponse->operationSucceeded()) {
     $error = $operationResponse->getError();
     printf('Backup not created due to error: %s.' . PHP_EOL, $error->getMessage());
     return;
}
...
```

That way the happy path and what the code is aiming to perform is on the main indentation and easier to glance at.

2024-09-03 20:54 UTC, Hectorhammett commented
Looking good but there are some errors on the syntax and style on the tests :).

2024-09-05 19:40 UTC, Hectorhammett approved these changes

2024-09-06 21:52 UTC, Hectorhammett approved these changes

2024-09-09 19:59 UTC, bshaffer commented on spanner/src/copy_backup_with_MR_CMEK.php
> +function copy_backup_with_MR_CMEK(
nit: all sample names (and filenames) are lowercase in this repo. Let's be consistent!

2024-09-09 19:59 UTC, bshaffer commented on spanner/src/create_backup_with_MR_CMEK.php
> +// [START spanner_create_backup_with_MR_CMEK]
Same with sample region tags

2024-09-09 20:49 UTC, panerorenn9541 commented on spanner/src/create_backup_with_MR_CMEK.php
> +// [START spanner_create_backup_with_MR_CMEK]
The tags I got from Tina and we are using the same tags in all languages

2024-10-15 20:39 UTC, bshaffer approved these changes

2024-10-18 18:43 UTC, merged